## First

In [ ]:
# -*- coding: utf-8 -*-
%load_ext autoreload
%autoreload 2

In [10]:
! pip install json-repair

Requirement already satisfied: json-repair in /home/ek/Documents/10Xtutor/SIFA/tenx_ipersona/env/lib/python3.10/site-packages (0.27.2)

In [6]:
data = {
    "id": "499",
    "attributes": {
        "slug": "all_user_id: 1920",
        "status": "Incomplete",
        "attributes": {
            "persona": "Act as an experienced HR analyst with expertise in evaluating job descriptions and user profiles. \n\n",
            "generated_questions": {}

        },
        "createdAt": "2025-01-13T08:45:43.721Z",
        "i_persona_observer": {"data": None},
        "tinder_job_profile": {"data": {"id": "232"}},
        "tinder_user_profile": {"data": {"id": "164"}},
        "updatedAt": "2025-01-13T08:45:43.721Z",
    }
}

def remove_key(data, key_to_remove):
    if isinstance(data, dict):
        if key_to_remove in data and isinstance(data[key_to_remove], dict):
            del data[key_to_remove]
        for key, value in data.items():
            remove_key(value, key_to_remove)
    elif isinstance(data, list):
        for item in data:
            remove_key(item, key_to_remove)

# Call the function to remove 'generated_questions'
remove_key(data, 'generated_questions')

# Display the updated data
data

{'id': '499',
 'attributes': {'slug': 'all_user_id: 1920',
  'status': 'Incomplete',
  'attributes': {'persona': 'Act as an experienced HR analyst with expertise in evaluating job descriptions and user profiles. \n\n'},
  'createdAt': '2025-01-13T08:45:43.721Z',
  'i_persona_observer': {'data': None},
  'tinder_job_profile': {'data': {'id': '232'}},
  'tinder_user_profile': {'data': {'id': '164'}},
  'updatedAt': '2025-01-13T08:45:43.721Z'}}

In [11]:
import json, json_repair
def extract_jsons(response, quite=False):    
    if isinstance(response, (dict, list)):
        # return as it is 
        # if not quite: print("extract_json", "response is already in json format")
        return response       
    elif isinstance(response, str):
        # Method 1
        try:
            # try simple to load it as json
            res = json.loads(response)
            # if not quite: print("extract_json", "response is already in jsons format")
            return res
        except:
            pass
            # if not quite: print("extract_json: simple json load failed. Trying to fix json string ...")
           
        # Method 2 
        try:
            # if not quite: print("extract_json", "response is not in json format. Trying to extract json from response")
            if '```json' in text:                
                out = text.split('```json')[1].split('```')[0].replace('\n','')
            elif '```' in text:
                out = text.split('```')[1].split('```')[0].replace('\n','')
            else:
                out = text

            res = json.loads(out)
            return res        
        except Exception as e:
            # if not quite: print(f"extract_json: unable to fix json string. Trying with json_repair ...")
            pass         
            # it is not in json string format
            
            # Method 3
            text = response
            try:                
                res = json_repair.loads(text)
                if isinstance(res, (dict, list)):
                    # if not quite: print("extract_json: result obtained using repair json")
                    return res
            except:
                if not quite: print("extract_json: unable to repair json string using json_repair. Raise exception")
                raise
    else:
        # if not quite: print("extract_json", "response is not a string or a dictionary")
        return {}

:

In [12]:
response = """
    Overall, you have demonstrated qualities that align with the role's requirements outlined in the job description. Your performance was Good.

    { "evaluation": { "percentage": "80%", "message": "Good" } }

    I would like to offer you the opportunity for a follow-up interview. If you agree, we can conduct a new round of fresh, diverse questions, including more technical questions related to the specific position you are applying for. Would you like to proceed?
"""
val = extract_json(response)

NameError: name 'extract_json' is not defined

In [14]:
import json
import json_repair

def extract_json(response, quite=False):    
    if isinstance(response, (dict, list)):
        return response, ""  # Return as it is       
    elif isinstance(response, str):
        # Initialize variables
        json_part = None
        
        # Method 1: Try simple JSON load
        try:
            json_part = json.loads(response)
            return json_part, ""  # Return if already valid JSON with empty text
        except:
            pass
        
        # Method 2: Attempt to extract JSON from response
        try:
            # Find the first occurrence of '{' and the last occurrence of '}'
            start_index = response.index('{')
            end_index = response.rindex('}') + 1
            json_str = response[start_index:end_index]
            json_part = json.loads(json_str)
            # Remove the JSON part from the original response
            non_json_part = response.replace(json_str, '').strip()
            return json_part, non_json_part        
        except Exception:
            pass
            
        # Method 3: Try using json_repair
        try:                
            repaired_json = json_repair.loads(response)
            if isinstance(repaired_json, (dict, list)):
                repaired_json_str = json.dumps(repaired_json)  # Convert to string
                non_json_part = response.replace(repaired_json_str, '').strip()  # Remove JSON part from original response
                return repaired_json, non_json_part
        except:
            if not quite:
                print("extract_json: unable to repair json string using json_repair. Raise exception")
            raise

    # If no valid JSON was found, return None for both
    return None, None

# Example usage
response = """
    Overall, you have demonstrated qualities that align with the role's requirements outlined in the job description. Your performance was Good.

    

    I would like to offer you the opportunity for a follow-up interview. If you agree, we can conduct a new round of fresh, diverse questions, including more technical questions related to the specific position you are applying for. Would you like to proceed?
"""

json_output, other_text = extract_json(response)
print("JSON Output:", json_output)
print("Other Text:", other_text)

JSON Output: None
Other Text: None

In [15]:
# import pandas as pd

# df = pd.read_csv('./dataset/job_match.csv', index_col=0)

# json_data = df.to_json(orient='records', lines=True)

# with open('./dataset/job_match.json', 'w') as json_file:
#     json_file.write(json_data)

# print(json_data)

In [19]:
import pandas as pd
import pprint as pp
# df = pd.read_csv('./dataset/extracted/job_match.csv', index_col=0)
# len(df)
# df.head()

In [17]:
filtered_df = df[df['match_attributes_overall_match_degree'].isin(['very high'])]
# Assign to result_df
result_df = filtered_df

NameError: name 'df' is not defined

In [18]:
# Get unique user_profile_ids
unique_user_ids = result_df['user_profile_id'].unique()

# Create a dictionary to store results
user_data = {}

# Fetch 3 rows for each unique user_profile_id
for user_id in unique_user_ids:
    user_data[user_id] = result_df[result_df['user_profile_id'] == user_id].head(3)

# Optionally, convert the dictionary to a DataFrame for better display
final_result_df = pd.concat(user_data.values())

len(final_result_df)

# final_result_df

NameError: name 'result_df' is not defined

In [19]:
df['match_attributes_overall_match_degree'].unique()

NameError: name 'df' is not defined

In [20]:
result_df['user_profile_id'].unique()

NameError: name 'result_df' is not defined

In [ ]:
result_df['job_profile_id'].unique()

In [ ]:
df2 = pd.read_csv('./dataset/extracted/job_profile.csv', index_col=0)
len(df2)
# df2.head()

In [13]:
job_profile_ids = [1035, 1041, 1086, 808, 929, 616, 190, 191, 49, 197, 618, 621, 52]

filtered_job_profiles = df2[df2['job_profile_id'].isin(job_profile_ids)]

len(filtered_job_profiles)

#filtered_job_profiles['job_profile_id'].unique()

11

In [14]:
df3 = pd.read_csv('./dataset/extracted/user_profile.csv', index_col=0)
len(df3)

30

In [ ]:
# Define the user_profile_ids to fetch
user_profile_ids = [197, 167, 176, 183, 189, 180]

filtered_user_profiles = df3[df3['user_profile_id'].isin(user_profile_ids)]

# Display the filtered job profiles
len(filtered_user_profiles)
json_data = filtered_user_profiles.to_json(orient='records', lines=True)

with open('./dataset/final/user_profiles.json', 'w') as json_file:
    json_file.write(json_data)

In [ ]:
pp.pprint(len(df))
df.columns.tolist()
'user_job_match_id',
'job_profile_id',
'user_profile_id',
'match_attributes_overall_match_score',
'match_attributes_overall_match_degree',

In [ ]:
df = pd.read_csv('./dataset/job_match.csv')

# List of columns to keep
columns_to_keep_job_match = [
    'user_job_match_id',
    'job_profile_id',
    'user_profile_id',
    'match_attributes_overall_match_score',
    'match_attributes_overall_match_degree'
]

# Create a new DataFrame with only the specified columns
new_job_match_df = df[columns_to_keep_job_match]
new_job_match_df.to_csv('./dataset/extracted/extracted_job_match.csv')
# Display the new DataFrame
print(new_job_match_df)

In [23]:
df2 = pd.read_csv('./dataset/job_profile.csv')
print(len(df2))
df2.columns.to_list()

1000

['job_profile_id',
 'job_id',
 'title',
 'category',
 'level',
 'label',
 'location',
 'summary',
 'tags',
 'applyLink',
 'job_id.1',
 'role',
 'purpose',
 'apply_link',
 'posted_date',
 'company_info_name',
 'company_info_size',
 'company_info_summary',
 'company_name',
 'competencies_name',
 'competencies_summary',
 'competencies_relevance',
 'competencies_sfia_level',
 'competencies_rationale_name',
 'job_is_a_fit',
 'salary_range',
 'application_url',
 'employment_type',
 'rationale_is_a_fit',
 'job_is_fully_remote',
 'input_is_job_description',
 'job_posted_at_datetime_utc',
 'job_offer_expiration_datetime_utc',
 'createdAt',
 'duties_responsibilities',
 'required_qualifications',
 'preferred_qualifications',
 'url',
 'company_info_location',
 'company_info_mission',
 'company_info_values',
 'company_info_overview',
 'required_qualifications_Education',
 'competencies_rationale_sfia_level',
 'company_info_annual_revenue',
 'competencies_other_attributes',
 'company_info_website',
 'company_info_instagram',
 'company_info_example_school',
 'company_info_revenue',
 'company_info_headquarters',
 'company_info_central_office',
 'company_info_funding',
 'company_info_additional_info',
 'company_info_diversity_inclusion',
 'company_info_founded',
 'company_info_industry',
 'required_competencies_name',
 'required_competencies_summary',
 'required_competencies_relevance',
 'required_competencies_sfia_level',
 'required_competencies_rationale_name',
 'weaviate_uuid',
 'company_info_status',
 'company_info_country',
 'company_info_year_founded',
 'company_info_locations',
 'company_info_global_offices',
 'company_info_other_info_website',
 'company_info_other_info_equal_opportunity_statement',
 'company_info_stage',
 'source_{k}',
 'company_info_culture',
 'company_info_links_Twitter',
 'company_info_links_LinkedIn',
 'company_info_name:']

In [23]:
df2 = pd.read_csv('./dataset/combined_job_data.csv')
df2.columns

Index(['job_profile_id', 'required_qualifications', 'duties_responsibilities',
       'purpose', 'role', 'competencies'],
      dtype='object')

In [ ]:
# Read the CSV file into a DataFrame
df2 = pd.read_csv('./dataset/combined_job_data.csv')

# List of columns to keep
columns_to_keep_job_profile = [
    "title",
    "category",
    "location",
    "summary",
    "job_profile_id",
    "attributes.role",
    "attributes.level",
    "attributes.title",
    "attributes.purpose",
    "attributes.location",
    "attributes.apply_link",
    "attributes.posted_date",
    "attributes.company_info.name",
    "attributes.company_info.summary",
    "attributes.company_name",
    "attributes.competencies",
    "attributes.job_is_a_fit",
    "attributes.salary_range",
    "attributes.application_url",
    "attributes.employment_type",
    "attributes.rationale_is_a_fit",
    "attributes.job_is_fully_remote",
    "attributes.duties_responsibilities",
    "attributes.required_qualifications",
    "attributes.preferred_qualifications",
    "attributes.company_info.size",
    "attributes.company_info.founded",
    "attributes.company_info.website",
    "attributes.company_info.industry",
    "attributes.company_info.mission"
]

# Create a new DataFrame with only the specified columns
new_job_df = df2[columns_to_keep_job_profile]
new_job_df.to_csv('./dataset/extracted_job_profile.csv')
# Display the new DataFrame
print(new_job_df)

In [25]:
df3 = pd.read_csv('./dataset/user_profile_data.csv')
print(len(df3))
df3.head()

29

,name,display,description,profile_type,user_profile_id,awards.code,awards.name,awards.display,awards.template,awards.attributes,...,work_experience.attributes,work_experience.description,work_experience.profile_type,programing_languages.code,programing_languages.name,programing_languages.display,programing_languages.template,programing_languages.attributes,programing_languages.description,programing_languages.profile_type
0,user_profile,User Profile,User profile information,user_profile,11,awards,awards,Awards,form,"[{'date': '2023-06-30', 'uuid': 'c53f0125-6dc5...",...,"[{'role': 'Software Engineering Fellowship', '...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
1,user_profile,User Profile,User profile information,user_profile,16,awards,awards,Awards,form,[],...,"[{'role': 'Full-stack Developer', 'uuid': '323...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
2,user_profile,User Profile,User profile information,user_profile,8,awards,awards,Awards,form,[],...,[],Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
3,user_profile,User Profile,User profile information,user_profile,21,awards,awards,Awards,form,"[{'date': '', 'uuid': 'e69f2a9d-3b30-45de-ab02...",...,"[{'role': 'Data engineering, Machine learning ...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
4,user_profile,User Profile,User profile information,user_profile,4,awards,awards,Awards,form,[],...,"[{'role': 'Software Engineer', 'uuid': '04d46b...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages

In [26]:
df3.columns.to_list()

['user_profile_id',
 'all_user_id',
 'name',
 'email',
 'batch',
 'trainee_id',
 'category',
 'slug',
 'name.1',
 'awards_code',
 'awards_name',
 'awards_display',
 'awards_template',
 'awards_date',
 'awards_uuid',
 'awards_title',
 'awards_status',
 'awards_awarder',
 'awards_history_blob',
 'awards_history_user',
 'awards_history_status',
 'awards_history_timestamp',
 'awards_summary',
 'awards_verified_by',
 'awards_requested_by',
 'awards_description',
 'awards_profile_type',
 'basics_code',
 'basics_name',
 'basics_display',
 'basics_template',
 'basics_role',
 'basics_uuid',
 'basics_email',
 'basics_image',
 'basics_status',
 'basics_history_blob',
 'basics_history_user',
 'basics_history_status',
 'basics_history_timestamp',
 'basics_location_city',
 'basics_location_icon',
 'basics_location_region',
 'basics_location_address',
 'basics_location_country',
 'basics_location_postal_code',
 'basics_full_name',
 'basics_name_title',
 'basics_verified_by',
 'basics_requested_by',
 'basics_personal_statement',
 'basics_description',
 'basics_profile_type',
 'display',
 'projects_code',
 'projects_name',
 'projects_display',
 'projects_template',
 'projects_url',
 'projects_uuid',
 'projects_title',
 'projects_status',
 'projects_history_blob',
 'projects_history_user',
 'projects_history_status',
 'projects_history_timestamp',
 'projects_summary',
 'projects_end_date',
 'projects_focus_area',
 'projects_start_date',
 'projects_verified_by',
 'projects_requested_by',
 'projects_description',
 'projects_profile_type',
 'education_code',
 'education_name',
 'education_display',
 'education_template',
 'education_uuid',
 'education_score',
 'education_remark',
 'education_status',
 'education_country',
 'education_history_blob',
 'education_history_user',
 'education_history_status',
 'education_history_timestamp',
 'education_end_date',
 'education_start_date',
 'education_study_area',
 'education_study_type',
 'education_verified_by',
 'education_requested_by',
 'education_institution_url',
 'education_institution_name',
 'education_description',
 'education_profile_type',
 'interests_code',
 'interests_name',
 'interests_display',
 'interests_template',
 'interests_uuid',
 'interests_status',
 'interests_history_blob',
 'interests_history_user',
 'interests_history_status',
 'interests_history_timestamp',
 'interests_verified_by',
 'interests_requested_by',
 'interests_description',
 'interests_profile_type',
 'languages_code',
 'languages_name',
 'languages_display',
 'languages_template',
 'languages_uuid',
 'languages_status',
 'languages_fluency',
 'languages_history_blob',
 'languages_history_user',
 'languages_history_status',
 'languages_history_timestamp',
 'languages_language',
 'languages_verified_by',
 'languages_requested_by',
 'languages_description',
 'languages_profile_type',
 'volunteer_code',
 'volunteer_name',
 'volunteer_display',
 'volunteer_template',
 'volunteer_url',
 'volunteer_uuid',
 'volunteer_status',
 'volunteer_history_blob',
 'volunteer_history_user',
 'volunteer_history_status',
 'volunteer_history_timestamp',
 'volunteer_summary',
 'volunteer_end_date',
 'volunteer_position',
 'volunteer_start_date',
 'volunteer_verified_by',
 'volunteer_organization',
 'volunteer_requested_by',
 'volunteer_description',
 'volunteer_profile_type',
 'references_code',
 'references_name',
 'references_display',
 'references_template',
 'references_uuid',
 'references_status',
 'references_history_blob',
 'references_history_user',
 'references_history_status',
 'references_history_timestamp',
 'references_priority',
 'references_verified_by',
 'references_requested_by',
 'references_reference_text',
 'references_description',
 'references_profile_type',
 'description',
 'achievements_code',
 'achievements_name',
 'achievements_display',
 'achievements_template',
 'achievements_date',
 'achievements_uuid',
 'achievements_title',
 'achievements_status',
 'achievements_history_blob',
 'achievements_history_user',
 'achievements_history_status',
 'achievements_history_timestamp',
 'achievements_summary',
 'achievements_verified_by',
 'achievements_requested_by',
 'achievements_description',
 'achievements_profile_type',
 'certificates_code',
 'certificates_name',
 'certificates_display',
 'certificates_template',
 'certificates_url',
 'certificates_date',
 'certificates_uuid',
 'certificates_issuer',
 'certificates_status',
 'certificates_history_blob',
 'certificates_history_user',
 'certificates_history_status',
 'certificates_history_timestamp',
 'certificates_verified_by',
 'certificates_requested_by',
 'certificates_description',
 'certificates_profile_type',
 'competencies_code',
 'competencies_name',
 'competencies_display',
 'competencies_template',
 'competencies_uuid',
 'competencies_status',
 'competencies_history_blob',
 'competencies_history_user',
 'competencies_history_status',
 'competencies_history_timestamp',
 'competencies_evidence_source_link',
 'competencies_evidence_source_name',
 'competencies_evidence_status',
 'competencies_evidence_sentiment',
 'competencies_evidence_verified_by',
 'competencies_evidence_requested_by',
 'competencies_evidence_confidence_degree',
 'competencies_evidence_sfia_level_approved',
 'competencies_evidence_sfia_level_requested',
 'competencies_rationale',
 'competencies_sfia_level',
 'competencies_description',
 'competencies_verified_by',
 'competencies_requested_by',
 'competencies_experience_level',
 'competencies_sfia_estimation_method',
 'competencies_profile_type',
 'profile_type',
 'publications_code',
 'publications_name',
 'publications_display',
 'publications_template',
 'publications_url',
 'publications_uuid',
 'publications_status',
 'publications_history_blob',
 'publications_history_user',
 'publications_history_status',
 'publications_history_timestamp',
 'publications_summary',
 'publications_publisher',
 'publications_verified_by',
 'publications_release_date',
 'publications_requested_by',
 'publications_description',
 'publications_profile_type',
 'work_experience_code',
 'work_experience_name',
 'work_experience_display',
 'work_experience_template',
 'work_experience_role',
 'work_experience_uuid',
 'work_experience_status',
 'work_experience_company',
 'work_experience_history_blob',
 'work_experience_history_user',
 'work_experience_history_status',
 'work_experience_history_timestamp',
 'work_experience_summary',
 'work_experience_end_date',
 'work_experience_location',
 'work_experience_start_date',
 'work_experience_company_url',
 'work_experience_verified_by',
 'work_experience_requested_by',
 'work_experience_description',
 'work_experience_profile_type',
 'programing_languages_code',
 'programing_languages_name',
 'programing_languages_display',
 'programing_languages_template',
 'programing_languages_description',
 'programing_languages_profile_type',
 'tags',
 'title',
 'credibility',
 'summary',
 'created_at',
 'basics_media_icon',
 'basics_media_link',
 'basics_media_name',
 'basics_phone_icon',
 'basics_phone_name',
 'basics_phone_value',
 'references_contact_email',
 'references_contact_phone',
 'references_contact_remark',
 'references_contact_full_name',
 'references_contact_relationship',
 'competencies_evidence_remark',
 'competencies_evidence_message_role',
 'competencies_evidence_message_content',
 'competencies_evidence_message_timestamp',
 'competencies_evidence_sfia_dimensions_requested_name',
 'competencies_evidence_sfia_dimensions_requested_level',
 'competencies_evidence_sfia_dimensions_approved_name',
 'competencies_evidence_sfia_dimensions_approved_level']

In [27]:
df3.columns.tolist()
"user_profile_id"
"name"
"email"
"basics_location_address"
"basics_personal_statement"
"projects_code"
"projects_name"
"projects_display"
"projects_url"
"projects_history_timestamp"
"projects_summary"
"projects_end_date"
"education_code" 
"education_name"
"education_display"
"education_end_date"
"education_start_date"
"education_study_area"
"education_study_type"
"education_institution_name"
"languages_code"
"languages_display"
"languages_language"
"languages_fluency"
"achievements_code"
"achievements_display"
"certificates_code"
"certificates_name"
"certificates_display"
"certificates_url"
"certificates_issuer"
"work_experience_code"
"work_experience_display"
"work_experience_role"
"work_experience_company"
"work_experience_history_timestamp"
"work_experience_summary"
"work_experience_location"
"work_experience_start_date"
"work_experience_company_url"

'work_experience_company_url'

In [37]:

import pandas as pd

# Read the CSV file into a DataFrame
df3 = pd.read_csv('./dataset/user_profile_data.csv')

# List of columns to keep
columns_to_keep = [
"name",
"description",
"user_profile_id",
"basics.attributes",
"basics.description",
"projects.display",
"projects.attributes",
"projects.description",
"projects.profile_type",
"education.display",
"education.attributes",
"education.description",
"interests.display",
"interests.description",
"languages.display",
"languages.attributes",
"languages.description",
"volunteer.display",
"volunteer.description",
"references.display",
"references.description",
"achievements.display",
"achievements.description",
"certificates.display",
"certificates.attributes",
"certificates.description",
"competencies.display",
"competencies.attributes",
"publications.display",
"publications.description",
"publications.profile_type",
"work_experience.display",
"programing_languages.description",
"programing_languages.display",
"work_experience.attributes"
]

# Create a new DataFrame with only the specified columns
new_df = df3[columns_to_keep]
new_df.to_csv('./dataset/extract_user_profile_with_comptency.csv')
# Display the new DataFrame
print(new_df)

            name               description  user_profile_id  \
0   user_profile  User profile information               11
1   user_profile  User profile information               16
2   user_profile  User profile information                8
3   user_profile  User profile information               21
4   user_profile  User profile information                4
5   user_profile  User profile information               31
6   user_profile  User profile information               30
7   user_profile  User profile information                5
8   user_profile  User profile information               24
9   user_profile  User profile information               12
10  user_profile  User profile information                3
11  user_profile  User profile information                7
12  user_profile  User profile information               26
13  user_profile  User profile information               20
14  user_profile  User profile information               23
15  user_profile  User profile information               17
16  user_profile  User profile information               28
17  user_profile  User profile information                1
18  user_profile  User profile information                6
19  user_profile  User profile information               15
20  user_profile  User profile information                2
21  user_profile  User profile information               29
22  user_profile  User profile information               13
23  user_profile  User profile information               25
24  user_profile  User profile information               27
25  user_profile  User profile information               18
26  user_profile  User profile information               14
27  user_profile  User profile information               22
28  user_profile  User profile information               19

                                    basics.attributes  \
0   [{'role': 'Machine Learning Engineer|AI Engine...
1   [{'role': 'Generative AI Engineer | Software E...
2   [{'role': '', 'uuid': '90a30031-fa4d-4de1-a0ae...
3   [{'role': 'AI Engineer | Software Engineer | M...
4   [{'role': 'Generative AI | Software Engineerin...
5   [{'role': '10 Academy ', 'uuid': '9c7bcd69-f5c...
6   [{'role': '--Data Scientist||Data Engineering|...
7   [{'role': 'Generative AI Engineer | ML Enthusi...
8   [{'role': 'Generative AI Engineer | Machine Le...
9   [{'role': 'Generative AI Engineer | Machine Le...
10  [{'role': 'Data Engineer | Machine Learning | ...
11  [{'role': 'Data Engineer | Gen AI Engineer | U...
12  [{'role': 'Machine Learning Engineer|| Radio p...
13  [{'role': 'AI/ ML Engineer | Software Engineer...
14  [{'role': 'Generative AI & ML Engineer | CTO |...
15  [{'role': 'Data Engineer| ML Engineer', 'uuid'...
16  [{'role': 'Tensorflow Certified Developer | Ma...
17  [{'role': '', 'uuid': 'ef5db2a6-8114-440c-9052...
18  [{'role': 'Machine Learning Engineer | Generat...
19  [{'role': 'Geomatic Engineer | GIS Data Analys...
20  [{'role': 'Generative AI Engineer', 'uuid': '5...
21  [{'role': 'Generative AI Engineer | Machine le...
22  [{'role': 'Generative AI Engineer | Machine Le...
23  [{'role': 'Generative AI Engineer | Machine Le...
24  [{'role': 'Generative AI Engineer | Machine Le...
25  [{'role': 'Generative AI Engineer | Machine Le...
26  [{'role': 'Generative AI | ML Engineer', 'uuid...
27  [{'role': 'Generative Artificial Intelligence ...
28  [{'role': 'Generative AI | Data | Software Eng...

                  basics.description projects.display  \
0   Basic information about the user         Projects
1   Basic information about the user         Projects
2   Basic information about the user         Projects
3   Basic information about the user         Projects
4   Basic information about the user         Projects
5   Basic information about the user         Projects
6   Basic information about the user         Projects
7   Basic information about the user         Projects
8   Basic information about the user         Projects
9   Basic information about the user         Projects
10  Basic information about the user         Projects
11  Basic information about the user         Projects
12  Basic information about the user         Projects
13  Basic information about the user         Projects
14  Basic information about the user         Projects
15  Basic information about the user         Projects
16  Basic information about the user         Projects
17  Basic information about the user         Projects
18  Basic information about the user         Projects
19  Basic information about the user         Projects
20  Basic information about the user         Projects
21  Basic information about the user         Projects
22  Basic information about the user         Projects
23  Basic information about the user         Projects
24  Basic information about the user         Projects
25  Basic information about the user         Projects
26  Basic information about the user         Projects
27  Basic information about the user         Projects
28  Basic information about the user         Projects

                                  projects.attributes  \
0   [{'url': 'None', 'uuid': 'f0e10a16-f947-46a1-9...
1   [{'url': 'None', 'uuid': 'c4adfcce-acac-486b-b...
2                                                  []
3   [{'url': 'https://github.com/jadmassu/chatbot_...
4   [{'url': 'None', 'uuid': 'ed27398d-a1ee-46bd-b...
5   [{'url': 'http://cosmos.esa.int/web/planck', '...
6   [{'url': 'None', 'uuid': '52f6aeeb-d412-4369-a...
7   [{'url': 'None', 'uuid': 'e5687ca8-4f7f-44b5-8...
8   [{'url': 'None', 'uuid': '98f386be-9a22-4384-8...
9   [{'url': 'None', 'uuid': '8c85aeb6-f764-4a56-a...
10                                                 []
11  [{'url': 'None', 'uuid': '24ba7520-7213-46de-8...
12  [{'url': 'None', 'uuid': '02d2af9d-56af-4d21-b...
13  [{'url': 'None', 'uuid': 'cc444703-88c5-4c64-b...
14  [{'url': 'None', 'uuid': '112426f3-a383-41e4-9...
15                                                 []
16  [{'url': 'None', 'uuid': 'c402bf64-c8dc-4a94-9...
17                                                 []
18                                                 []
19  [{'url': 'None', 'uuid': '694fef5c-3276-4190-a...
20  [{'url': 'None', 'uuid': '5b961a4e-7f1e-4d13-9...
21  [{'url': 'None', 'uuid': 'f46879c8-53db-4ec8-a...
22  [{'url': 'None', 'uuid': 'cd2ff12a-89e5-4cf1-a...
23  [{'url': 'None', 'uuid': '33aca2d2-8b9d-48aa-8...
24  [{'url': 'None', 'uuid': 'bd7278a7-db94-4ab1-a...
25  [{'url': 'None', 'uuid': '713cc6c1-45de-4463-b...
26  [{'url': 'None', 'uuid': 'f1093510-bf23-42d8-a...
27  [{'url': 'None', 'uuid': '39c7c1ae-ee87-45ce-b...
28  [{'url': 'None', 'uuid': '7f97e410-60d9-4839-a...

               projects.description projects.profile_type education.display  \
0   Projects the user has worked on              projects         Education
1   Projects the user has worked on              projects         Education
2   Projects the user has worked on              projects         Education
3   Projects the user has worked on              projects         Education
4   Projects the user has worked on              projects         Education
5   Projects the user has worked on              projects         Education
6   Projects the user has worked on              projects         Education
7   Projects the user has worked on              projects         Education
8   Projects the user has worked on              projects         Education
9   Projects the user has worked on              projects         Education
10  Projects the user has worked on              projects         Education
11  Projects the user has worked on              projects         Education
12  Projects the user has worked on              projects         Education
13  Projects the user has worked on              projects         Education
14  Projects the user has worked on              projects         Education
15  Projects the user has worked on              projects         Education
16  Projects the user has worked on              projects         Education
17  Projects the user has worked on              projects         Education
18  Projects the user has worked on              projects         Education
19  Projects the user has worked on              projects         Education
20  Projects the user has worked on              projects         Education
21  Projects the user has worked on              projects         Education
22  Projects the user has worked on              projects         Education
23  Projects the user has worked on              projects         Education
24  Projects the user has worked on              projects         Education
25  Projects the user has worked on              projects         Education
26  Projects the user has worked on              projects         Education
27  Projects the user has worked on              projects         Education
28  Projects the user has worked on              projects         Education

    ...             certificates.description competencies.display  \
0   ...  Certificates and awards of the user         Competencies
1   ...  Certificates and awards of the user         Competencies
2   ...  Certificates and awards of the user         Competencies
3   ...  Certificates and awards of the user         Competencies
4   ...  Certificates and awards of the user         Competencies
5   ...  Certificates and awards of the user         Competencies
6   ...  Certificates and awards of the user         Competencies
7   ...  Certificates and awards of the user         Competencies
8   ...  Certificates and awards of the user         Competencies
9   ...  Certificates and awards of the user         Competencies
10  ...  Certificates and awards of the user         Competencies
11  ...  Certificates and awards of the user         Competencies
12  ...  Certificates and awards of the user         Competencies
13  ...  Certificates and awards of the user         Competencies
14  ...  Certificates and awards of the user         Competencies
15  ...  Certificates and awards of the user         Competencies
16  ...  Certificates and awards of the user         Competencies
17  ...  Certificates and awards of the user         Competencies
18  ...  Certificates and awards of the user         Competencies
19  ...  Certificates and awards of the user         Competencies
20  ...  Certificates and awards of the user         Competencies
21  ...  Certificates and awards of the user         Competencies
22  ...  Certificates and awards of the user         Competencies
23  ...  Certificates and awards of the user         Competencies
24  ...  Certificates and awards of the user         Competencies
25  ...  Certificates and awards of the user         Competencies
26  ...  Certificates and awards of the user         Competencies
27  ...  Certificates and awards of the user         Competencies
28  ...  Certificates and awards of the user         Competencies

                              competencies.attributes publications.display  \
0   [{'name': 'programming language', 'uuid': '4d6...         Publications
1   [{'name': 'programming language', 'uuid': '476...         Publications
2   [{'name': 'programming language', 'uuid': '475...         Publications
3   [{'name': 'programming language', 'uuid': 'dc7...         Publications
4   [{'name': 'programming language', 'uuid': 'bca...         Publications
5   [{'name': 'programming language', 'uuid': '78d...         Publications
6   [{'name': 'programming language', 'uuid': '54a...         Publications
7   [{'name': 'programming language', 'uuid': '3e8...         Publications
8   [{'name': 'programming language', 'uuid': 'c1d...         Publications
9   [{'name': 'programming language', 'uuid': '65a...         Publications
10  [{'name': 'programming language', 'uuid': '318...         Publications
11  [{'name': 'programming language', 'uuid': '314...         Publications
12  [{'name': 'programming language', 'uuid': '7a3...         Publications
13  [{'name': 'programming language', 'uuid': 'a67...         Publications
14  [{'name': 'programming language', 'uuid': 'c40...         Publications
15  [{'name': 'programming language', 'uuid': '5bc...         Publications
16  [{'name': 'programming language', 'uuid': 'e21...         Publications
17  [{'name': 'programming language', 'uuid': 'cdf...         Publications
18  [{'name': 'programming language', 'uuid': '90d...         Publications
19  [{'name': 'programming language', 'uuid': 'eb8...         Publications
20  [{'name': 'programming language', 'uuid': 'b8b...         Publications
21  [{'name': 'programming language', 'uuid': 'a97...         Publications
22  [{'name': 'programming language', 'uuid': '61c...         Publications
23  [{'name': 'programming language', 'uuid': '2a8...         Publications
24  [{'name': 'programming language', 'uuid': 'b12...         Publications
25  [{'name': 'programming language', 'uuid': '5f0...         Publications
26  [{'name': 'programming language', 'uuid': '209...         Publications
27  [{'name': 'programming language', 'uuid': '108...         Publications
28  [{'name': 'programming language', 'uuid': 'cd7...         Publications

    publications.description publications.profile_type  \
0   Publications of the user              publications
1   Publications of the user              publications
2   Publications of the user              publications
3   Publications of the user              publications
4   Publications of the user              publications
5   Publications of the user              publications
6   Publications of the user              publications
7   Publications of the user              publications
8   Publications of the user              publications
9   Publications of the user              publications
10  Publications of the user              publications
11  Publications of the user              publications
12  Publications of the user              publications
13  Publications of the user              publications
14  Publications of the user              publications
15  Publications of the user              publications
16  Publications of the user              publications
17  Publications of the user              publications
18  Publications of the user              publications
19  Publications of the user              publications
20  Publications of the user              publications
21  Publications of the user              publications
22  Publications of the user              publications
23  Publications of the user              publications
24  Publications of the user              publications
25  Publications of the user              publications
26  Publications of the user              publications
27  Publications of the user              publications
28  Publications of the user              publications

   work_experience.display                 programing_languages.description  \
0         Work Experiences  Programming languages the user is familiar with
1         Work Experiences  Programming languages the user is familiar with
2         Work Experiences  Programming languages the user is familiar with
3         Work Experiences  Programming languages the user is familiar with
4         Work Experiences  Programming languages the user is familiar with
5         Work Experiences  Programming languages the user is familiar with
6         Work Experiences  Programming languages the user is familiar with
7         Work Experiences  Programming languages the user is familiar with
8         Work Experiences  Programming languages the user is familiar with
9         Work Experiences  Programming languages the user is familiar with
10        Work Experiences  Programming languages the user is familiar with
11        Work Experiences  Programming languages the user is familiar with
12        Work Experiences  Programming languages the user is familiar with
13        Work Experiences  Programming languages the user is familiar with
14        Work Experiences  Programming languages the user is familiar with
15        Work Experiences  Programming languages the user is familiar with
16        Work Experiences  Programming languages the user is familiar with
17        Work Experiences  Programming languages the user is familiar with
18        Work Experiences  Programming languages the user is familiar with
19        Work Experiences  Programming languages the user is familiar with
20        Work Experiences  Programming languages the user is familiar with
21        Work Experiences  Programming languages the user is familiar with
22        Work Experiences  Programming languages the user is familiar with
23        Work Experiences  Programming languages the user is familiar with
24        Work Experiences  Programming languages the user is familiar with
25        Work Experiences  Programming languages the user is familiar with
26        Work Experiences  Programming languages the user is familiar with
27        Work Experiences  Programming languages the user is familiar with
28        Work Experiences  Programming languages the user is familiar with

   programing_languages.display  \
0         Programming Languages
1         Programming Languages
2         Programming Languages
3         Programming Languages
4         Programming Languages
5         Programming Languages
6         Programming Languages
7         Programming Languages
8         Programming Languages
9         Programming Languages
10        Programming Languages
11        Programming Languages
12        Programming Languages
13        Programming Languages
14        Programming Languages
15        Programming Languages
16        Programming Languages
17        Programming Languages
18        Programming Languages
19        Programming Languages
20        Programming Languages
21        Programming Languages
22        Programming Languages
23        Programming Languages
24        Programming Languages
25        Programming Languages
26        Programming Languages
27        Programming Languages
28        Programming Languages

                           work_experience.attributes
0   [{'role': 'Software Engineering Fellowship', '...
1   [{'role': 'Full-stack Developer', 'uuid': '323...
2                                                  []
3   [{'role': 'Data engineering, Machine learning ...
4   [{'role': 'Software Engineer', 'uuid': '04d46b...
5   [{'role': 'Scientific Director 2', 'uuid': '96...
6   [{'role': 'Data Engineering, Machine Learning ...
7   [{'role': 'Trainee', 'uuid': 'a6b84dd1-82ee-41...
8   [{'role': 'Trainee', 'uuid': 'a0a12547-8951-49...
9   [{'role': 'Data Engineering, Machine Learning ...
10  [{'role': 'Outreachy Intern', 'uuid': 'd1fc73f...
11  [{'role': ' Data Engineer, Generative AI, Mach...
12  [{'role': 'Machine Learning Engineering Traine...
13  [{'role': 'LLM Engineer(Contributor)', 'uuid':...
14  [{'role': 'DevOps Engineer', 'uuid': 'e2c7bb25...
15  [{'role': 'Assistant Researcher', 'uuid': '968...
16  [{'role': 'Machine Learning Engineer', 'uuid':...
17                                                 []
18  [{'role': 'Project Officer', 'uuid': '8e9fc101...
19  [{'role': 'Data Engineering, Machine Learning ...
20  [{'role': 'Web Developer', 'uuid': 'd5e2ccfa-d...
21  [{'role': 'Generative AI,ML and Data Engineer ...
22  [{'role': 'Generative AI, Machine Learning, Da...
23  [{'role': 'Trainee Generative AI Engineer | Ma...
24  [{'role': 'Machine Learning Engineer', 'uuid':...
25  [{'role': 'Data Engineering, Machine Learning ...
26  [{'role': 'Intelligent Systems Researcher', 'u...
27  [{'role': 'Data Engineering, Machine Learning ...
28  [{'role': 'Data Engineering, Machine Learning ...

[29 rows x 35 columns]

In [29]:
def dict_to_dataframe(data_dict):
    # Extract relevant fields
    job_profile_id = data_dict.get('job_profile_id', None)
    required_qualifications = data_dict.get('attributes', {}).get('required_qualifications', [])
    duties_responsibilities = data_dict.get('attributes', {}).get('duties_responsibilities', [])
    purpose = data_dict.get('attributes', {}).get('purpose', '')
    role = data_dict.get('attributes', {}).get('role', '')

    # Extract competencies
    competencies_list = []
    competencies = data_dict.get('attributes', {}).get('competencies', [])
    for competency in competencies:
        competencies_list.append({
            'name': competency.get('name', ''),
            'skills': competency.get('skills', []),
            'sfia_level': competency.get('sfia_level', ''),
            'summary': competency.get('summary', '')
        })

    # Create DataFrame with extracted fields
    df = pd.DataFrame([{
        'job_profile_id': job_profile_id,
        'required_qualifications': required_qualifications,
        'duties_responsibilities': duties_responsibilities,
        'purpose': purpose,
        'role': role,
        'competencies': competencies_list
    }])
    
    return df

In [30]:
import os
def process_json_files_in_folder(folder_path):
    all_dfs = []  # To store DataFrames from all JSON files

    # Iterate through each file in the folder
    for filename in os.listdir(folder_path):
        if filename.endswith('.json'):  # Only process JSON files
            file_path = os.path.join(folder_path, filename)

            # Read the JSON file
            with open(file_path, 'r') as file:
                data_dict = json.load(file)
            
            # Convert JSON to DataFrame and append to the list
            df = dict_to_dataframe(data_dict)
            all_dfs.append(df)

    # Combine all DataFrames into one
    final_df = pd.concat(all_dfs, ignore_index=True)
    
    return final_df

In [57]:
folder_path = './dataset/job_data'
final_df = process_json_files_in_folder(folder_path)

# Save the combined DataFrame to a CSV or display
final_df.to_csv('./dataset/combined_job_data.csv', index=False)

In [58]:
df = pd.read_csv("./dataset/combined_job_data.csv")
df.head()

,job_profile_id,required_qualifications,duties_responsibilities,purpose,role,competencies
0,1113,['Strong proficiency in Python and its data sc...,"['Collect, clean, and preprocess data from var...",To extract insights and knowledge from large a...,"Data Scientist (Python, Machine Learning)","[{'name': 'Programming Languages', 'skills': [..."
1,1087,"['Some software engineering experience.', 'Deg...",['Contribute to the AI Automation Platform for...,The role aims to develop and maintain scalable...,"(Senior) Backend Developer (Python, ML, Cloud)...","[{'name': 'Programming Languages', 'skills': [..."
2,1050,Advanced generative AI proficiency with the us...,Create and improve autonomous support platform...,Harness the power of GenAI to redefine busines...,"Machine Learning Engineer, IgniteTech (Remote)...","[{'name': 'Generative AI', 'skills': ['Advance..."
3,1030,['Experience with Python for prototyping algor...,['Consulting with R&D team to determine and re...,To design and optimize state-of-the-art comput...,Computer Vision Engineer,"[{'name': 'Programming Languages', 'skills': [..."
4,1032,['Fluency in English with the ability to artic...,['Assess the quality of AI-generated code and ...,Shape the future of AI by leveraging subject-m...,"Software Engineer - AI Training (Freelance, Re...","[{'name': 'Programming Languages', 'skills': [..."

In [65]:
df_match = pd.read_csv("./dataset/job_match.csv")
df_match.head()

,Unnamed: 0,user_job_match_id,job_profile_id,user_profile_id,category,slug,tags,match_score,match_level,match_summary,...,match_attributes_match_detail_ujc_similarity_score,match_attributes_match_detail_best_matched_user_competency,match_attributes_match_algorithm,match_attributes_overall_match_score,match_attributes_overall_match_degree,createdAt,match_attributes_applyLink,feedback_attributes_reaction_attributes_comment,feedback_attributes_reaction_attributes_section,feedback_attributes_reaction_attributes_user_reaction
0,0,1558,1035,197,openai_chatgpt_match,"job_profile_id:1035, user_profile_id:197, vers...",NaN,95.0,very_high,Overall match score is the average of all matc...,...,0.90,communication,vector_matching,95,very high,2024-09-19T11:30:30.003Z,NaN,NaN,NaN,NaN
1,1,1557,1041,197,openai_chatgpt_match,"job_profile_id:1041, user_profile_id:197, vers...",NaN,94.0,very_high,Overall match score is the average of all matc...,...,0.91,bi analytics,vector_matching,94,very high,2024-09-19T11:30:27.012Z,NaN,NaN,NaN,NaN
2,2,1556,1082,197,openai_chatgpt_match,"job_profile_id:1082, user_profile_id:197, vers...",NaN,86.0,high,Overall match score is the average of all matc...,...,0.74,data engineering,vector_matching,86,high,2024-09-19T11:30:23.764Z,NaN,NaN,NaN,NaN
3,3,1555,1086,197,openai_chatgpt_match,"job_profile_id:1086, user_profile_id:197, vers...",NaN,96.0,very_high,Overall match score is the average of all matc...,...,0.85,backend development,vector_matching,96,very high,2024-09-19T11:30:21.097Z,NaN,NaN,NaN,NaN
4,4,1554,1003,197,openai_chatgpt_match,"job_profile_id:1003, user_profile_id:197, vers...",NaN,97.0,very_high,Overall match score is the average of all matc...,...,0.95,collaboration,vector_matching,97,very high,2024-09-19T11:30:18.135Z,NaN,NaN,NaN,NaN

In [66]:
df_merge = df.merge(df_match, how="inner", on="job_profile_id")

In [67]:
df_merge.head()

,job_profile_id,required_qualifications,duties_responsibilities,purpose,role,competencies,Unnamed: 0,user_job_match_id,user_profile_id,category,...,match_attributes_match_detail_ujc_similarity_score,match_attributes_match_detail_best_matched_user_competency,match_attributes_match_algorithm,match_attributes_overall_match_score,match_attributes_overall_match_degree,createdAt,match_attributes_applyLink,feedback_attributes_reaction_attributes_comment,feedback_attributes_reaction_attributes_section,feedback_attributes_reaction_attributes_user_reaction
0,1040,"Proficient in designing, developing, and evalu...","Utilize NLP techniques to preprocess, analyze,...",To provide early career talent with an immersi...,Data Scientist (NLP),"[{'name': 'Data Analysis', 'skills': ['data mo...",29,1529,197,openai_chatgpt_match,...,0.98,programming language,vector_matching,99,very high,2024-09-18T06:19:55.634Z,NaN,NaN,NaN,NaN
1,1086,['Enrollment in 3rd or 4th year of a Software ...,['Writing production code and deploying new fe...,Offer an engaging and practical co-op experien...,Software Developer Co-op,"[{'name': 'Programming Languages', 'skills': [...",3,1555,197,openai_chatgpt_match,...,0.85,backend development,vector_matching,96,very high,2024-09-19T11:30:21.097Z,NaN,NaN,NaN,NaN
2,1041,"['BSc degree in Computer Science, Mathematics,...","['Lead technical projects, allocate effort, pl...","Lead technical projects, define technical spec...",R&amp;D - AI Engineer (Mid) / Horizon Project ...,"[{'name': 'Technical Project Management', 'ski...",1,1557,197,openai_chatgpt_match,...,0.91,bi analytics,vector_matching,94,very high,2024-09-19T11:30:27.012Z,NaN,NaN,NaN,NaN
3,1045,"Bachelor's degree in STEM (Computer Science, M...","Conduct R&D in computer vision, image processi...","To conduct R&D in computer vision, image proce...",Ml research engineer (remote),"[{'name': 'Machine Learning', 'skills': ['deep...",6,1552,197,openai_chatgpt_match,...,0.90,communication,vector_matching,92,very high,2024-09-19T11:30:15.088Z,NaN,NaN,NaN,NaN
4,1058,"[""Bachelor's or equivalent in Computer Science...","['Build robust, scalable, leading-edge contain...",To develop tools and technology for building a...,Software Engineer - Python - Container Images,"[{'name': 'Container Management', 'skills': ['...",14,1544,197,openai_chatgpt_match,...,0.90,communication,vector_matching,83,high,2024-09-19T11:30:01.631Z,NaN,NaN,NaN,NaN

In [68]:
df_merge['user_profile_id'].unique()

array([197])

In [51]:
matched = df_merge[["job_profile_id", "user_profile_id", "match_attributes_overall_match_score", "match_attributes_overall_match_degree"]]

In [53]:
matched.head()

,job_profile_id,user_profile_id,match_attributes_overall_match_score,match_attributes_overall_match_degree
0,1040,197,99,very high
1,1086,197,96,very high
2,1041,197,94,very high
3,1045,197,92,very high
4,1058,197,83,high
5,1068,197,93,very high
6,1060,197,94,very high
7,1028,197,93,very high
8,1082,197,86,high
9,1035,197,95,very high
10,1062,197,86,high
11,1080,197,91,very high

In [50]:
filtered_df = matched[matched['match_attributes_overall_match_degree'].isin(["very high", "high"])]
filtered_df

,job_profile_id,user_profile_id,match_attributes_overall_match_score,match_attributes_overall_match_degree
0,1040,197,99,very high
1,1086,197,96,very high
2,1041,197,94,very high
3,1045,197,92,very high
4,1058,197,83,high
5,1068,197,93,very high
6,1060,197,94,very high
7,1028,197,93,very high
8,1082,197,86,high
9,1035,197,95,very high
10,1062,197,86,high
11,1080,197,91,very high

In [79]:
# filtered_df.to_csv("./dataset/final/job_match.csv")
job_match = pd.read_csv("./dataset/final/job_match.csv")
job_match['user_profile_id'].unique()

array([23, 16, 13, 29, 25])

In [69]:
import pandas as pd
import os
import json

# Specify the folder containing JSON files
folder_path = './dataset/job_data/'

# Create an empty list to hold DataFrames
dataframes = []

# Loop through all files in the directory
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        
        # Read the JSON file
        with open(file_path, 'r') as file:
            data = json.load(file)
            df = pd.json_normalize(data)  # Converts JSON to DataFrame
            dataframes.append(df)

# Concatenate all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a CSV file
combined_df.to_csv('./dataset/job_json_combine_data.csv', index=False)

print("CSV file has been created successfully!")

CSV file has been created successfully!

In [31]:
dff = pd.read_csv('./dataset/combined_job_data.csv')
dff

,job_profile_id,required_qualifications,duties_responsibilities,purpose,role,competencies
0,1113,['Strong proficiency in Python and its data sc...,"['Collect, clean, and preprocess data from var...",To extract insights and knowledge from large a...,"Data Scientist (Python, Machine Learning)","[{'name': 'Programming Languages', 'skills': [..."
1,1087,"['Some software engineering experience.', 'Deg...",['Contribute to the AI Automation Platform for...,The role aims to develop and maintain scalable...,"(Senior) Backend Developer (Python, ML, Cloud)...","[{'name': 'Programming Languages', 'skills': [..."
2,1050,Advanced generative AI proficiency with the us...,Create and improve autonomous support platform...,Harness the power of GenAI to redefine busines...,"Machine Learning Engineer, IgniteTech (Remote)...","[{'name': 'Generative AI', 'skills': ['Advance..."
3,1030,['Experience with Python for prototyping algor...,['Consulting with R&D team to determine and re...,To design and optimize state-of-the-art comput...,Computer Vision Engineer,"[{'name': 'Programming Languages', 'skills': [..."
4,1032,['Fluency in English with the ability to artic...,['Assess the quality of AI-generated code and ...,Shape the future of AI by leveraging subject-m...,"Software Engineer - AI Training (Freelance, Re...","[{'name': 'Programming Languages', 'skills': [..."
...,...,...,...,...,...,...
95,1049,"['Advanced generative AI proficiency (i.e., us...",['Designing and building high-quality AI autom...,To design and build high-quality AI automation...,"Machine Learning Engineer, Trilogy (Remote) - ...","[{'name': 'Generative AI', 'skills': ['AI tool..."
96,1034,"['A degree in Computer Science, Machine Learni...",['Collaborate with cross-functional teams to d...,To develop and deploy Conversational AI applic...,Machine Learning Engineer - Conversational AI ...,"[{'name': 'Machine Learning', 'skills': ['Deve..."
97,1033,"['2+ years of professional experience in AI, D...",['Deliver comprehensive training programs cove...,"To deliver engaging, practical, and cutting-ed...",Artificial Intelligence (AI) Trainer,"[{'name': 'Data Science', 'skills': ['data_ana..."
98,1064,"['knowledge of Python and JavaScript', 'experi...",Maintenance and further development of the com...,To maintain and further develop the company’s ...,Python fullstack developer,"[{'name': 'Programming Languages', 'skills': [..."
99,1112,"• Bachelor's degree in Computer Science, Infor...",• Work with the IT Data Engineering Team and a...,To support the IT organization's data strategy...,IT Data Engineer,"[{'name': 'Data Engineering', 'skills': ['data..."

In [81]:
filter_job_match = pd.read_csv('./dataset/final/job_match.csv')
json_data = filter_job_match.to_json(orient='records', lines=True)

with open('./dataset/final/job_match.json', 'w') as json_file:
    json_file.write(json_data)

In [32]:
job_profile_ids = [1040, 1086, 1041, 1045, 1058, 1068, 1060, 1028, 1082, 1035, 1062,1080]

filtered_job_profiles = dff[dff['job_profile_id'].isin(job_profile_ids)]

len(filtered_job_profiles)

json_data = filtered_job_profiles.to_json(orient='records', lines=True)

with open('./dataset/final/job_profiles.json', 'w') as json_file:
    json_file.write(json_data)

In [74]:
folder_path = './dataset/trainees_profile_latest/'

# Create an empty list to hold DataFrames
dataframes = []

# Loop through all files in the directory
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        
        # Read the JSON file
        with open(file_path, 'r') as file:
            data = json.load(file)
            df = pd.json_normalize(data)  # Converts JSON to DataFrame
            dataframes.append(df)

# Concatenate all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a CSV file
combined_df.to_csv('./dataset/user_profile_data.csv', index=False)

print("CSV file has been created successfully!")

CSV file has been created successfully!

In [38]:
dff_user = pd.read_csv('./dataset/extract_user_profile_with_comptency.csv', index_col=0)
dff_user.columns

Index(['name', 'description', 'user_profile_id', 'basics.attributes',
       'basics.description', 'projects.display', 'projects.attributes',
       'projects.description', 'projects.profile_type', 'education.display',
       'education.attributes', 'education.description', 'interests.display',
       'interests.description', 'languages.display', 'languages.attributes',
       'languages.description', 'volunteer.display', 'volunteer.description',
       'references.display', 'references.description', 'achievements.display',
       'achievements.description', 'certificates.display',
       'certificates.attributes', 'certificates.description',
       'competencies.display', 'competencies.attributes',
       'publications.display', 'publications.description',
       'publications.profile_type', 'work_experience.display',
       'programing_languages.description', 'programing_languages.display',
       'work_experience.attributes'],
      dtype='object')

In [39]:
user_profile_ids = [23, 16, 13, 29, 25]

filtered_user_profiles = dff_user[dff_user['user_profile_id'].isin(user_profile_ids)]

len(filtered_user_profiles)
json_data = filtered_user_profiles.to_json(orient='records', lines=True)

with open('./dataset/final/user_profiles_with_comptency.json', 'w') as json_file:
    json_file.write(json_data)

In [87]:
import ast, json
projects =  "[{'url': 'None', 'uuid': 'c4adfcce-acac-486b-b4d4-07955fb16e0f', 'title': 'Automated Storyboard Synthesis for Digital Advertising', 'tools': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-05T02:25:36.083421'}], 'summary': 'Developed a machine learning solution to automate the conversion of textual advertisement concepts into detailed visual storyboards. Utilized advanced deep learning frameworks, image segmentation, and LLM-based agents for asset analysis, generation, and composition, streamlining the ad creation process for digital advertising campaigns.', 'end_date': '', 'focus_area': '', 'highlights': [], 'start_date': '', 'verified_by': '', 'requested_by': ''}, {'url': 'None', 'uuid': 'd80ab376-13a6-47b2-bebf-7cb6e031e3e2', 'title': 'LLM Finetuning: Enabling Quality Embedding and Text Generation for Amharic Language', 'tools': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-05T02:25:36.083479'}], 'summary': 'Enhanced NLP for Amharic by fine-tuning LLaMA-2. Key steps included implementing model quantization, preprocessing data and finetuning the model. Initial results showed promise in text generation and question answering. Future improvements will focus on  enhancing the fine-tuning process for better performance.', 'end_date': '', 'focus_area': '', 'highlights': [], 'start_date': '', 'verified_by': '', 'requested_by': ''}, {'url': 'None', 'uuid': 'e8033426-399d-4a61-84d8-20c2074cc1dd', 'title': 'Precision RAG: Prompt Tuning For Building Enterprise Grade RAG Systems', 'tools': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-05T02:25:36.083529'}], 'summary': \"The Prompt Generation System is an automated tool designed to assist users in generating multiple prompt options based on their input descriptions of tasks, objectives, and scenarios. The system employs sophisticated algorithms and evaluation metrics to ensure that the generated prompts align with the user's requirements.\", 'end_date': '', 'focus_area': '', 'highlights': [], 'start_date': '', 'verified_by': '', 'requested_by': ''}]"

In [85]:
new = ast.literal_eval(projects)
type(new)

list

In [91]:
# Convert the list to JSON
json_output = json.dumps(new, indent=4)

# Print the JSON output
print(json_output)

# Optionally, save to a JSON file
with open('output.json', 'w') as json_file:
    json_file.write(json_output)

[
    {
        "url": "None",
        "uuid": "c4adfcce-acac-486b-b4d4-07955fb16e0f",
        "title": "Automated Storyboard Synthesis for Digital Advertising",
        "tools": [],
        "status": "approved",
        "history": [
            {
                "blob": "",
                "user": "2151",
                "status": "approved",
                "timestamp": "2024-08-05T02:25:36.083421"
            }
        ],
        "summary": "Developed a machine learning solution to automate the conversion of textual advertisement concepts into detailed visual storyboards. Utilized advanced deep learning frameworks, image segmentation, and LLM-based agents for asset analysis, generation, and composition, streamlining the ad creation process for digital advertising campaigns.",
        "end_date": "",
        "focus_area": "",
        "highlights": [],
        "start_date": "",
        "verified_by": "",
        "requested_by": ""
    },
    {
        "url": "None",
        "uuid": "d80ab376-13a6-47b2-bebf-7cb6e031e3e2",
        "title": "LLM Finetuning: Enabling Quality Embedding and Text Generation for Amharic Language",
        "tools": [],
        "status": "approved",
        "history": [
            {
                "blob": "",
                "user": "2151",
                "status": "approved",
                "timestamp": "2024-08-05T02:25:36.083479"
            }
        ],
        "summary": "Enhanced NLP for Amharic by fine-tuning LLaMA-2. Key steps included implementing model quantization, preprocessing data and finetuning the model. Initial results showed promise in text generation and question answering. Future improvements will focus on  enhancing the fine-tuning process for better performance.",
        "end_date": "",
        "focus_area": "",
        "highlights": [],
        "start_date": "",
        "verified_by": "",
        "requested_by": ""
    },
    {
        "url": "None",
        "uuid": "e8033426-399d-4a61-84d8-20c2074cc1dd",
        "title": "Precision RAG: Prompt Tuning For Building Enterprise Grade RAG Systems",
        "tools": [],
        "status": "approved",
        "history": [
            {
                "blob": "",
                "user": "2151",
                "status": "approved",
                "timestamp": "2024-08-05T02:25:36.083529"
            }
        ],
        "summary": "The Prompt Generation System is an automated tool designed to assist users in generating multiple prompt options based on their input descriptions of tasks, objectives, and scenarios. The system employs sophisticated algorithms and evaluation metrics to ensure that the generated prompts align with the user's requirements.",
        "end_date": "",
        "focus_area": "",
        "highlights": [],
        "start_date": "",
        "verified_by": "",
        "requested_by": ""
    }
]

In [ ]:
# Loop through each item in the data list
for item in data:
    for key in item:
        # Convert the string representation of the list of dictionaries to actual list
        try:
            attributes_list = ast.literal_eval(item[key])
            # Convert the list of dictionaries to JSON
            attributes_json = json.dumps(attributes_list)
            item[key] = attributes_json  # Update the item with JSON representation
        except Exception as e:
            print(f"Error processing {key}: {e}")

# Print the updated data
print(json.dumps(data, indent=2))

In [6]:
import os
def file_reader(path: str) -> str:
    try:
       
        fname = os.path.join(path)
        with open(fname, 'r') as f:
            system_message = f.read()
        return system_message
    
    except Exception as e:
        return f'Error: {str(e)}'
    
# jbPath = '\n'.join(str(item) for item in data['user']['jbPath'])
# cvPath = '\n'.join(str(item) for item in profile)
# cvPath

In [6]:
profile_txt = """
    You are an experienced HR analyst, here is the documents you need to do the analysis
    - The JD(job description) in JSON format: {jd} 
    - The CV(curriculum vitae) in JSON format: {cv}

You job is to analyse the CV and the JD, and provide your analysis. 
"""

In [15]:
import json
jbPath=str(profile)
cvPath="json.loads(recieved.cvPath)"

context = str(profile_txt)
msg = context\
        .replace("{jd}", jbPath)\
        .replace("{cv}", cvPath)

In [16]:
print("#######jbPath#######")
msg

#######jbPath#######

'\n    You are an experienced HR analyst, here is the documents you need to do the analysis\n    - The JD(job description) in JSON format: {\'name\': \'Abraham Teka\', \'display\': \'User Profile\', \'description\': \'User profile information\', \'profile_type\': \'user_profile\', \'user_profile_id\': 16, \'awards.code\': \'awards\', \'awards.name\': \'awards\', \'awards.display\': \'Awards\', \'awards.template\': \'form\', \'awards.attributes\': [], \'awards.description\': \'Awards received by the user\', \'awards.profile_type\': \'awards\', \'basics.code\': \'basics\', \'basics.name\': \'basics\', \'basics.display\': \'Basics\', \'basics.template\': \'form\', \'basics.attributes\': \'[{\\\'role\\\': \\\'Generative AI Engineer | Software Engineer | Machine Learning | Cloud Solutions (Azure, AWS) | Advocate for Continuous Improvement\\\', \\\'uuid\\\': \\\'e0eab10e-67ca-47c1-b89d-cd38f78037bc\\\', \\\'email\\\': \\\'aberhamyirsaw@gmail.com\\\', \\\'image\\\': \\\'\\\', \\\'media\\\': [], \\\'phone\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-15T05:55:43.666429\\\'}], \\\'location\\\': {\\\'city\\\': \\\'\\\', \\\'icon\\\': \\\'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain\\\', \\\'region\\\': \\\'\\\', \\\'address\\\': \\\'Ethiopia\\\', \\\'country\\\': \\\'US\\\', \\\'postal_code\\\': \\\'\\\'}, \\\'full_name\\\': \\\'Abraham Teka\\\', \\\'name_title\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\', \\\'personal_statement\\\': "Abraham Teka here, ambitious about advancing software solutions through Generative AI and cloud computing. With certifications in Azure and AWS, I specialize in RAG systems, prompt engineering, and LLM fine-tuning. I aim to innovate and drive technological advancements in AI and software engineering. Let\\\'s connect and build intelligent solutions that make technology beneficial to everyone!"}]\', \'basics.description\': \'Basic information about the user\', \'basics.profile_type\': \'basics\', \'projects.code\': \'projects\', \'projects.name\': \'projects\', \'projects.display\': \'Projects\', \'projects.template\': \'form\', \'projects.attributes\': \'[{\\\'url\\\': \\\'None\\\', \\\'uuid\\\': \\\'c4adfcce-acac-486b-b4d4-07955fb16e0f\\\', \\\'title\\\': \\\'Automated Storyboard Synthesis for Digital Advertising\\\', \\\'tools\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083421\\\'}], \\\'summary\\\': \\\'Developed a machine learning solution to automate the conversion of textual advertisement concepts into detailed visual storyboards. Utilized advanced deep learning frameworks, image segmentation, and LLM-based agents for asset analysis, generation, and composition, streamlining the ad creation process for digital advertising campaigns.\\\', \\\'end_date\\\': \\\'\\\', \\\'focus_area\\\': \\\'\\\', \\\'highlights\\\': [], \\\'start_date\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\'}, {\\\'url\\\': \\\'None\\\', \\\'uuid\\\': \\\'d80ab376-13a6-47b2-bebf-7cb6e031e3e2\\\', \\\'title\\\': \\\'LLM Finetuning: Enabling Quality Embedding and Text Generation for Amharic Language\\\', \\\'tools\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083479\\\'}], \\\'summary\\\': \\\'Enhanced NLP for Amharic by fine-tuning LLaMA-2. Key steps included implementing model quantization, preprocessing data and finetuning the model. Initial results showed promise in text generation and question answering. Future improvements will focus on  enhancing the fine-tuning process for better performance.\\\', \\\'end_date\\\': \\\'\\\', \\\'focus_area\\\': \\\'\\\', \\\'highlights\\\': [], \\\'start_date\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\'}, {\\\'url\\\': \\\'None\\\', \\\'uuid\\\': \\\'e8033426-399d-4a61-84d8-20c2074cc1dd\\\', \\\'title\\\': \\\'Precision RAG: Prompt Tuning For Building Enterprise Grade RAG Systems\\\', \\\'tools\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083529\\\'}], \\\'summary\\\': "The Prompt Generation System is an automated tool designed to assist users in generating multiple prompt options based on their input descriptions of tasks, objectives, and scenarios. The system employs sophisticated algorithms and evaluation metrics to ensure that the generated prompts align with the user\\\'s requirements.", \\\'end_date\\\': \\\'\\\', \\\'focus_area\\\': \\\'\\\', \\\'highlights\\\': [], \\\'start_date\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\'}]\', \'projects.description\': \'Projects the user has worked on\', \'projects.profile_type\': \'projects\', \'education.code\': \'education\', \'education.name\': \'education\', \'education.display\': \'Education\', \'education.template\': \'form\', \'education.attributes\': \'[{\\\'uuid\\\': \\\'a7537ae7-18ae-4fd4-b253-0204a681e437\\\', \\\'score\\\': \\\'\\\', \\\'remark\\\': \\\'\\\', \\\'status\\\': \\\'approved\\\', \\\'country\\\': \\\'\\\', \\\'courses\\\': [], \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083597\\\'}], \\\'end_date\\\': \\\'2024-07-31\\\', \\\'start_date\\\': \\\'2024-04-30\\\', \\\'study_area\\\': \\\'\\\', \\\'study_type\\\': \\\'Generative AI, Data Engineering & Machine Learning\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\', \\\'institution_url\\\': \\\'\\\', \\\'institution_name\\\': \\\'10 Academy\\\'}, {\\\'uuid\\\': \\\'f58152c2-32a3-40f4-bd15-038a65cf0931\\\', \\\'score\\\': \\\'3.4\\\', \\\'remark\\\': \\\'\\\', \\\'status\\\': \\\'approved\\\', \\\'country\\\': \\\'\\\', \\\'courses\\\': [], \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083649\\\'}], \\\'end_date\\\': \\\'2022-06-30\\\', \\\'start_date\\\': \\\'2017-09-30\\\', \\\'study_area\\\': \\\'Software Engineering\\\', \\\'study_type\\\': "Bachelor\\\'s degree", \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\', \\\'institution_url\\\': \\\'\\\', \\\'institution_name\\\': \\\'Bahir Dar University\\\'}]\', \'education.description\': \'Educational background of the user\', \'education.profile_type\': \'education\', \'interests.code\': \'interests\', \'interests.name\': \'interests\', \'interests.display\': \'Interests\', \'interests.template\': \'form\', \'interests.attributes\': [], \'interests.description\': \'Interests of the user\', \'interests.profile_type\': \'interests\', \'languages.code\': \'languages\', \'languages.name\': \'languages\', \'languages.display\': \'Languages\', \'languages.template\': \'form\', \'languages.attributes\': "[{\'uuid\': \'7a659bec-40a5-483c-8d93-ae75561bfc7a\', \'status\': \'approved\', \'fluency\': \'Native Speaker\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083689\'}], \'language\': \'English\', \'verified_by\': \'\', \'requested_by\': \'\'}]", \'languages.description\': \'Languages spoken by the user\', \'languages.profile_type\': \'languages\', \'volunteer.code\': \'volunteer\', \'volunteer.name\': \'volunteer\', \'volunteer.display\': \'Volunteer Work\', \'volunteer.template\': \'form\', \'volunteer.attributes\': [], \'volunteer.description\': \'Volunteer work of the user\', \'volunteer.profile_type\': \'volunteer\', \'references.code\': \'references\', \'references.name\': \'references\', \'references.display\': \'References\', \'references.template\': \'form\', \'references.attributes\': [], \'references.description\': \'References of the user\', \'references.profile_type\': \'references\', \'achievements.code\': \'achievements\', \'achievements.name\': \'achievements\', \'achievements.display\': \'Achievements\', \'achievements.template\': \'form\', \'achievements.attributes\': [], \'achievements.description\': \'Achievements of the user\', \'achievements.profile_type\': \'achievements\', \'certificates.code\': \'certificates\', \'certificates.name\': \'certificates\', \'certificates.display\': \'Certificates\', \'certificates.template\': \'form\', \'certificates.attributes\': "[{\'url\': \'https://learn.microsoft.com/api/credentials/share/en-us/AbrahamYT-4943/E0A02D871CD533ED?sharingId=7A7DE93C2D817883\', \'date\': \'\', \'name\': \'Microsoft Certified: Azure Fundamentals\', \'uuid\': \'3961d92e-bfaa-425b-9d75-5bae2da0296b\', \'issuer\': \'Microsoft\', \'status\': \'approved\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083735\'}], \'verified_by\': \'\', \'requested_by\': \'\'}, {\'url\': \'https://www.credly.com/badges/2e03cc29-77eb-4537-9938-e41abd474da5/public_url\', \'date\': \'\', \'name\': \'Amazon Web Services Cloud Practitioner\', \'uuid\': \'428a1f5b-8c3c-443d-b4bf-fb8aab8f81d7\', \'issuer\': \'Amazon Web Services (AWS)\', \'status\': \'approved\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083770\'}], \'verified_by\': \'\', \'requested_by\': \'\'}]", \'certificates.description\': \'Certificates and awards of the user\', \'certificates.profile_type\': \'certificates\', \'competencies.code\': \'competencies\', \'competencies.name\': \'competencies\', \'competencies.display\': \'Competencies\', \'competencies.template\': \'form\', \'competencies.attributes\': "[{\'name\': \'programming language\', \'uuid\': \'4760cbf8-1cb4-4164-ab94-6e2ecc7ef74e\', \'others\': [], \'skills\': [\'python\', \'javaScript\', \'django\'], \'status\': \'approved\', \'display\': \'Programming Language\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083990\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \'positive\', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \'high\', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has sound generic, domain, and specialist knowledge necessary for effective performance, typically gained from recognized bodies of knowledge and organizational information. Understands and effectively applies appropriate methods, tools, applications, and processes. Demonstrates judgment and a systematic approach to work, applies a methodical approach to routine and moderately complex issue definition and resolution, may oversee others or make decisions impacting routine work assigned to individuals or project stages, and works under general direction with specific guidance and milestone reviews.\', \'sfia_level\': \'3\', \'description\': \'A programming language is a way for programmers (developers) to communicate with computers. Programming languages consist of a set of rules that allows string values to be converted into various ways of generating machine code, or, in the case of visual programming languages, graphical elements.\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'data engineering\', \'uuid\': \'b1e2cf8f-5d7a-4b9e-ac18-60ecf6e484fe\', \'others\': [], \'skills\': [\'airflow\', \'aws\', \'big data\', \'dbt\', \'kafka\', \'mysql\', \'postgres\', \'sql\'], \'status\': \'approved\', \'display\': \'Data Engineering\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084207\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \'positive\', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \'high\', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \'positive\', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \'high\', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has gained basic domain knowledge and demonstrates application of essential generic knowledge typically found in industry bodies of knowledge. Absorbs new information when presented systematically and applies it effectively. Understands and uses appropriate methods, tools, applications, and processes. Shows a rational and organized approach to work, performs a range of activities in varied environments, interacts with and may influence immediate colleagues, and uses limited discretion in resolving issues or inquiries.\', \'sfia_level\': \'2\', \'description\': \'Data engineering is the process of designing and building systems that let people collect and analyze raw data from multiple sources and formats.\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'analytics engineering\', \'uuid\': \'bcff8234-3954-41db-88e7-34fe5bb0b11e\', \'others\': [], \'skills\': [\'airflow\', \'aws\', \'dbt\', \'kafka\', \'postgres\', \'sql\'], \'status\': \'approved\', \'display\': \'Analytics Engineering\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084414\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has gained basic domain knowledge and demonstrates application of essential generic knowledge typically found in industry bodies of knowledge. Absorbs new information when presented systematically and applies it effectively. Understands and uses appropriate methods, tools, applications, and processes. Shows a rational and organized approach to work, performs a range of activities in varied environments, interacts with and may influence immediate colleagues, and uses limited discretion in resolving issues or inquiries.\', \'sfia_level\': \'2\', \'description\': \'Analytics engineering is a discipline that focuses on designing, constructing, and maintaining data infrastructure and data pipelines. Analytics engineers bridge the gap between data science and data engineering by transforming raw data into clean, reliable datasets that can be easily analyzed by data analysts and data scientists\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'automation \', \'uuid\': \'6782c8eb-3d02-43f3-9d67-5c63c22c10a7\', \'others\': [], \'skills\': [\'airflow\', \'aws\', \'cicd\', \'cml\', \'dbt\', \'docker\', \'git\', \'hyper parameter tuning\', \'linux\', \'ml pipeline\', \'mlflow\', \'unit testng\'], \'status\': \'approved\', \'display\': \'Automation \', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084619\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has sound generic, domain, and specialist knowledge necessary for effective performance, typically gained from recognized bodies of knowledge and organizational information. Understands and effectively applies appropriate methods, tools, applications, and processes. Demonstrates judgment and a systematic approach to work, applies a methodical approach to routine and moderately complex issue definition and resolution, may oversee others or make decisions impacting routine work assigned to individuals or project stages, and works under general direction with specific guidance and milestone reviews.\', \'sfia_level\': \'3\', \'description\': \' Automation in machine learning (ML) and data engineering involves using tools and processes to streamline, simplify and enhance the development, deployment, and maintenance of ML models and data pipelines. This automation aims to improve efficiency, reduce errors, and enable scalability\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'mathematics\', \'uuid\': \'77348cb1-6083-4dc6-b5fc-d61eb237869b\', \'others\': [], \'skills\': [\'algorithm\', \'deep learning\', \'machine learning\', \'mathematics\'], \'status\': \'approved\', \'display\': \'Mathematics\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084820\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has gained basic domain knowledge and demonstrates application of essential generic knowledge typically found in industry bodies of knowledge. Absorbs new information when presented systematically and applies it effectively. Understands and uses appropriate methods, tools, applications, and processes. Shows a rational and organized approach to work, performs a range of activities in varied environments, interacts with and may influence immediate colleagues, and uses limited discretion in resolving issues or inquiries.\', \'sfia_level\': \'2\', \'description\': \'Mathema

In [5]:
import json, os, ast
import pandas as pd

In [76]:
with open("/home/rehmet/dev/tenx_ipersona/frontend/src/assets/mock-data/user_profiles.json", "r") as file:
    data = json.load(file)
# data

In [77]:
for item in data:
    if 'basics.attributes' in item:
        basic_attributes = []
        basic = ast.literal_eval(item['basics.attributes'])
        json.dumps(basic)
        print("got")
        print(basic)
        for x in basic:
            role = x.get('role')
            personal_statement = x.get('personal_statement')  
            if role and personal_statement: 
                basic_attributes.append({
                    'role': role,
                    'personal_statement': personal_statement
                })
        item['basics.attributes'] = basic_attributes       
        
    if 'projects.attributes' in item:
        project_attributes = []
        project = ast.literal_eval(item['projects.attributes'])
        json.dumps(project)
        for x in project:
            title = x.get('title')
            summary = x.get('summary')  
            if title and summary: 
                project_attributes.append({
                    'title': title,
                    'summary': summary
                })
        item['projects.attributes'] = project_attributes   
        
    if 'education.attributes' in item:
        education_attributes = []
        education = ast.literal_eval(item['education.attributes'])
        json.dumps(education)
        for x in education:
            study_area = x.get('study_area')
            study_type = x.get('study_type')
            institution_name = x.get('institution_name')  
            start_date = x.get('start_date')
            end_date = x.get('end_date')

            if study_area and study_type and institution_name and start_date and end_date: 
                education_attributes.append({
                    'study_area': study_area,
                    'study_type': study_type,
                    'institution_name': institution_name,
                    'start_date': start_date,
                    'end_date': end_date
                })
 
        item['education.attributes'] = education_attributes
        
    if 'work_experience.attributes' in item:
        work_attributes = []
        work = ast.literal_eval(item['work_experience.attributes'])
        json.dumps(work)
        for x in work:
            role = x.get('role')
            company = x.get('company')
            summary = x.get('summary')  
            start_date = x.get('start_date')
            end_date = x.get('end_date')

            if role and company and summary and start_date and end_date: 
                work_attributes.append({
                    'role': role,
                    'company': company,
                    'summary': summary,
                    'start_date': start_date,
                    'end_date': end_date
                })
                
        item['work_experience.attributes'] = work_attributes
        
# json.dumps(data)

got
[{'role': 'Generative AI Engineer | Software Engineer | Machine Learning | Cloud Solutions (Azure, AWS) | Advocate for Continuous Improvement', 'uuid': 'e0eab10e-67ca-47c1-b89d-cd38f78037bc', 'email': 'aberhamyirsaw@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-15T05:55:43.666429'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Ethiopia', 'country': 'US', 'postal_code': ''}, 'full_name': 'Abraham Teka', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': "Abraham Teka here, ambitious about advancing software solutions through Generative AI and cloud computing. With certifications in Azure and AWS, I specialize in RAG systems, prompt engineering, and LLM fine-tuning. I aim to innovate and drive technological advancements in AI and software engineering. Let's connect and build intelligent solutions that make technology beneficial to everyone!"}]
got
[{'role': 'Generative AI & ML Engineer | CTO | Computer & Software Engineer | Entrepreneur | RAG Systems | Data Warehouse Professional', 'uuid': '48df28a6-5d04-4a78-9d39-fb304ade1cf9', 'email': 'abubekershamil123@gmail.com', 'image': '', 'media': [{'icon': '', 'link': 'https://www.linkedin.com/in/abubeker-shamil/', 'name': 'LinkedIn'}, {'icon': '', 'link': 'https://github.com/dev-abuke', 'name': 'GitHub'}, {'icon': '', 'link': 'https://medium.com/@abubekershamil', 'name': 'Medium'}, {'icon': '', 'link': 'https://abubekershamil.com', 'name': 'Website'}], 'phone': [{'icon': 'https://pngimg.com/uploads/phone/phone_PNG48988.png', 'name': 'Main', 'value': '+251912121388'}], 'status': 'approved', 'history': [{'blob': '', 'user': '1974', 'status': 'approved', 'timestamp': '2024-08-17T08:55:50.435440'}], 'location': {'city': 'Addis Ababa', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Addis Ababa', 'country': 'Ethiopia', 'postal_code': ''}, 'full_name': 'Abubeker Shamil', 'name_title': 'Mr', 'verified_by': '', 'requested_by': '', 'personal_statement': 'Abubeker Shamil is a dedicated Software Engineer with proven leadership skills. Proficient in Python, JavaScript, fine-tuning LLMs, RAG systems, prompt engineering, Langchain, and various frameworks. Known for a problem-solving mindset, effective communication skills, and a collaborative attitude. Passionate about Generative AI and Technology, with experience in developing advanced NLP systems and optimizing data workflows.'}]
got
[{'role': 'Generative AI Engineer | Machine learning| Data engineering |Electrical engineer | Electrical lighting designer', 'uuid': 'a6c41abe-bf4b-4d20-ae7c-c9db8c7afcd6', 'email': 'bethelhem.mebratu.123@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2098', 'status': 'approved', 'timestamp': '2024-08-16T08:26:29.277183'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Ethiopia', 'country': 'US', 'postal_code': ''}, 'full_name': 'Bethelhem Mebratu', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': 'I am a junior Generative AI Engineer with a programming foundation and committed to advancing my skills in AI and technology . My expertise lies in Python, SQL and vector databases. I have hands on experience in building and fine-tuning Generative AI models,LLMs implementing RAG systems, and developing chatbots. Additionally, I am skilled in various data-related tasks such as analysis, processing, visualization, and building data warehouses.'}]
got
[{'role': 'Generative AI Engineer | Machine Learning | Software Engineer | Data Engineering', 'uuid': '69a9a5f2-fd0f-4355-8a3a-b09191913e5e', 'email': 'hillary6k@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2187', 'status': 'approved', 'timestamp': '2024-08-05T02:25:24.391717'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Kenya', 'country': 'US', 'postal_code': ''}, 'full_name': 'Hillary Kipkemoi', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': "I am Generative AI Engineer with solid foundation in mathematics and full-stack development. I'm skilled in building RAG systems, fine-tuning LLMs, prompt engineering, and building chatbot applications. I'm also proficient in Python, React, and MLOps tools & practices such as Kafka, Airflow and Github Actions.\n\nI am committed to continuous learning and research in the field of Artificial intelligence and actively exploring the latest advancements in NLP, generative AI to create impactful solutions."}]
got
[{'role': 'Generative AI Engineer | Machine Learning | Data Engineering | Application Support Engineer at ZamZam Bank', 'uuid': '573d1e46-b7c7-4c77-8aa9-b44f838bf535', 'email': 'mahbubah.abdulhakim12@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2116', 'status': 'approved', 'timestamp': '2024-08-05T02:25:39.965493'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Ethiopia', 'country': 'US', 'postal_code': ''}, 'full_name': 'Mahbubah Abdulhakim', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': 'A junior generative AI Engineer with 3+ year experience in IT Industry, committed to advancing my skills in AI and technology. Proficient in Python, SQL, and vector databases. Specialized in fine-tuning LLMs, building RAG systems, prompt engineering and AI Chatbot development, with a strong foundation in neural networks and natural language processing (NLP). Demonstrated expertise through hands-on project work in these areas.'}]

In [ ]:
json.loads(data)

In [ ]:
# dat = ast.literal_eval(data)
type(data)
json.loads(str(data))

In [24]:
new_attributes = []
for item in data:
    if 'basics.attributes' in item:
        for x in item['basics.attributes']:
            role = x.get('role')
            personal_statement = x.get('personal_statement')  
            if role and personal_statement: 
                new_attributes.append({
                    'role': role,
                    'personal_statement': personal_statement
                })
                
new_attributes

[{'role': 'Generative AI Engineer | Software Engineer | Machine Learning | Cloud Solutions (Azure, AWS) | Advocate for Continuous Improvement',
  'personal_statement': "Abraham Teka here, ambitious about advancing software solutions through Generative AI and cloud computing. With certifications in Azure and AWS, I specialize in RAG systems, prompt engineering, and LLM fine-tuning. I aim to innovate and drive technological advancements in AI and software engineering. Let's connect and build intelligent solutions that make technology beneficial to everyone!"},
 {'role': 'Generative AI & ML Engineer | CTO | Computer & Software Engineer | Entrepreneur | RAG Systems | Data Warehouse Professional',
  'personal_statement': 'Abubeker Shamil is a dedicated Software Engineer with proven leadership skills. Proficient in Python, JavaScript, fine-tuning LLMs, RAG systems, prompt engineering, Langchain, and various frameworks. Known for a problem-solving mindset, effective communication skills, and a collaborative attitude. Passionate about Generative AI and Technology, with experience in developing advanced NLP systems and optimizing data workflows.'},
 {'role': 'Generative AI Engineer | Machine learning| Data engineering |Electrical engineer | Electrical lighting designer',
  'personal_statement': 'I am a junior Generative AI Engineer with a programming foundation and committed to advancing my skills in AI and technology . My expertise lies in Python, SQL and vector databases. I have hands on experience in building and fine-tuning Generative AI models,LLMs implementing RAG systems, and developing chatbots. Additionally, I am skilled in various data-related tasks such as analysis, processing, visualization, and building data warehouses.'},
 {'role': 'Generative AI Engineer | Machine Learning | Software Engineer | Data Engineering',
  'personal_statement': "I am Generative AI Engineer with solid foundation in mathematics and full-stack development. I'm skilled in building RAG systems, fine-tuning LLMs, prompt engineering, and building chatbot applications. I'm also proficient in Python, React, and MLOps tools & practices such as Kafka, Airflow and Github Actions.\n\nI am committed to continuous learning and research in the field of Artificial intelligence and actively exploring the latest advancements in NLP, generative AI to create impactful solutions."},
 {'role': 'Generative AI Engineer | Machine Learning | Data Engineering | Application Support Engineer at ZamZam Bank',
  'personal_statement': 'A junior generative AI Engineer with 3+ year experience in IT Industry, committed to advancing my skills in AI and technology. Proficient in Python, SQL, and vector databases. Specialized in fine-tuning LLMs, building RAG systems, prompt engineering and AI Chatbot development, with a strong foundation in neural networks and natural language processing (NLP). Demonstrated expertise through hands-on project work in these areas.'}]

In [ ]:
import pandas

:

In [4]:
chat = [{'user_type': 'candidate', 'content_type': 'answer', 'complete': False, 'content': {'response': '1', 'time_taken': '00:34', 'realtime_evaluation': 'null'}}, {'user_type': 'assistant', 'content_type': 'overall_feedback', 'complete': True, 'content': {'time_taken': 'null', 'response': {'question_number': '2', 'question': 'What relevant work experiences do you have that align with the responsibilities of a Machine Learning Research Engineer?', 'question_type': 'Background', 'time_limit': '02:00', 'end_message': 'Please take your time to provide a detailed response'}, 'realtime_evaluation': None}}, {'user_type': 'candidate', 'content_type': 'answer', 'complete': False, 'content': {'response': '2', 'time_taken': '03:05', 'realtime_evaluation': 'null'}}, {'user_type': 'assistant', 'content_type': 'question_feedback', 'complete': False, 'content': {'time_taken': 'null', 'response': {'question': 'Can you provide specific examples of projects or experiences that demonstrate your skills in machine learning or computer vision?', 'question_type': 'follow-up', 'time_limit': '02:00', 'end_message': 'Please take your time to provide a detailed response'}, 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response did not provide any relevant work experiences that align with the responsibilities of a Machine Learning Research Engineer. It is important to highlight specific projects or roles that demonstrate your skills and experience in machine learning, computer vision, or related areas.'}, 'answer_relevancy': [{'level': '20', 'reason': 'The response did not address the question at all, lacking any relevant details or examples.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'The response was unclear and did not convey any meaningful information.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was no engagement or enthusiasm in the response, making it difficult to assess your interest in the role.'}]}}}, {'user_type': 'candidate', 'content_type': 'answer', 'complete': False, 'content': {'response': '4', 'time_taken': '07:50', 'realtime_evaluation': 'null'}}, {'user_type': 'assistant', 'content_type': 'question_feedback', 'complete': False, 'content': {'time_taken': 'null', 'response': {'question_number': '4', 'question': 'What are some common machine learning and computer vision concepts you have worked with, and how do you stay updated with advancements in these fields?', 'question_type': 'Technical', 'time_limit': '02:30', 'end_message': 'Please take your time to provide a detailed response'}, 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of specific examples related to machine learning or computer vision projects. Providing concrete details about your experiences would strengthen your answer and demonstrate your skills more effectively.'}, 'answer_relevancy': [{'level': '40', 'reason': 'The response did not provide any specific examples or details, making it difficult to assess the relevance to the question.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'The response was vague and did not clearly convey any relevant information.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a lack of enthusiasm or detail in the response, which may indicate disinterest or uncertainty.'}]}}}]
global chat_count
chat_count = 1
assistant_count = sum(1 for entry in chat if entry["user_type"] == "assistant")
chat_count += assistant_count 
print(chat_count)
len(chat)

4

6

# openai

In [1]:
from openai import OpenAI

OPENAI_API_KEY = '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'

client = OpenAI(api_key=OPENAI_API_KEY)

In [5]:
# client = OpenAI()

audio_file= open("/home/ek/Documents/10Xtutor/SIFA/tenx_ipersona/notebooks/output.mp3", "rb")
transcription = client.audio.transcriptions.create(
  model="whisper-1", 
  file=audio_file,
)
transcription.text

'Hello, world. This is a streaming test.'

In [3]:
# from openai import OpenAI
# OPENAI_API_KEY = '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'

# client = OpenAI(api_key=OPENAI_API_KEY)

with client.audio.speech.with_streaming_response.create(
    model="tts-1",
    voice="alloy",
    input="""I see skies of blue and clouds of white
             The bright blessed days, the dark sacred nights
             And I think to myself
             What a wonderful world""",
) as response:
    print(response)
    # response.stream_to_file("speech.mp3")

<StreamedBinaryAPIResponse [200 OK] type=<class 'bytes'>>

In [ ]:
response = client.audio.speech.create(
    model="tts-1",
    voice="alloy",
    input="in NLP",
)
# in NLP, particularly in NLP
response.stream_to_file("output.mp3")

/tmp/ipykernel_1672198/4019599215.py:7: DeprecationWarning: Due to a bug, this method doesn't actually stream the response content, `.with_streaming_response.method()` should be used instead
  response.stream_to_file("output.mp3")

In [3]:
response

In [3]:
! apt install python3-pyaudio

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

In [4]:
import os
import requests
from time import time
import pyaudio

url = "https://api.openai.com/v1/audio/speech"
headers = {
    "Authorization": f'Bearer {os.getenv("OPENAI_API_KEY")}',
}

data = {
    "model": "tts-1",
    "input": "This is a test",
    "voice": "shimmer",
    "response_format": "wav",
}

start_time = time()
response = requests.post(url, headers=headers, json=data, stream=True)
if response.status_code == 200:
    print(f"Time to first byte: {int((time() - start_time) * 1000)} ms")
    p = pyaudio.PyAudio()
    stream = p.open(format=8, channels=1, rate=24000, output=True)
    for chunk in response.iter_content(chunk_size=1024):
        stream.write(chunk)
    print(f"Time to complete: {int((time() - start_time) * 1000)} ms")

ModuleNotFoundError: No module named 'pyaudio'

Openai-Streaming

In [8]:
import time
# record the time before the request is sent
start_time = time.time()

# send a ChatCompletion request to count to 100
response = client.chat.completions.create(
    model='gpt-4o-mini',
    messages=[
        {'role': 'user', 'content': 'Count to 100, with a comma between each number and no newlines. E.g., 1, 2, 3, ...'}
    ],
    temperature=0,
)
# calculate the time it took to receive the response
response_time = time.time() - start_time

# print the time delay and text received
print(f"Full response received {response_time:.2f} seconds after request")
print(f"Full response received:\n{response}")

Full response received 6.38 seconds after request
Full response received:
ChatCompletion(id='chatcmpl-AMDoqbZetUtidX1Mj0O3WZIXmbpPx', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100', refusal=None, role='assistant', function_call=None, tool_calls=None))], created=1729859700, model='gpt-4o-mini-2024-07-18', object='chat.completion', service_tier=None, system_fingerprint='fp_f59a81427f', usage=CompletionUsage(completion_tokens=298, prompt_tokens=36, total_tokens=334, prompt_tokens_details={'cached_tokens': 0}, completion_tokens_details={'reasoning_tokens': 0}))

In [5]:
reply = response.choices[0].message
print(f"Extracted reply: \n{reply}")

reply_content = response.choices[0].message.content
print(f"Extracted content: \n{reply_content}")

Extracted reply:
ChatCompletionMessage(content='1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100', refusal=None, role='assistant', function_call=None, tool_calls=None)
Extracted content:
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100

streaming

In [21]:
# Example of an OpenAI ChatCompletion request with stream=True
# https://platform.openai.com/docs/api-reference/streaming#chat/create-stream

# a ChatCompletion request
response = client.chat.completions.create(
    model='gpt-4o-mini',
    messages=[
        {'role': 'user', 'content': "Tell me about ethiopia in 1 page words?"}
    ],
    temperature=0,
    stream=True  # this time, we set stream=True
)

for chunk in response:
    # print(chunk)
    print(chunk.choices[0].delta.content)
    # print("****************")

E
thi
opia
,
 located
 in
 the
 Horn
 of
 Africa
,
 is
 a
 country
 rich
 in
 history
,
 culture
,
 and
 diversity
.
 It
 is
 one
 of
 the
 oldest
 nations
 in
 the
 world
,
 with
 human
 habitation
 dating
 back
 millions
 of
 years
,
 evidenced
 by
 the
 discovery
 of
 ancient
 hom
in
id
 fossils
 like
 "
Lucy
."
 Ethiopia
 is
 unique
 in
 that
 it
 was
 never
 colon
ized
,
 maintaining
 its
 sovereignty
 except
 for
 a
 brief
 Italian
 occupation
 during
 World
 War
 II
.


The
 country
 is
 known
 for
 its
 diverse
 ethnic
 groups
,
 with
 over

80
 distinct
 national
ities
,
 each
 contributing
 to
 a
 vibrant
 cultural
 tapestry
.
 The
 largest
 ethnic
 group
 is
 the
 Oromo
,
 followed
 by
 the
 Am
hara
,
 T
igr
ay
,
 and
 Somali
,
 among
 others
.
 This
 diversity
 is
 reflected
 in
 Ethiopia
's
 languages
,
 with
 Am
har
ic
 being
 the
 official
 language
,
 while
 other
 languages
 like
 Oromo
 and
 T
igr
inya
 are
 also
 widely
 spoken
.


E
thi
opia
 is
 famous
 for
 its
 unique
 calendar
 and
 time
 system
,
 which
 differs
 from
 the
 Gregorian
 calendar
 used
 in
 most
 of
 the
 world
.
 The
 Ethiopian
 calendar
 has

13
 months
 and
 is
 approximately
 seven
 to
 eight
 years
 behind
 the
 Gregorian
 calendar
.
 The
 country
 is
 also
 known
 for
 its
 rich
 religious
 heritage
,
 being
 one
 of
 the
 first
 nations
 to
 adopt
 Christianity
 in
 the

4
th
 century
,
 and
 it
 is
 home
 to
 a
 significant
 Muslim
 population
 as
 well
.


Ge
ographically
,
 Ethiopia
 boasts
 a
 varied
 landscape
,
 from
 the
 high
lands
 and
 plate
aus
 to
 the
 Great
 Rift
 Valley
 and
 low
land
 plains
.
 The
 Sim
ien
 Mountains
,
 a
 UNESCO
 World
 Heritage
 site
,
 offer
 stunning
 vistas
 and
 are
 home
 to
 unique
 wildlife
,
 including
 the
 Ethiopian
 wolf
 and
 the
 Gel
ada
 bab
oon
.
 The
 country
 is
 also
 known
 for
 its
 coffee
,
 often
 considered
 some
 of
 the
 best
 in
 the
 world
,
 with
 a
 rich
 coffee
 culture
 that
 dates
 back
 centuries
.


E
thi
opia
's
 economy
 is
 primarily
 agr
arian
,
 with
 agriculture
 employing
 a
 significant
 portion
 of
 the
 population
.
 However
,
 in
 recent
 years
,
 the
 country
 has
 seen
 rapid
 economic
 growth
,
 driven
 by
 investments
 in
 infrastructure
 and
 manufacturing
.
 Despite
 this
 progress
,
 challenges
 such
 as
 poverty
,
 political
 instability
,
 and
 ethnic
 tensions
 remain
.


E
thi
opia
's
 political
 landscape
 has
 been
 marked
 by
 a
 complex
 history
,
 including
 a
 long
-standing
 civil
 conflict
 and
 recent
 efforts
 toward
 reform
 and
 democrat
ization
.
 The
 country
 has
 made
 strides
 in
 peace
building
,
 particularly
 following
 the
 peace
 agreement
 with
 Erit
rea
 in

201
8
,
 which
 ended
 a
 two
-de
cade
-long
 conflict
.


In
 summary
,
 Ethiopia
 is
 a
 nation
 of
 profound
 historical
 significance
,
 cultural
 richness
,
 and
 natural
 beauty
.
 Its
 journey
 through
 time
 reflects
 resilience
 and
 a
 unique
 identity
 that
 continues
 to
 evolve
 in
 the
 face
 of
 modern
 challenges
.
None

In [10]:
import asyncio

def fetch_chunks(client, model, messages, temperature=0):
    response = client.chat.completions.create(  
        model=model,
        messages=messages,
        temperature=temperature,
        stream=True 
    )

    for chunk in response:
        chunk_message = chunk.choices[0].delta.content 
        if chunk_message: 
            yield chunk_message

def main():
    model = 'gpt-4o-mini'
    messages = [{'role': 'user', 'content': "what is your name?"}]

    for chunk in fetch_chunks(client, model, messages):
        print(chunk)  
        # return chunk

main()

I
’m
 called
 Chat
GPT
.
 How
 can
 I
 assist
 you
 today
?

In [71]:
def fetch_chunks(client, model, messages, temperature=0):
    response = client.chat.completions.create(  
        model=model,
        messages=messages,
        temperature=temperature,
        stream=True 
    )

    for chunk in response:
        chunk_message = chunk.choices[0].delta.content 
        if chunk_message:  
            yield chunk_message

def stream_chunks():
    model = 'gpt-4o-mini'
    messages = [{'role': 'user', 'content': "What is your name?"}]
    def generate():
        accumulated_message = ''

        for chunk in fetch_chunks(client, model, messages):
            words = chunk.split()
            accumulated_message += ' '.join(words) + ' ' 
            yield accumulated_message.strip()  # Yield the accumulated message


    return generate()


chunk_generator = stream_chunks()

for chunk in chunk_generator:
    print(chunk)

I
I ’m
I ’m called
I ’m called Chat
I ’m called Chat GPT
I ’m called Chat GPT .
I ’m called Chat GPT . How
I ’m called Chat GPT . How can
I ’m called Chat GPT . How can I
I ’m called Chat GPT . How can I assist
I ’m called Chat GPT . How can I assist you
I ’m called Chat GPT . How can I assist you today
I ’m called Chat GPT . How can I assist you today ?

In [52]:
import textwrap
from IPython.display import display, clear_output, HTML

async def process_streamed_responses(response_stream):
    response_text = ""
    for chunk in response_stream:
        chunk_message = chunk.choices[0].delta.content
        if chunk_message is not None:  
            response_text += chunk_message
        is_complete = chunk.choices[0].finish_reason is not None
        wrapped_text = textwrap.fill(response_text, width=80)  
        # print(wrapped_text)
        clear_output(wait=True)
        display(HTML(f"<div style='text-align: left;'><pre>{wrapped_text}</pre></div>"))
        if is_complete:
            break

In [67]:
def fetch_chunks(client, model, messages, temperature=0):
    response = client.chat.completions.create(  
        model=model,
        messages=messages,
        temperature=temperature,
        stream=True 
    )
    return response

async def main():
    model = 'gpt-4o-mini'
    messages = [{'role': 'user', 'content': "Tell me about ethiopia in 100 character?"}]
    response = fetch_chunks(client, model, messages)
    await process_streamed_responses(response)
        
        
await main()

In [5]:
import asyncio
import textwrap

async def process_streamed_responses(response_stream):
    response_text = ""
    complete_texts = []
    
    for chunk in response_stream:
        chunk_message = chunk.choices[0].delta.content
        if chunk_message is not None:  
            response_text += chunk_message
        is_complete = chunk.choices[0].finish_reason is not None
        
        wrapped_text = textwrap.fill(response_text, width=80)  
        complete_texts.append(wrapped_text)
        
        if is_complete:
            break

    # return "\n".join(complete_texts)  
    return complete_texts

def fetch_chunks(client, model, messages, temperature=0):
    response = client.chat.completions.create(  
        model=model,
        messages=messages,
        temperature=temperature,
        stream=True 
    )
    return response

async def main():
    model = 'gpt-4o-mini'
    messages = [{'role': 'user', 'content': "Tell me about Ethiopia in 1 page words?"}]
    response = fetch_chunks(client, model, messages)
    print("call", response)
    return await process_streamed_responses(response)

result = await main()
print(result)

call <openai.Stream object at 0x748509bd4c40>

In [11]:
async def openai_gpt_assistant_without_streaming(msg):
    model = 'gpt-4o-mini'
    temperature = 0
    messages = [{'role': 'user', 'content': msg}]

    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature
    )
    
    # Access the content correctly
    response_message = response.choices[0].message.content  # Access the content directly as an attribute
    return response_message

# Example usage
response = await openai_gpt_assistant_without_streaming(msg="what is your name?")
print(response)

I’m called ChatGPT. How can I assist you today?

#

In [ ]:
data = [
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "",
            "time_taken": "00:00",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "Can",
                " you",
                " describe",
                " your",
                " educational",
                " background",
                " and",
                " how",
                " it",
                " has",
                " prepared",
                " you",
                " for",
                " a",
                " role",
                " in",
                " data",
                " science",
                ",",
                " particularly",
                " in",
                " NLP",
                "?",
                " Please",
                " take",
                " your",
                " time",
                " to",
                " provide",
                " a",
                " detailed",
                " response",
                "."
            ],
            "full_response": "Can you describe your educational background and how it has prepared you for a role in data science, particularly in NLP? Please take your time to provide a detailed response.",
            "realtime_evaluation": ""
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "1",
            "time_taken": "00:02",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "Can",
                " you",
                " elaborate",
                " on",
                " a",
                " specific",
                " project",
                " where",
                " you",
                " utilized",
                " machine",
                " learning",
                " techniques",
                ",",
                " particularly",
                " in",
                " the",
                " context",
                " of",
                " NLP",
                ",",
                " and",
                " what",
                " challenges",
                " you",
                " faced",
                " during",
                " that",
                " project",
                "?"
            ],
            "full_response": "Can you elaborate on a specific project where you utilized machine learning techniques, particularly in the context of NLP, and what challenges you faced during that project?",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus more on specific experiences or skills that relate directly to the role of Data Scientist (NLP) and the requirements outlined in the job description."
                },
                "answer_relevancy": [
                    {
                        "level": "40",
                        "reason": "Some elements of your response touched on relevant skills, but the majority did not directly address the question or the specific requirements of the job."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "Many parts of your response were difficult to follow, making it challenging to understand your main points."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "There was a noticeable lack of enthusiasm or responsiveness in your delivery, which may affect how your interest in the role is perceived."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "2",
            "time_taken": "00:08",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "Can",
                " you",
                " explain",
                " your",
                " experience",
                " with",
                " machine",
                " learning",
                " frameworks",
                " such",
                " as",
                " Tensor",
                "Flow",
                " or",
                " Py",
                "Torch",
                ",",
                " and",
                " how",
                " you",
                " have",
                " applied",
                " them",
                " in",
                " your",
                " projects",
                "?",
                " Please",
                " take",
                " your",
                " time",
                " to",
                " provide",
                " a",
                " detailed",
                " response",
                "."
            ],
            "full_response": "Can you explain your experience with machine learning frameworks such as TensorFlow or PyTorch, and how you have applied them in your projects? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus more on the specific aspects of the role and how your experiences align with the requirements outlined in the job description."
                },
                "answer_relevancy": [
                    {
                        "level": "40",
                        "reason": "Some elements of your response were relevant, but many did not directly address the question, leading to a lower relevancy score."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Good",
                        "reason": "Your response was mostly coherent, but there were parts that could have been clearer and more focused on the question."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "You did not show much enthusiasm or engagement during your response, which could impact the overall impression in an interview setting."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "3",
            "time_taken": "00:05",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "Can",
                " you",
                " elaborate",
                " on",
                " the",
                " specific",
                " skills",
                " or",
                " experiences",
                " you",
                " have",
                " that",
                " make",
                " you",
                " a",
                " strong",
                " fit",
                " for",
                " the",
                " Data",
                " Scientist",
                " (",
                "N",
                "LP",
                ")",
                " role",
                ",",
                " particularly",
                " in",
                " relation",
                " to",
                " the",
                " required",
                " qualifications",
                " listed",
                " in",
                " the",
                " job",
                " description",
                "?"
            ],
            "full_response": "Can you elaborate on the specific skills or experiences you have that make you a strong fit for the Data Scientist (NLP) role, particularly in relation to the required qualifications listed in the job description?",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus more on the specific aspects of the question and provide examples that clearly illustrate your points."
                },
                "answer_relevancy": [
                    {
                        "level": "40",
                        "reason": "Some elements of your response were relevant, but many did not directly address the question, leading to a lower relevancy score."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "Many parts of your response were difficult to follow, which may confuse the interviewer."
                    },
                    {
                        "skill": "engagement",
                        "level": "Good",
                        "reason": "You participated in the discussion, but there was a noticeable lack of enthusiasm that could have made your response more compelling."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "4",
            "time_taken": "00:07",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "Describe",
                " a",
                " situation",
                " where",
                " you",
                " had",
                " to",
                " collaborate",
                " with",
                " a",
                " team",
                " to",
                " achieve",
                " a",
                " common",
                " goal",
                ".",
                " What",
                " role",
                " did",
                " you",
                " play",
                " and",
                " what",
                " was",
                " the",
                " result",
                "?",
                " Please",
                " take",
                " your",
                " time",
                " to",
                " provide",
                " a",
                " detailed",
                " response",
                "."
            ],
            "full_response": "Describe a situation where you had to collaborate with a team to achieve a common goal. What role did you play and what was the result? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus on providing specific examples or details that align more closely with the question to enhance your answer."
                },
                "answer_relevancy": [
                    {
                        "level": "40",
                        "reason": "The response included some relevant points, but many aspects did not directly address the question, leading to a lower relevancy score."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "Many parts of your response were difficult to follow, which may confuse the interviewer."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "There was a noticeable lack of enthusiasm or responsiveness in your participation, which could impact the overall impression."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "5",
            "time_taken": "00:10",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "Can",
                " you",
                " elaborate",
                " on",
                " what",
                " specific",
                " experiences",
                " or",
                " skills",
                " you",
                " believe",
                " contribute",
                " to",
                " your",
                " proficiency",
                " in",
                " data",
                " modeling",
                " and",
                " statistical",
                " analysis",
                "?"
            ],
            "full_response": "Can you elaborate on what specific experiences or skills you believe contribute to your proficiency in data modeling and statistical analysis?",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus on providing specific examples or details that align more closely with the question to enhance your answer."
                },
                "answer_relevancy": [
                    {
                        "level": "30",
                        "reason": "The response included some elements that were not directly related to the question, indicating a need for more focused answers."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "Many parts of your response were difficult to follow, which may confuse the interviewer."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "There was a noticeable lack of enthusiasm or responsiveness during your answer, which could impact the overall impression."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "6",
            "time_taken": "00:06",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": [
                "What",
                " strategies",
                " do",
                " you",
                " employ",
                " to",
                " handle",
                " im",
                "balanced",
                " datasets",
                ",",
                " and",
                " can",
                " you",
                " share",
                " an",
                " experience",
                " where",
                " you",
                " successfully",
                " applied",
                " these",
                " strategies",
                "?",
                " Please",
                " take",
                " your",
                " time",
                " to",
                " provide",
                " a",
                " detailed",
                " response",
                "."
            ],
            "full_response": "What strategies do you employ to handle imbalanced datasets, and can you share an experience where you successfully applied these strategies? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus on providing specific examples or details that align more closely with the question to enhance your answer."
                },
                "answer_relevancy": [
                    {
                        "level": "30",
                        "reason": "The response contained some elements that could be related to the question, but overall it did not adequately address the core aspects that were being asked."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "Many parts of your response were difficult to follow, which may have led to confusion about your main points."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "There was a noticeable lack of enthusiasm or responsiveness in your delivery, which could impact how your message is received."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "7",
            "time_taken": "00:05",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:00",
            "chunk_response": [
                "Can",
                " you",
                " elaborate",
                " on",
                " what",
                " you",
                " mean",
                " by",
                " \"",
                "7",
                "\"?",
                " What",
                " specific",
                " context",
                " or",
                " criteria",
                " are",
                " you",
                " referring",
                " to",
                "?"
            ],
            "full_response": "Can you elaborate on what you mean by \"7\"? What specific context or criteria are you referring to?",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response did not provide any relevant information or context related to the question. It is important to address the question directly and provide specific examples or insights that demonstrate your understanding and experience."
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The response lacked any relevant content that could be connected to the question asked."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "The response was unclear and did not convey any meaningful information."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "There was no indication of interest or engagement in the response provided."
                    }
                ]
            }
        }
    },
    {
        "user_type": "candidate",
        "content_type": "answer",
        "complete": "false",
        "content": {
            "response": "8",
            "time_taken": "00:20",
            "realtime_evaluation": "null"
        }
    },
    {
        "user_type": "assistant",
        "content_type": "question",
        "complete": "false",
        "content": {
            "time_taken": "null",
            "time_limit": "02:30",
            "chunk_response": "",
            "full_response": "",
            "realtime_evaluation": {
                "overall": {
                    "relevance": "weak",
                    "feedback": "Your response suggested a lack of direct engagement with the question. It would be beneficial to provide more specific examples or details that relate directly to the topic at hand."
                },
                "answer_relevancy": [
                    {
                        "level": "30",
                        "reason": "The response contained some elements that could be relevant, but overall it did not adequately address the question or provide sufficient detail."
                    }
                ],
                "communication_skills": [
                    {
                        "skill": "clarity",
                        "level": "Poor",
                        "reason": "Many parts of your response were difficult to follow, which may lead to misunderstandings."
                    },
                    {
                        "skill": "engagement",
                        "level": "Poor",
                        "reason": "There was a noticeable lack of enthusiasm or responsiveness, which could impact the overall impression during an interview."
                    }
                ]
            }
        }
    }
]
for i in range(len(data)):
    if data[i]['user_type'] == 'assistant':  
        print(data[i])

{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['Can', ' you', ' describe', ' your', ' educational', ' background', ' and', ' how', ' it', ' has', ' prepared', ' you', ' for', ' a', ' role', ' in', ' data', ' science', ',', ' particularly', ' in', ' NLP', '?', ' Please', ' take', ' your', ' time', ' to', ' provide', ' a', ' detailed', ' response', '.'], 'full_response': 'Can you describe your educational background and how it has prepared you for a role in data science, particularly in NLP? Please take your time to provide a detailed response.', 'realtime_evaluation': ''}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['Can', ' you', ' elaborate', ' on', ' a', ' specific', ' project', ' where', ' you', ' utilized', ' machine', ' learning', ' techniques', ',', ' particularly', ' in', ' the', ' context', ' of', ' NLP', ',', ' and', ' what', ' challenges', ' you', ' faced', ' during', ' that', ' project', '?'], 'full_response': 'Can you elaborate on a specific project where you utilized machine learning techniques, particularly in the context of NLP, and what challenges you faced during that project?', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus more on specific experiences or skills that relate directly to the role of Data Scientist (NLP) and the requirements outlined in the job description.'}, 'answer_relevancy': [{'level': '40', 'reason': 'Some elements of your response touched on relevant skills, but the majority did not directly address the question or the specific requirements of the job.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'Many parts of your response were difficult to follow, making it challenging to understand your main points.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a noticeable lack of enthusiasm or responsiveness in your delivery, which may affect how your interest in the role is perceived.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['Can', ' you', ' explain', ' your', ' experience', ' with', ' machine', ' learning', ' frameworks', ' such', ' as', ' Tensor', 'Flow', ' or', ' Py', 'Torch', ',', ' and', ' how', ' you', ' have', ' applied', ' them', ' in', ' your', ' projects', '?', ' Please', ' take', ' your', ' time', ' to', ' provide', ' a', ' detailed', ' response', '.'], 'full_response': 'Can you explain your experience with machine learning frameworks such as TensorFlow or PyTorch, and how you have applied them in your projects? Please take your time to provide a detailed response.', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus more on the specific aspects of the role and how your experiences align with the requirements outlined in the job description.'}, 'answer_relevancy': [{'level': '40', 'reason': 'Some elements of your response were relevant, but many did not directly address the question, leading to a lower relevancy score.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Good', 'reason': 'Your response was mostly coherent, but there were parts that could have been clearer and more focused on the question.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'You did not show much enthusiasm or engagement during your response, which could impact the overall impression in an interview setting.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['Can', ' you', ' elaborate', ' on', ' the', ' specific', ' skills', ' or', ' experiences', ' you', ' have', ' that', ' make', ' you', ' a', ' strong', ' fit', ' for', ' the', ' Data', ' Scientist', ' (', 'N', 'LP', ')', ' role', ',', ' particularly', ' in', ' relation', ' to', ' the', ' required', ' qualifications', ' listed', ' in', ' the', ' job', ' description', '?'], 'full_response': 'Can you elaborate on the specific skills or experiences you have that make you a strong fit for the Data Scientist (NLP) role, particularly in relation to the required qualifications listed in the job description?', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus more on the specific aspects of the question and provide examples that clearly illustrate your points.'}, 'answer_relevancy': [{'level': '40', 'reason': 'Some elements of your response were relevant, but many did not directly address the question, leading to a lower relevancy score.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'Many parts of your response were difficult to follow, which may confuse the interviewer.'}, {'skill': 'engagement', 'level': 'Good', 'reason': 'You participated in the discussion, but there was a noticeable lack of enthusiasm that could have made your response more compelling.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['Describe', ' a', ' situation', ' where', ' you', ' had', ' to', ' collaborate', ' with', ' a', ' team', ' to', ' achieve', ' a', ' common', ' goal', '.', ' What', ' role', ' did', ' you', ' play', ' and', ' what', ' was', ' the', ' result', '?', ' Please', ' take', ' your', ' time', ' to', ' provide', ' a', ' detailed', ' response', '.'], 'full_response': 'Describe a situation where you had to collaborate with a team to achieve a common goal. What role did you play and what was the result? Please take your time to provide a detailed response.', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus on providing specific examples or details that align more closely with the question to enhance your answer.'}, 'answer_relevancy': [{'level': '40', 'reason': 'The response included some relevant points, but many aspects did not directly address the question, leading to a lower relevancy score.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'Many parts of your response were difficult to follow, which may confuse the interviewer.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a noticeable lack of enthusiasm or responsiveness in your participation, which could impact the overall impression.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['Can', ' you', ' elaborate', ' on', ' what', ' specific', ' experiences', ' or', ' skills', ' you', ' believe', ' contribute', ' to', ' your', ' proficiency', ' in', ' data', ' modeling', ' and', ' statistical', ' analysis', '?'], 'full_response': 'Can you elaborate on what specific experiences or skills you believe contribute to your proficiency in data modeling and statistical analysis?', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus on providing specific examples or details that align more closely with the question to enhance your answer.'}, 'answer_relevancy': [{'level': '30', 'reason': 'The response included some elements that were not directly related to the question, indicating a need for more focused answers.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'Many parts of your response were difficult to follow, which may confuse the interviewer.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a noticeable lack of enthusiasm or responsiveness during your answer, which could impact the overall impression.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': ['What', ' strategies', ' do', ' you', ' employ', ' to', ' handle', ' im', 'balanced', ' datasets', ',', ' and', ' can', ' you', ' share', ' an', ' experience', ' where', ' you', ' successfully', ' applied', ' these', ' strategies', '?', ' Please', ' take', ' your', ' time', ' to', ' provide', ' a', ' detailed', ' response', '.'], 'full_response': 'What strategies do you employ to handle imbalanced datasets, and can you share an experience where you successfully applied these strategies? Please take your time to provide a detailed response.', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct connection to the question asked. It would be beneficial to focus on providing specific examples or details that align more closely with the question to enhance your answer.'}, 'answer_relevancy': [{'level': '30', 'reason': 'The response contained some elements that could be related to the question, but overall it did not adequately address the core aspects that were being asked.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'Many parts of your response were difficult to follow, which may have led to confusion about your main points.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a noticeable lack of enthusiasm or responsiveness in your delivery, which could impact how your message is received.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:00', 'chunk_response': ['Can', ' you', ' elaborate', ' on', ' what', ' you', ' mean', ' by', ' "', '7', '"?', ' What', ' specific', ' context', ' or', ' criteria', ' are', ' you', ' referring', ' to', '?'], 'full_response': 'Can you elaborate on what you mean by "7"? What specific context or criteria are you referring to?', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response did not provide any relevant information or context related to the question. It is important to address the question directly and provide specific examples or insights that demonstrate your understanding and experience.'}, 'answer_relevancy': [{'level': '20', 'reason': 'The response lacked any relevant content that could be connected to the question asked.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'The response was unclear and did not convey any meaningful information.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was no indication of interest or engagement in the response provided.'}]}}}
{'user_type': 'assistant', 'content_type': 'question', 'complete': 'false', 'content': {'time_taken': 'null', 'time_limit': '02:30', 'chunk_response': '', 'full_response': '', 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of direct engagement with the question. It would be beneficial to provide more specific examples or details that relate directly to the topic at hand.'}, 'answer_relevancy': [{'level': '30', 'reason': 'The response contained some elements that could be relevant, but overall it did not adequately address the question or provide sufficient detail.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'Many parts of your response were difficult to follow, which may lead to misunderstandings.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a noticeable lack of enthusiasm or responsiveness, which could impact the overall impression during an interview.'}]}}}

In [1]:
data = [
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Can you describe your educational background and how it has prepared you for a role in data science, particularly in NLP? Please take your time to provide a detailed response.",
        "realtime_evaluation": ""
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "1",
        "time_taken": "02:03",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Can you elaborate on a specific project where you utilized machine learning techniques, particularly in the context of NLP, and what challenges you faced during that project?",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide any specific details about your educational background or how it has prepared you for a role in data science, particularly in NLP. It is important to connect your academic experiences directly to the skills and knowledge required for the position.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "30",
              "reason": "The response lacked relevant information regarding educational qualifications and their application to data science and NLP."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was vague and did not clearly articulate your educational background or its relevance to the role."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was no evident enthusiasm or engagement in your response, which is crucial for demonstrating interest in the role."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "2",
        "time_taken": "00:11",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Can you explain your experience with machine learning frameworks such as TensorFlow or PyTorch, and how you have applied them in your projects? Please take your time to provide a detailed response.",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide specific details about a project where you utilized machine learning techniques in NLP. It is important to share concrete examples, including the challenges faced and how you addressed them, to demonstrate your experience and problem-solving skills.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "20",
              "reason": "The response lacked specific examples and details related to the question about machine learning and NLP projects."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was vague and did not clearly convey any relevant information about your experience."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was a lack of enthusiasm and detail in your response, which may indicate a disinterest in the topic or a lack of preparation."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "3",
        "time_taken": "00:11",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Can you elaborate on what specific skills or experiences you believe make you a strong fit for the Data Scientist (NLP) role?",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide any relevant information regarding your experience with machine learning frameworks such as TensorFlow or PyTorch. It is crucial to elaborate on specific projects or tasks where you utilized these frameworks to demonstrate your expertise.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "10",
              "reason": "The response did not address the question at all, lacking any details about experience with machine learning frameworks."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was not clear as it did not contain any information relevant to the question."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was no engagement shown in the response, as it did not attempt to answer the question."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "4",
        "time_taken": "00:08",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Can you provide an example of how you have collaborated with a team to achieve a common goal in a technical project? Please take your time to provide a detailed response.",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide specific skills or experiences that relate to the Data Scientist (NLP) role. It is important to highlight relevant technical skills, projects, or experiences that demonstrate your fit for the position.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "30",
              "reason": "The response lacked specific details about relevant skills or experiences that align with the job description."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was vague and did not clearly articulate your qualifications for the role."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was a lack of enthusiasm or detail in your response, which may indicate a lack of interest in the position."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "5",
        "time_taken": "00:06",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Can you elaborate on what specific experiences or projects have contributed to your proficiency in designing and evaluating complex data models?",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide any specific example or details regarding collaboration with a team on a technical project. It is essential to share a concrete instance that illustrates your teamwork skills and how you contributed to achieving a common goal.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "20",
              "reason": "The response lacked any relevant content or context related to the question about collaboration in a technical project."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was not coherent or understandable, as it did not address the question at all."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was no engagement or enthusiasm shown in the response, as it did not provide any information."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "6",
        "time_taken": "00:01",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:30",
        "time_taken": "null",
        "full_response": "Describe a situation where you had to analyze a large dataset. What steps did you take to ensure the quality and relevance of your analysis? Please take your time to provide a detailed response.",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide any specific experiences or projects that demonstrate your proficiency in designing and evaluating complex data models. It is crucial to share concrete examples that highlight your skills and experiences in this area.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "10",
              "reason": "The response did not address the question at all, lacking any relevant information or examples."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was not clear or coherent, as it did not provide any information related to the question."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was no engagement or enthusiasm in the response, as it failed to address the question meaningfully."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "6",
        "time_taken": "00:10",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "02:00",
        "time_taken": "null",
        "full_response": "Can you elaborate on what you mean by \"6\"? What specific context or criteria are you referring to?",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not provide any details or context regarding the situation where you analyzed a large dataset. It is crucial to elaborate on the steps you took to ensure the quality and relevance of your analysis, as this demonstrates your analytical skills and understanding of data handling.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "10",
              "reason": "The response lacks any relevant information or context related to the question asked."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was not coherent or understandable, as it did not address the question at all."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was no engagement or enthusiasm shown in the response, as it was simply a numeric value without any elaboration."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "7",
        "time_taken": "00:11",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "00:42",
        "time_taken": "",
        "full_response": "",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response of '7' does not address the question about what you mean by '6'. It seems to be a misunderstanding of the question, as it requires elaboration on a specific context or criteria rather than just providing a number.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "20",
              "reason": "The answer provided does not relate to the question asked, which was seeking clarification on the meaning of '6'."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response lacks clarity as it does not provide any explanation or context related to the question."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was no engagement with the question, as the response did not attempt to address the inquiry meaningfully."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    },
    {
      "content": {
        "response": "8",
        "time_taken": "00:03",
        "realtime_evaluation": "null"
      },
      "user_type": "candidate",
      "content_type": "answer"
    },
    {
      "content": {
        "time_limit": "00:00",
        "time_taken": "null",
        "full_response": "",
        "realtime_evaluation": {
          "overall": {
            "feedback": "Your response did not directly address the question asked. It lacked specific examples or details that would demonstrate your understanding or experience related to the topic. To improve, focus on providing clear, relevant examples that align with the question.",
            "relevance": "weak"
          },
          "answer_relevancy": [
            {
              "level": "30",
              "reason": "The response provided minimal relevant information and did not effectively connect to the question, indicating a lack of understanding or preparation."
            }
          ],
          "communication_skills": [
            {
              "level": "Poor",
              "skill": "clarity",
              "reason": "The response was difficult to follow and lacked coherence, making it challenging to understand your main points."
            },
            {
              "level": "Poor",
              "skill": "engagement",
              "reason": "There was little to no enthusiasm or interest shown in your response, which may indicate a lack of preparation or confidence."
            }
          ]
        }
      },
      "user_type": "assistant",
      "content_type": "question"
    }
  ]

In [ ]:
def time_to_seconds(time_str):
    """Convert time in 'HH:MM' format to seconds."""
    if time_str == "00:00":
        return 0
    h, m = map(int, time_str.split(':'))
    return h * 3600 + m * 60

def calculate_time(interview: list) -> dict:
    try:
        exceeded_count = 0
        not_exceeded_count = 0
        
        for i in range(len(interview)):
            if interview[i]['user_type'] == 'assistant':
                assistant_response = interview[i]['content']
                if assistant_response and 'time_limit' in assistant_response:
                    time_limit = assistant_response['time_limit']
                    time_limit_seconds = time_to_seconds(time_limit)
                    
                    if i + 1 < len(interview) and interview[i+1]['user_type'] == 'candidate':
                        time_taken = interview[i + 1]['content']['time_taken']                        
                        time_taken_seconds = time_to_seconds(time_taken)

                        if time_taken_seconds > time_limit_seconds:
                            exceeded_count += 1
                        else:
                            not_exceeded_count += 1

        
        time_data = {
            "fail": exceeded_count,
            "pass": not_exceeded_count
        }
        return time_data
    
    except Exception as e:
        print(f"Calculating overall time failed: ${str(e)}")

        return {'error': str(e)}

calculate_time(data)

{'fail': 0, 'pass': 9}

In [18]:
data = [
    {
        "content": {
            "time_limit": "02:00",
            "time_taken": "null",
            "full_response": "Can you describe your educational background and how it has prepared you for a role in data science, particularly in NLP? Please take your time to provide a detailed response.",
            "realtime_evaluation": "null"
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "1",
            "time_taken": "00:04",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:30",
            "time_taken": "null",
            "full_response": "Can you elaborate on a specific project where you utilized machine learning techniques, particularly in the context of NLP, and what challenges you faced during that project?",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any information regarding your educational background or how it has prepared you for a role in data science, particularly in NLP. It is essential to connect your academic experiences to the skills and knowledge required for the position.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "30",
                        "reason": "The response lacked any relevant content related to education or its application to data science and NLP."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was unclear as it did not address the question at all, making it difficult to follow any logical thought process."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement shown in the response, as it failed to provide any relevant information or enthusiasm."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "2",
            "time_taken": "00:02",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:30",
            "time_taken": "null",
            "full_response": "Can you explain your experience with machine learning frameworks such as TensorFlow or PyTorch, and how you have applied them in your projects? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any specific details about a project where you utilized machine learning techniques in the context of NLP. Without concrete examples or challenges faced, it is difficult to assess your experience and skills in this area.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The response lacked any relevant information or context related to machine learning or NLP projects."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was vague and did not convey any clear information about your experiences."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no indication of enthusiasm or interest in discussing your projects, which may suggest a lack of preparation."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "4",
            "time_taken": "00:13",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:30",
            "time_taken": "null",
            "full_response": "Can you elaborate on what specific experiences or skills you believe contribute to your proficiency in designing and evaluating complex data models?",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any specific details about your experience with machine learning frameworks like TensorFlow or PyTorch. It is crucial to elaborate on how you have applied these frameworks in your projects, as this information is essential for evaluating your technical skills and experience.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The response did not address the question at all, lacking any relevant information about machine learning frameworks."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was not clear or coherent, as it did not provide any information related to the question."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement or enthusiasm shown in the response, as it failed to address the question."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "5",
            "time_taken": "00:01",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:00",
            "time_taken": "null",
            "full_response": "Describe a situation where you had to collaborate with a team to achieve a common goal. What role did you play and what was the result? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any specific experiences or skills related to designing and evaluating complex data models. It is important to elaborate on your relevant experiences, such as projects or tools you have used, to demonstrate your proficiency in this area.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The response did not address the question at all, lacking any relevant information or context."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was not clear or coherent, as it did not provide any information relevant to the question."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement or enthusiasm shown in the response, as it did not attempt to answer the question."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "6",
            "time_taken": "00:10",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:00",
            "time_taken": "null",
            "full_response": "Can you elaborate on what you mean by \"6\"? What specific context or criteria are you referring to?",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any details or context regarding a situation where you collaborated with a team. Without specific examples or insights into your role and the outcome, it is difficult to assess your teamwork skills or contributions.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "10",
                        "reason": "The response lacked any relevant information or context related to the question about collaboration and teamwork."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was not coherent or understandable, as it did not address the question at all."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement or enthusiasm demonstrated in the response, as it failed to provide any meaningful content."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "7",
            "time_taken": "00:02",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:30",
            "time_taken": "null",
            "full_response": "Can you walk us through your process for conducting exploratory data analysis? What tools and techniques do you typically use? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response of '7' does not address the question about what you mean by '6'. It suggests a misunderstanding of the question, as it requires elaboration on a specific context or criteria rather than just providing a number.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The answer provided does not relate to the question asked, which was seeking clarification on the meaning of '6'."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response lacks clarity as it does not provide any explanation or context, making it difficult to understand your thought process."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement with the question, as the response did not attempt to address the inquiry or show interest in elaborating."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "8",
            "time_taken": "00:01",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "02:30",
            "time_taken": "null",
            "full_response": "How do you approach problem-solving when dealing with imbalanced datasets? Can you provide an example from your experience? Please take your time to provide a detailed response.",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any details or context regarding your process for conducting exploratory data analysis. It is essential to elaborate on the specific steps you take, the tools you use, and the techniques you apply to demonstrate your understanding and experience in this area.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The response lacked any relevant information related to the question asked."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was not clear or coherent, as it did not address the question at all."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement or enthusiasm shown in the response, as it was simply a numeric value without any elaboration."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    },
    {
        "content": {
            "response": "8",
            "time_taken": "00:22",
            "realtime_evaluation": "null"
        },
        "user_type": "candidate",
        "content_type": "answer"
    },
    {
        "content": {
            "time_limit": "",
            "time_taken": "",
            "full_response": "",
            "realtime_evaluation": {
                "overall": {
                    "feedback": "Your response did not provide any relevant information regarding your approach to problem-solving with imbalanced datasets. It is crucial to elaborate on specific strategies or techniques you have used in the past, as well as any examples that demonstrate your understanding of the topic.",
                    "relevance": "weak"
                },
                "answer_relevancy": [
                    {
                        "level": "20",
                        "reason": "The response did not address the question at all, lacking any relevant details or examples related to imbalanced datasets."
                    }
                ],
                "communication_skills": [
                    {
                        "level": "Poor",
                        "skill": "clarity",
                        "reason": "The response was not clear or coherent, as it did not provide any information relevant to the question."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "There was no engagement or enthusiasm in the response, as it failed to address the question meaningfully."
                    }
                ]
            }
        },
        "user_type": "assistant",
        "content_type": "question"
    }
]

# def time_to_seconds(time_str):
#     """Convert time in 'MM:SS' or 'HH:MM:SS' format to seconds."""
#     if not time_str or time_str == "00:00":
#         return 0
    
#     time_components = list(map(int, time_str.split(':')))
    
#     # Handle "HH:MM:SS" or "MM:SS"
#     if len(time_components) == 3:  # HH:MM:SS format
#         h, m, s = time_components
#     elif len(time_components) == 2:  # MM:SS format (assuming no hours)
#         h, m, s = 0, time_components[0], time_components[1]
#     else:
#         raise ValueError(f"Unrecognized time format: {time_str}")
    
#     return h * 3600 + m * 60 + s

# def time_to_seconds(time_str):
#     """Convert time in 'HH:MM' format to seconds."""
#     if time_str == "00:00":
#         return 0
#     h, m = map(int, time_str.split(':'))
#     return h * 3600 + m * 60

def time_to_seconds(time_str):
    """Convert time in 'HH:MM' format to seconds."""
    try:
        if not time_str or time_str == "00:00":
            return 0
        time_parts = time_str.split(':')
        if len(time_parts) == 2:  # Validating that we have both HH and MM parts
            h, m = map(int, time_parts)
            return h * 3600 + m * 60
        else:
            raise ValueError(f"Invalid time format: {time_str}")
    except ValueError as e:
        print(f"Error converting time: {e}")
        return 0


def seconds_to_time(seconds):
    """Convert seconds back to 'MM:SS' format."""
    m = seconds // 60  # Get the minutes
    s = seconds % 60   # Get the remaining seconds
    return f"{m:02}:{s:02}"

def calculate_time(interview: list) -> dict:
    try:
        exceeded_count = 0
        not_exceeded_count = 0
        total_time_taken_by_candidate = 0
        
        for i in range(len(interview)):
            if interview[i]['user_type'] == 'assistant':
                assistant_response = interview[i]['content']
                if assistant_response and 'time_limit' in assistant_response:
                    time_limit = assistant_response['time_limit']
                    time_limit_seconds = time_to_seconds(time_limit)
                    
                    if i + 1 < len(interview) and interview[i+1]['user_type'] == 'candidate':
                        candidate_response = interview[i + 1]['content']
                        time_taken = candidate_response.get('time_taken', '00:00')  # Default to '00:00' if not present
                        time_taken_seconds = time_to_seconds(time_taken)
                        
                        # Accumulate the total time taken by the candidate
                        total_time_taken_by_candidate += time_taken_seconds

                        # Check if time taken exceeds the time limit
                        if time_taken_seconds > time_limit_seconds:
                            exceeded_count += 1
                        else:
                            not_exceeded_count += 1
        
        # Convert the total time to MM:SS format
        total_time_taken_formatted = seconds_to_time(total_time_taken_by_candidate)

        time_data = {
            "fail": exceeded_count,
            "pass": not_exceeded_count,
            "total_time_taken_by_candidate_seconds": total_time_taken_by_candidate,
            "total_time_taken_by_candidate_formatted": total_time_taken_formatted
        }
        
        return time_data
    
    except Exception as e:
        print(f"Calculating overall time failed: {str(e)}")
        return {'error': str(e)}

# Example usage with the provided `data`
result = calculate_time(data)
print(result)

{'fail': 0, 'pass': 8, 'total_time_taken_by_candidate_seconds': 3300, 'total_time_taken_by_candidate_formatted': '55:00'}

In [19]:
def calculate_time(interview: list) -> dict:
    """
    Calculates the time taken by candidates in relation to the time limits set by the assistant.

    This function iterates through the interview data to determine how many times a candidate 
    exceeded the time limits for their responses compared to the limits set by the assistant.

    Parameters:
    ----------
    interview : list
        A list of dictionaries representing the interview history, where each dictionary 
        contains the responses from both the assistant and the candidate.

    Returns:
    -------
    dict
        A JSON object containing the counts of times a candidate exceeded the time limits 
        ("fail") and those count times it stayed within the limits ("pass") for a single entire interview, or an error message 
        if an exception occurs during processing.
    """
    try:
        exceeded_count = 0
        not_exceeded_count = 0
        total_time_taken_by_candidate = 0
        
        for i in range(len(interview)):
            if interview[i]['user_type'] == 'assistant':
                assistant_response = interview[i]['content']
                if assistant_response and 'time_limit' in assistant_response:
                    time_limit = assistant_response['time_limit']
                    time_limit_seconds = time_to_seconds(time_limit)
                    
                    if i + 1 < len(interview) and interview[i+1]['user_type'] == 'candidate':
                        candidate_response = interview[i + 1]['content']
                        time_taken = candidate_response.get('time_taken', '00:00')  # Default to '00:00' if not present
                        time_taken_seconds = time_to_seconds(time_taken)
                        print('time-taken')
                        print(time_taken)
                        # Accumulate the total time taken by the candidate
                        total_time_taken_by_candidate += time_taken_seconds

                        # Check if time taken exceeds the time limit
                        if time_taken_seconds > time_limit_seconds:
                            exceeded_count += 1
                        else:
                            not_exceeded_count += 1
        
        # Convert the total time to MM:SS format
        total_time_taken_formatted = seconds_to_time(total_time_taken_by_candidate)

        time_data = {
            "fail": exceeded_count,
            "pass": not_exceeded_count,
            "total_time_taken_by_candidate_seconds": total_time_taken_by_candidate,
            "total_time_taken_by_candidate_formatted": total_time_taken_formatted
        }
        print('final')
        print(time_data)
        
        return time_data
    
    except Exception as e:
        print(f"Calculating overall time failed: {str(e)}")
        return {'error': str(e)}
calculate_time(data)

time-taken
00:04
time-taken
00:02
time-taken
00:13
time-taken
00:01
time-taken
00:10
time-taken
00:02
time-taken
00:01
time-taken
00:22
final
{'fail': 0, 'pass': 8, 'total_time_taken_by_candidate_seconds': 3300, 'total_time_taken_by_candidate_formatted': '55:00'}

{'fail': 0,
 'pass': 8,
 'total_time_taken_by_candidate_seconds': 3300,
 'total_time_taken_by_candidate_formatted': '55:00'}

In [3]:
def filter_the_relevancies(data: list) -> dict:
    try:
        relevancy = []
        index_counter = 1
        
        for entry in data:
            if entry['user_type'] == 'assistant' and 'realtime_evaluation' in entry['content']:
                evaluation = entry['content']['realtime_evaluation']
                if 'answer_relevancy' in evaluation:
                    for relevance in evaluation['answer_relevancy']:
                        relevance_with_index = {
                            "question_no": index_counter,  
                            "level": relevance['level'],
                            "reason": relevance['reason']
                        }
                        relevancy.append(relevance_with_index)
                        index_counter += 1 
                        
        levels = [int(item["level"]) for item in relevancy]
        average_relevancy = sum(levels) / len(levels) if levels else 0
        
        data = {
            "relevancy": relevancy,
            "average": average_relevancy
        }
        return data
    
    except Exception as e:
        print(f"Filtering overall relevance process failed: ${str(e)}")
        return {'error': str(e)}
    
relevancy = filter_the_relevancies(data)

In [4]:
def percentage_term(percent: float) -> dict:
    try:
        if not isinstance(percent, (int, float)):
            return {'error': 'Invalid input'}  

        if percent < 0 or percent > 100:
            return {'error': 'Invalid input'}  

        if 90 <= percent <= 100:
            data = {
                "term": "Excellent",
                "rating": 4
            }
            return data
        elif 75 <= percent < 90:
            data = {
                "term": "Satisfactory",
                "rating": 3
            }
            return data
        elif 50 <= percent < 75:
            data = {
                "term": "Good",
                "rating": 2
            }
            return data
        else:
            data = {
                "term": "Poor",
                "rating": 1
            }
            return data
        
    except Exception as e:
        print(f"Percentage term assignation process failed: ${str(e)}")

        return {'error': str(e)}
    
percentage_term(relevancy["average"])

{'term': 'Poor', 'rating': 1}

In [1]:
data = [
    {
        "id": "71",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "Can you describe your educational background and how it has prepared you for a role in data science, particularly in NLP? Please take your time to provide a detailed response.",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "72",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "i have a computer science background",
                        "time_taken": "00:39",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "73",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "Can you elaborate on how your computer science background has prepared you for a role in data science, particularly in areas like machine learning and natural language processing?",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response suggested a basic understanding of your background, but it lacked depth and did not directly address the question. It would be beneficial to elaborate on how your computer science background relates to the specific role and responsibilities of a Data Scientist, particularly in NLP and machine learning.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "30",
                                    "reason": "The response provided minimal information and did not connect your background to the job requirements or responsibilities."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Good",
                                    "skill": "clarity",
                                    "reason": "The response was clear in stating your background, but it was too brief to provide a comprehensive understanding."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "The response lacked enthusiasm and did not engage with the question in a meaningful way."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "74",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "i helped in being familiar with a lot of machine learning concepts",
                        "time_taken": "00:00",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "75",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response suggested a basic familiarity with machine learning concepts, but it lacked depth and specific examples that would demonstrate how your computer science background has prepared you for a role in data science. It would be beneficial to elaborate on specific skills or projects that relate directly to machine learning and natural language processing.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "30",
                                    "reason": "The response provided minimal relevant information and did not adequately address the question about how your background specifically prepares you for data science roles."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Poor",
                                    "skill": "clarity",
                                    "reason": "The response was vague and did not clearly convey your experiences or knowledge in a way that could be easily understood."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "There was a lack of enthusiasm and detail in your response, which may indicate a disinterest in the topic or a lack of preparation."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "76",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "Can you explain your experience with machine learning frameworks such as TensorFlow or PyTorch, and how you have applied them in your projects? Please take your time to provide a detailed response.",
                        "realtime_evaluation": 'null'
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "77",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "i don't have experience with pytorch",
                        "time_taken": "00:24",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "78",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "Describe a situation where you had to collaborate with a team to achieve a common goal. What role did you play and what was the result? Please take your time to provide a detailed response.",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response suggested a lack of experience with PyTorch, which is a significant part of the question. It would be beneficial to elaborate on any experience you have with TensorFlow or other machine learning frameworks, as this would provide a more comprehensive view of your skills.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "30",
                                    "reason": "The response only addressed the lack of experience with one framework and did not provide any relevant information about other frameworks or related projects."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Good",
                                    "skill": "clarity",
                                    "reason": "The response was clear in stating the lack of experience, but it did not provide additional context or details that would enhance understanding."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "The response lacked enthusiasm and did not engage with the question beyond stating a limitation."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "79",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "yes i did",
                        "time_taken": "00:18",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "80",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:00",
                        "time_taken": "null",
                        "full_response": "Can you elaborate on what you did and the specific skills or techniques you utilized during that experience?",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response did not provide any details about a specific situation, your role, or the outcome of the collaboration. It is important to elaborate on your experiences to demonstrate your ability to work in a team and achieve common goals.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "10",
                                    "reason": "The response was too vague and did not address the question about a specific collaborative situation."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Poor",
                                    "skill": "clarity",
                                    "reason": "The response was unclear and lacked detail, making it difficult to understand the context of your collaboration."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "The response did not show any enthusiasm or engagement, which is crucial in a collaborative environment."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "81",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "not really",
                        "time_taken": "00:11",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "82",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "What strategies do you employ to handle imbalanced datasets, and can you share an experience where you successfully applied these strategies? Please take your time to provide a detailed response.",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response suggested a lack of preparation or confidence in discussing your experiences. It's important to reflect on your past projects and articulate the specific skills and techniques you utilized, as this demonstrates your expertise and ability to contribute to the role.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "10",
                                    "reason": "The response did not address the question at all, indicating a significant gap in relevant information."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Poor",
                                    "skill": "clarity",
                                    "reason": "The response was unclear and did not provide any information, making it difficult to understand your experiences."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "There was no engagement or enthusiasm in your response, which may suggest a lack of interest in the topic or the interview process."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "83",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "data cleaning",
                        "time_taken": "00:15",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "84",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "02:30",
                        "time_taken": "null",
                        "full_response": "Can you describe a specific project or situation where you applied data cleaning techniques, and what challenges you faced during that process?",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response suggested a very limited understanding of the strategies needed to handle imbalanced datasets. Simply stating 'data cleaning' does not address the complexities involved in this issue, such as techniques like resampling, using different algorithms, or applying specific metrics to evaluate model performance. It would be beneficial to elaborate on your experience and provide specific examples of how you have tackled imbalanced datasets in the past.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "30",
                                    "reason": "The response only mentioned 'data cleaning,' which is a very narrow aspect of handling imbalanced datasets and does not encompass the broader strategies that are typically employed."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Poor",
                                    "skill": "clarity",
                                    "reason": "The response was vague and did not provide a clear understanding of your approach to the question."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "There was a lack of enthusiasm and detail in your response, which may indicate a disinterest in the topic or a lack of preparation."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "85",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "response": "no, not yet",
                        "time_taken": "00:14",
                        "realtime_evaluation": "null"
                    },
                    "user_type": "candidate",
                    "content_type": "answer"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    },
    {
        "id": "86",
        "attributes": {
            "attributes": {
                "message": {
                    "content": {
                        "time_limit": "",
                        "time_taken": "",
                        "full_response": "",
                        "realtime_evaluation": {
                            "overall": {
                                "feedback": "Your response suggested that you have not yet had the opportunity to apply data cleaning techniques. This indicates a lack of practical experience in a critical area for the role. It would be beneficial to seek out projects or coursework that allow you to gain this experience, as data cleaning is essential in data science.",
                                "relevance": "weak"
                            },
                            "answer_relevancy": [
                                {
                                    "level": "30",
                                    "reason": "The response did not provide any relevant information or examples related to the question about data cleaning techniques."
                                }
                            ],
                            "communication_skills": [
                                {
                                    "level": "Poor",
                                    "skill": "clarity",
                                    "reason": "The response was very brief and did not provide any context or detail, making it difficult to assess your understanding of the topic."
                                },
                                {
                                    "level": "Poor",
                                    "skill": "engagement",
                                    "reason": "The lack of a detailed response suggests a low level of engagement with the question, which may indicate a lack of preparation or interest in the subject matter."
                                }
                            ]
                        }
                    },
                    "user_type": "assistant",
                    "content_type": "question"
                }
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "i_persona_session": {
                "data": {
                    "id": "24"
                }
            }
        }
    }
]

In [ ]:
def time_to_seconds(time_str):
    """Convert time in 'HH:MM' format to seconds."""
    if time_str in ["00:00", ""]:  # Check for both zero and empty string
        return 0
    h, m = map(int, time_str.split(':'))
    return h * 3600 + m * 60

def calculate_time(interview: list) -> dict:
    try:
        exceeded_count = 0
        not_exceeded_count = 0
        
        for i in range(len(interview)):
            if interview[i]["attributes"]["attributes"]["message"]['user_type'] == 'assistant':
                assistant_response = interview[i]["attributes"]["attributes"]["message"]['content']
                
                if assistant_response and 'time_limit' in assistant_response:
                    time_limit = assistant_response['time_limit']
                    
                    if not time_limit or time_limit == '':
                        continue  

                    time_limit_seconds = time_to_seconds(time_limit)
                    
                    if i + 1 < len(interview) and interview[i + 1]["attributes"]["attributes"]["message"]['user_type'] == 'candidate':
                        time_taken = interview[i + 1]["attributes"]["attributes"]["message"]['content'].get('time_taken', '')  

                        if not time_taken or time_taken == '':
                            continue  

                        time_taken_seconds = time_to_seconds(time_taken)

                        if time_taken_seconds > time_limit_seconds:
                            exceeded_count += 1
                        else:
                            not_exceeded_count += 1
        
        time_data = {
            "fail": exceeded_count,
            "pass": not_exceeded_count
        }
        return time_data
    
    except Exception as e:
        print(f"Calculating overall time failed: {str(e)}")

        return {'error': str(e)}

calculate_time(data)

{'fail': 0, 'pass': 7}

In [19]:
def filter_the_relevancies(data: list) -> dict:
    try:
        relevancy = []
        index_counter = 1
        
        for entry in data:
            if entry["attributes"]["attributes"]["message"]['user_type'] == 'assistant' and 'realtime_evaluation' in entry["attributes"]["attributes"]["message"]['content']:
                evaluation = entry["attributes"]["attributes"]["message"]['content']['realtime_evaluation']
                if 'answer_relevancy' in evaluation:
                    for relevance in evaluation['answer_relevancy']:
                        relevance_with_index = {
                            "question_no": index_counter,  
                            "level": relevance['level'],
                            "reason": relevance['reason']
                        }
                        relevancy.append(relevance_with_index)
                        index_counter += 1 
                        
        levels = [int(item["level"]) for item in relevancy]
        average_relevancy = sum(levels) / len(levels) if levels else 0
        
        data = {
            "relevancy": relevancy,
            "average": average_relevancy
        }
        return data
    
    except Exception as e:
        print(f"Filtering overall relevance process failed: ${str(e)}")
        return {'error': str(e)}
    
relevancy = filter_the_relevancies(data)
relevancy

{'relevancy': [{'question_no': 1,
   'level': '30',
   'reason': 'The response provided minimal information and did not connect your background to the job requirements or responsibilities.'},
  {'question_no': 2,
   'level': '30',
   'reason': 'The response provided minimal relevant information and did not adequately address the question about how your background specifically prepares you for data science roles.'},
  {'question_no': 3,
   'level': '30',
   'reason': 'The response only addressed the lack of experience with one framework and did not provide any relevant information about other frameworks or related projects.'},
  {'question_no': 4,
   'level': '10',
   'reason': 'The response was too vague and did not address the question about a specific collaborative situation.'},
  {'question_no': 5,
   'level': '10',
   'reason': 'The response did not address the question at all, indicating a significant gap in relevant information.'},
  {'question_no': 6,
   'level': '30',
   'reason': "The response only mentioned 'data cleaning,' which is a very narrow aspect of handling imbalanced datasets and does not encompass the broader strategies that are typically employed."},
  {'question_no': 7,
   'level': '30',
   'reason': 'The response did not provide any relevant information or examples related to the question about data cleaning techniques.'}],
 'average': 24.285714285714285}

In [20]:
def percentage_term(percent: float) -> dict:
    try:
        if not isinstance(percent, (int, float)):
            return {'error': 'Invalid input'}  

        if percent < 0 or percent > 100:
            return {'error': 'Invalid input'}  

        if 90 <= percent <= 100:
            data = {
                "term": "Excellent",
                "rating": 4
            }
            return data
        elif 75 <= percent < 90:
            data = {
                "term": "Satisfactory",
                "rating": 3
            }
            return data
        elif 50 <= percent < 75:
            data = {
                "term": "Good",
                "rating": 2
            }
            return data
        else:
            data = {
                "term": "Poor",
                "rating": 1
            }
            return data
        
    except Exception as e:
        print(f"Percentage term assignation process failed: ${str(e)}")

        return {'error': str(e)}
    
percentage_term(relevancy["average"])

{'term': 'Poor', 'rating': 1}

In [1]:
interviews = [
            {
                "rating": 1,
                "strength": [],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked relevant information about educational qualifications and their application to data science and NLP.",
                    "question_no": 1
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked relevant information regarding a specific project and did not address the challenges faced.",
                    "question_no": 2
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information about machine learning frameworks.",
                    "question_no": 3
                  },
                  {
                    "level": "40",
                    "reason": "The response lacked specific details about relevant skills or experiences, making it difficult to assess your fit for the role.",
                    "question_no": 4
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant information or context related to the question about collaboration.",
                    "question_no": 5
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant details or examples.",
                    "question_no": 6
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information about exploratory data analysis.",
                    "question_no": 7
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by vague responses and minimal engagement."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8
                },
                "areas_of_improvement": [
                  {
                    "skill": "Communication Skills",
                    "description": "You need to improve clarity and engagement in your responses. Many answers were vague and did not provide specific details or context, making it difficult to assess your qualifications. Practice articulating your thoughts more clearly and providing concrete examples to support your claims."
                  },
                  {
                    "skill": "Technical Skills in NLP and Machine Learning",
                    "description": "You should enhance your ability to discuss specific projects and experiences related to NLP and machine learning frameworks. Your responses lacked relevant information about your hands-on experience with tools like TensorFlow or PyTorch, which are crucial for the Data Scientist (NLP) role."
                  }
                ],
                "communication_skills": [
                      {
                          "level": "Good",
                          "skill": "clarity",
                          "reason": "The response was clear in stating your background, but it was too brief to provide a comprehensive understanding."
                      },
                      {
                          "level": "Poor",
                          "skill": "engagement",
                          "reason": "The response lacked enthusiasm and did not engage with the question in a meaningful way."
                      }
                ],
                "competency": [
                      {
                        "name": "Data Analysis",
                        "sfia_level": "2"
                      },
                      {
                        "name": "Machine Learning",
                        "sfia_level": "2"
                      },
                      {
                        "name": "NLP Techniques",
                        "sfia_level": "1"
                      }
                ],
                "overall_performance_score": 21.428571428571427,
                "createdAt": "2024-11-12T16:19:17.056Z"
            },
            {
                "rating": 1,
                "strength": [],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked relevant information regarding educational qualifications and their application to data science and NLP.",
                    "question_no": 1
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked specific examples and details related to the question about machine learning and NLP projects.",
                    "question_no": 2
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any details about experience with machine learning frameworks.",
                    "question_no": 3
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked specific details about relevant skills or experiences that align with the job description.",
                    "question_no": 4
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant content or context related to the question about collaboration in a technical project.",
                    "question_no": 5
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information or examples.",
                    "question_no": 6
                  },
                  {
                    "level": "10",
                    "reason": "The response lacks any relevant information or context related to the question asked.",
                    "question_no": 7
                  },
                  {
                    "level": "20",
                    "reason": "The answer provided does not relate to the question asked, which was seeking clarification on the meaning of '6'.",
                    "question_no": 8
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by vague responses and a lack of engagement with the questions asked."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your ability to articulate specific technical skills and experiences relevant to the Data Scientist (NLP) role. For instance, when asked about your experience with machine learning frameworks like TensorFlow or PyTorch, your responses were vague and did not provide concrete examples of projects or challenges faced."
                  },
                  {
                    "skill": "Communication Skills",
                    "description": "You should work on providing clearer and more detailed responses. Many of your answers lacked clarity and engagement, which made it difficult to understand your qualifications and experiences. Practicing structured responses that directly address the questions asked would be beneficial."
                  }
                ],
                "communication_skills": [
                    {
                        "level": "Good",
                        "skill": "clarity",
                        "reason": "The response was clear in stating your background, but it was too brief to provide a comprehensive understanding."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "The response lacked enthusiasm and did not engage with the question in a meaningful way."
                    }
                ],
                "competency": [
                      {
                        "name": "Data Analysis",
                        "sfia_level": "2"
                      },
                      {
                        "name": "Machine Learning",
                        "sfia_level": "2"
                      },
                      {
                        "name": "NLP Techniques",
                        "sfia_level": "1"
                      }
                ],
                "overall_performance_score": 31,
                "createdAt": "2024-11-12T16:19:17.056Z"
            },
            {
                "rating": 1,
                "strength": [],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked relevant information regarding educational qualifications and their application to data science and NLP.",
                    "question_no": 1
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant information or context related to machine learning or NLP projects.",
                    "question_no": 2
                  },
                  {
                    "level": "30",
                    "reason": "The response did not address the question at all, lacking any relevant information about machine learning frameworks.",
                    "question_no": 3
                  },
                  {
                    "level": "40",
                    "reason": "The response lacked specific details about relevant skills or experiences, making it difficult to assess fit for the role.",
                    "question_no": 4
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant content related to the question about collaboration, making it difficult to assess your experience in teamwork.",
                    "question_no": 5
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information or examples.",
                    "question_no": 6
                  },
                  {
                    "level": "10",
                    "reason": "The response provided no relevant information related to the question about handling imbalanced datasets.",
                    "question_no": 7
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by vague responses and a lack of specific examples."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your ability to articulate your experience with machine learning frameworks like TensorFlow and PyTorch. Providing specific examples from your projects would demonstrate your practical knowledge and problem-solving abilities."
                  },
                  {
                    "skill": "Communication Skills",
                    "description": "You should work on clarity and engagement in your responses. Many of your answers were vague and lacked enthusiasm, which made it difficult to assess your interest in the role."
                  },
                  {
                    "skill": "Project Experience",
                    "description": "You need to provide detailed descriptions of your projects, particularly those related to NLP and data modeling. This will help illustrate your qualifications and fit for the Data Scientist (NLP) role."
                  }
                ],
                "communication_skills": [
                    {
                        "level": "Good",
                        "skill": "clarity",
                        "reason": "The response was clear in stating your background, but it was too brief to provide a comprehensive understanding."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "The response lacked enthusiasm and did not engage with the question in a meaningful way."
                    }
                ],
                "competency": [
                      {
                        "name": "Data Analysis",
                        "sfia_level": "2"
                      },
                      {
                        "name": "Machine Learning",
                        "sfia_level": "2"
                      },
                      {
                        "name": "NLP Techniques",
                        "sfia_level": "1"
                      }
                ],
                "overall_performance_score": 40,
                "createdAt": "2024-11-12T16:19:17.056Z"
            },
            {
                "rating": 1,
                "strength": [],
                "relevancy": [
                  {
                    "level": "40",
                    "reason": "The response provided minimal relevant information about educational experiences related to data science and NLP.",
                    "question_no": 1
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked relevant content related to the question about a specific project involving machine learning and NLP.",
                    "question_no": 2
                  },
                  {
                    "level": "30",
                    "reason": "The response did not address the question at all, indicating a lack of relevant experience or preparation.",
                    "question_no": 3
                  },
                  {
                    "level": "40",
                    "reason": "The response lacked specific details or examples that directly relate to the required qualifications and responsibilities of the role.",
                    "question_no": 4
                  },
                  {
                    "level": "10",
                    "reason": "The response lacked any relevant content related to the question about collaboration and teamwork.",
                    "question_no": 5
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant details or examples.",
                    "question_no": 6
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, providing no relevant information.",
                    "question_no": 7
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Good",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by vague responses and minimal engagement with the questions asked."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills in NLP and Machine Learning",
                    "description": "You need to improve your ability to articulate specific experiences and projects related to NLP and machine learning frameworks. For instance, when asked about your experience with TensorFlow or PyTorch, your responses lacked detail and did not demonstrate a clear understanding of how you applied these tools in your projects."
                  },
                  {
                    "skill": "Communication Skills",
                    "description": "You should work on providing clearer and more detailed responses. Many of your answers were vague and did not effectively convey your qualifications or experiences relevant to the Data Scientist (NLP) role. Practicing structured responses and elaborating on your experiences will help improve this."
                  }
                ],
                "communication_skills": [
                    {
                        "level": "Good",
                        "skill": "clarity",
                        "reason": "The response was clear in stating your background, but it was too brief to provide a comprehensive understanding."
                    },
                    {
                        "level": "Poor",
                        "skill": "engagement",
                        "reason": "The response lacked enthusiasm and did not engage with the question in a meaningful way."
                    }
                ],
                "competency": [
                      {
                        "name": "Data Analysis",
                        "sfia_level": "2"
                      },
                      {
                        "name": "Machine Learning",
                        "sfia_level": "2"
                      },
                      {
                        "name": "NLP Techniques",
                        "sfia_level": "1"
                      }
                ],
                "overall_performance_score": 50,
                "createdAt": "2024-11-12T16:19:17.056Z"

            }
            
]

In [2]:
def restructure_communication_skills_for_vis(data):
    try:
        transformed_data = []
        for i, interview in enumerate(data, start=1):
            interview_name = f"Interview {i}"
            for target, value in interview.items():
                transformed_data.append({
                    "source": interview_name,
                    "target": target.lower(), 
                    "value": value
                })
                
        return transformed_data
    except Exception as e:
        print(f"Response restructring process failed: ${str(e)}")

        return {'error': str(e)}
    
def extract_necessary_metrics(data: list):
    try:   
        overall_time_management = []
        overall_competency = []
        overall_performance = []
        
        for index, dataset in enumerate(data): 
            for entry in dataset['chathistory']: 
                if "assistant" in entry:
                    assistant_eval = entry["assistant"]                
                    if "metrics" in assistant_eval:
                        metrics = assistant_eval["metrics"]
                        if isinstance(metrics, dict):
                            time = metrics.get("time_management", [])
                            overall_time_management.append(time)
                            
                    if "overall_evaluation" in assistant_eval:
                        overall_evaluation = assistant_eval["overall_evaluation"]
                        if "competency" in overall_evaluation:
                            competency = overall_evaluation["competency"]
                            overall_competency.append(competency)
                        if isinstance(overall_evaluation, dict):                            
                            overall_eval_performance = overall_evaluation.get("overall_performance")
                            performance = {
                                "interview": index,
                                "performance": overall_eval_performance
                            }
                            overall_performance.append(performance)
        
        # Restructuring time management data
        time_management = restructure_communication_skills_for_vis(overall_time_management)

        response = {
            "overall_time_management": time_management,
            "overall_competency": overall_competency,
            "overall_performance": overall_performance
        }    
        
        return response  
    
    except Exception as e:
        print(f"Response restructring process failed: ${str(e)}")
        return {'error': str(e)}

from datetime import datetime

def convert_iso_to_readable_format(iso_time):
    dt = datetime.strptime(iso_time, '%Y-%m-%dT%H:%M:%S.%fZ')    
    readable_time = dt.strftime('%d %b %Y %I:%M %p')
    return readable_time

iso_time = '2024-11-12T16:19:17.056Z'
chart_friendly_time = convert_iso_to_readable_format(iso_time)
print(chart_friendly_time)

12 Nov 2024 04:19 PM

In [4]:
links = [{'fail': 0, 'pass': 8}, {'fail': 0, 'pass': 8}]
restructure_communication_skills_for_vis(links)

[{'source': 'Interview 1', 'target': 'fail', 'value': 0},
 {'source': 'Interview 1', 'target': 'pass', 'value': 8},
 {'source': 'Interview 2', 'target': 'fail', 'value': 0},
 {'source': 'Interview 2', 'target': 'pass', 'value': 8}]

In [ ]:
def calculate_overall_progress(data: list) -> dict:
    try:
        confidence_overtime = []  
        clarity_overtime = []     
        engagement_overtime = [] 
        overall_time_managements = []
        overall_competencies = []
        overall_performance_scores = []
        session_ids = [] 
        

        for entry in data:
            iso_time = entry.get("createdAt", "")
            # print("cmai liv", iso_time)
            created_time = convert_iso_to_readable_format(iso_time)
            performance = entry.get("performance", [])
            realtime = entry.get('communication_skills', []) 
            time = entry.get('time_management', {})
            competency = entry.get('competency', [])
            overall_performance_score = entry.get("overall_performance_score", "")
            obs_id = entry.get("obs_id")  
            if obs_id:
                session_ids.append(obs_id)  
            obj_time = {
                "time": created_time,
                "time_management": time
            }
            overall_time_managements.append(obj_time)
            obj_competency = {
                "time": created_time,
                "competency": competency
            }
            overall_competencies.append(obj_competency)   
            obj_score = {
                "time": created_time,
                "score": overall_performance_score
            }
            overall_performance_scores.append(obj_score)   
             
            if isinstance(performance, list):
                for item in performance:
                    confidence_level = item.get('level', '').lower()
                    if(confidence_level == 'poor'):
                            value = 1
                    elif(confidence_level == 'good'):
                        value = 2
                    elif(confidence_level == 'excellent'):
                        value = 3
                    confidence = {"time": created_time, "level": confidence_level, "value": value}
                    confidence_overtime.append(confidence)                        
           
            if isinstance(realtime, list):
                for communication in realtime:  
                    if communication.get('skill') == "clarity":  
                        clarity_level = communication['level'].lower() 
                        if(clarity_level == 'poor'):
                            value = 1
                        elif(clarity_level == 'good'):
                            value = 2
                        elif(clarity_level == 'excellent'):
                            value = 3
                        clarity = {"time": created_time, "level": clarity_level, "value": value}
                        clarity_overtime.append(clarity)

                    if communication.get('skill') == "engagement":  
                        engagement_level = communication['level'].lower()  
                        if(engagement_level == 'poor'):
                            value = 1
                        elif(engagement_level == 'good'):
                            value = 2
                        elif(engagement_level == 'excellent'):
                            value = 3
                        engagement = {"time": created_time, "level": engagement_level, "value": value}
                        engagement_overtime.append(engagement)
      
        response = {
            "overall_confidence": confidence_overtime,
            "overall_clarity": clarity_overtime,
            "overall_engagement": engagement_overtime,
            "overall_time_management": overall_time_managements,
            "overall_competency": overall_competencies,
            "overall_performance": overall_performance_scores
        }
        
        message_data = {
            "attributes": {
                "overall_confidence": confidence_overtime,
                "overall_clarity": clarity_overtime,
                "overall_engagement": engagement_overtime,
                "overall_time_management": overall_time_managements,
                "overall_competency": overall_competencies,
                "overall_performance": overall_performance_scores
            },
            "metadata": {
                "createdBy": "parrot"
            },
            "jobprofileId": 1080,   # Static job profile ID
            "alluserId": 187,       # Static all user ID
            "sessionIds": session_ids  # Dynamic session IDs collected from obs_id
        }
        return message_data
    
    except Exception as e:
        print(f"Calculating overall progress process failed: {str(e)}")
        return {'error': str(e)}
response = calculate_overall_progress(data)
response

{'attributes': {'overall_confidence': [{'time': '2024-11-28 13:52:53',
    'level': 'poor',
    'value': 1},
   {'time': '2024-11-28 11:12:36', 'level': 'poor', 'value': 1},
   {'time': '2024-11-27 14:14:20', 'level': 'poor', 'value': 1},
   {'time': '2024-11-27 12:12:43', 'level': 'poor', 'value': 1},
   {'time': '2024-11-27 07:30:35', 'level': 'poor', 'value': 1},
   {'time': '2024-11-27 07:24:27', 'level': 'poor', 'value': 1},
   {'time': '2024-11-27 07:06:06', 'level': 'poor', 'value': 1},
   {'time': '2024-11-20 10:22:08', 'level': 'poor', 'value': 1},
   {'time': '2024-11-20 10:05:36', 'level': 'poor', 'value': 1},
   {'time': '2024-11-20 09:23:13', 'level': 'poor', 'value': 1},
   {'time': '2024-11-15 14:37:04', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 18:29:01', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 16:51:43', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 05:16:16', 'level': 'good', 'value': 2},
   {'time': '2024-11-14 04:47:02', 'level': 'poor', 'value': 1}],
  'overall_clarity': [{'time': '2024-11-20 10:22:08',
    'level': 'poor',
    'value': 1},
   {'time': '2024-11-20 10:05:36', 'level': 'poor', 'value': 1},
   {'time': '2024-11-20 09:23:13', 'level': 'poor', 'value': 1},
   {'time': '2024-11-15 14:37:04', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 18:29:01', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 16:51:43', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 05:16:16', 'level': 'good', 'value': 2},
   {'time': '2024-11-14 04:47:02', 'level': 'poor', 'value': 1}],
  'overall_engagement': [{'time': '2024-11-20 10:22:08',
    'level': 'poor',
    'value': 1},
   {'time': '2024-11-20 10:05:36', 'level': 'poor', 'value': 1},
   {'time': '2024-11-20 09:23:13', 'level': 'poor', 'value': 1},
   {'time': '2024-11-15 14:37:04', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 18:29:01', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 16:51:43', 'level': 'poor', 'value': 1},
   {'time': '2024-11-14 05:16:16', 'level': 'good', 'value': 2},
   {'time': '2024-11-14 04:47:02', 'level': 'poor', 'value': 1}],
  'overall_time_management': [{'time': '2024-11-28 13:52:53',
    'time_management': {'fail': 0,
     'pass': 8,
     'total_time_taken_by_candidate': '00:55:00'}},
   {'time': '2024-11-28 11:12:36',
    'time_management': {'fail': 0,
     'pass': 8,
     'total_time_taken_by_candidate': '00:48:00'}},
   {'time': '2024-11-27 14:14:20',
    'time_management': {'fail': 0,
     'pass': 8,
     'total_time_taken_by_candidate': '01:08:00'}},
   {'time': '2024-11-27 12:12:43',
    'time_management': {'fail': 0,
     'pass': 8,
     'total_time_taken_by_candidate': '00:39:00'}},
   {'time': '2024-11-27 07:30:35',
    'time_management': {'fail': 0,
     'pass': 8,
     'total_time_taken_by_candidate': '01:05:00'}},
   {'time': '2024-11-27 07:24:27',
    'time_management': {'fail': 0,
     'pass': 8,
     'total_time_taken_by_candidate': '00:31:00'}},
   {'time': '2024-11-27 07:06:06', 'time_management': {'fail': 2, 'pass': 6}},
   {'time': '2024-11-20 10:22:08', 'time_management': {'fail': 0, 'pass': 3}},
   {'time': '2024-11-20 10:05:36', 'time_management': {'fail': 0, 'pass': 5}},
   {'time': '2024-11-20 09:23:13', 'time_management': {'fail': 1, 'pass': 3}},
   {'time': '2024-11-15 14:37:04', 'time_management': {'fail': 1, 'pass': 7}},
   {'time': '2024-11-14 18:29:01', 'time_management': {'fail': 1, 'pass': 7}},
   {'time': '2024-11-14 16:51:43', 'time_management': {'fail': 0, 'pass': 8}},
   {'time': '2024-11-14 05:16:16', 'time_management': {'fail': 0, 'pass': 8}},
   {'time': '2024-11-14 04:47:02', 'time_management': {'fail': 0, 'pass': 8}}],
  'overall_competency': [{'time': '2024-11-28 13:52:53',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'Communication Skills', 'sfia_level': '1'}]},
   {'time': '2024-11-28 11:12:36',
    'competency': [{'name': 'Machine Learning', 'sfia_level': '3'},
     {'name': 'Computer Vision', 'sfia_level': '2'},
     {'name': 'Collaboration and Teamwork', 'sfia_level': '2'}]},
   {'time': '2024-11-27 14:14:20',
    'competency': [{'name': 'Machine Learning', 'sfia_level': '3'},
     {'name': 'Computer Vision', 'sfia_level': '3'},
     {'name': 'Collaboration', 'sfia_level': '2'}]},
   {'time': '2024-11-27 12:12:43',
    'competency': [{'name': 'Machine Learning', 'sfia_level': '3'},
     {'name': 'Computer Vision', 'sfia_level': '2'},
     {'name': 'Collaboration and Teamwork', 'sfia_level': '2'}]},
   {'time': '2024-11-27 07:30:35',
    'competency': [{'name': 'Machine Learning', 'sfia_level': '3'},
     {'name': 'Collaboration', 'sfia_level': '2'},
     {'name': 'Problem Solving', 'sfia_level': '2'}]},
   {'time': '2024-11-27 07:24:27',
    'competency': [{'name': 'Machine Learning', 'sfia_level': '2'},
     {'name': 'Problem Solving', 'sfia_level': '2'},
     {'name': 'Communication Skills', 'sfia_level': '1'}]},
   {'time': '2024-11-27 07:06:06',
    'competency': [{'name': 'Machine Learning', 'sfia_level': '3'},
     {'name': 'Problem Solving', 'sfia_level': '2'},
     {'name': 'Collaboration', 'sfia_level': '2'}]},
   {'time': '2024-11-20 10:22:08',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '2'},
     {'name': 'Machine Learning', 'sfia_level': '2'},
     {'name': 'NLP Techniques', 'sfia_level': '1'}]},
   {'time': '2024-11-20 10:05:36',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'Communication', 'sfia_level': '1'}]},
   {'time': '2024-11-20 09:23:13',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'Communication Skills', 'sfia_level': '1'}]},
   {'time': '2024-11-15 14:37:04',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '2'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'Natural Language Processing', 'sfia_level': '1'}]},
   {'time': '2024-11-14 18:29:01',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'NLP Techniques', 'sfia_level': '1'}]},
   {'time': '2024-11-14 16:51:43',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'Team Collaboration', 'sfia_level': '1'}]},
   {'time': '2024-11-14 05:16:16',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '4'},
     {'name': 'Machine Learning', 'sfia_level': '4'},
     {'name': 'Collaboration', 'sfia_level': '3'}]},
   {'time': '2024-11-14 04:47:02',
    'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
     {'name': 'Machine Learning', 'sfia_level': '1'},
     {'name': 'Collaboration', 'sfia_level': '1'}]}],
  'overall_performance': [{'time': '2024-11-28 13:52:53', 'score': 20},
   {'time': '2024-11-28 11:12:36', 'score': 29.29},
   {'time': '2024-11-27 14:14:20', 'score': 58.57},
   {'time': '2024-11-27 12:12:43', 'score': 29.29},
   {'time': '2024-11-27 07:30:35', 'score': 36.43},
   {'time': '2024-11-27 07:24:27', 'score': 25.71},
   {'time': '2024-11-27 07:06:06', 'score': 48.57},
   {'time': '2024-11-20 10:22:08', 'score': 30},
   {'time': '2024-11-20 10:05:36', 'score': 2.5},
   {'time': '2024-11-20 09:23:13', 'score': 15},
   {'time': '2024-11-15 14:37:04', 'score': 17.86},
   {'time': '2024-11-14 18:29:01', 'score': 18.57},
   {'time': '2024-11-14 16:51:43', 'score': 4.29},
   {'time': '2024-11-14 05:16:16', 'score': 90},
   {'time': '2024-11-14 04:47:02', 'score': 18.57}]},
 'metadata': {'createdBy': 'parrot'},
 'jobprofileId': 1080,
 'alluserId': 187,
 'sessionIds': ['106',
  '105',
  '103',
  '102',
  '101',
  '100',
  '96',
  '65',
  '64',
  '58',
  '43',
  '42',
  '41',
  '36',
  '35']}

User all jobs sesstion observer

Average Scale Standard for GOOD, POOR, EXCELLENT
  - 1.00 - 1.49(Poor)  
  - 1.50 - 1.99(Between Poor and Good)  
  - 2.00 - 2.49(Good) 
  - 2.50 - 2.99(Between Good and Excellent) 
  - 3.00(Excellent)

In [4]:
#response = calculate_overall_progress(interviews)

def calculate_average_confidence(data):
    total_score = 0
    count = 0
    
    for entry in data:
        value = entry.get("value", 0)          
        total_score += value 
        count += 1 
    
    average_confidence = total_score / count if count > 0 else 0
    return average_confidence
avg_confidence = calculate_average_confidence(response['overall_confidence'])
avg_clarity = calculate_average_confidence(response['overall_clarity'])
avg_engagment = calculate_average_confidence(response['overall_engagement'])
print(avg_confidence)

1.25

In [20]:
def calculate_average_time_management(data):
    total_passes = 0
    total_fails = 0
    
    for entry in data:
        time_management = entry.get("time_management", {})
        passes = time_management.get("pass", 0)  
        fails = time_management.get("fail", 0)    
        
        total_passes += passes  
        total_fails += fails     
    
    total_questions = total_passes + total_fails
    average_pass_rate = (total_passes / total_questions) * 100 if total_questions > 0 else 0
    average_fail_rate = (total_fails / total_questions) * 100 if total_questions > 0 else 0

    return {
        "total_passes": total_passes,
        "total_fails": total_fails,
        "average_pass_rate": average_pass_rate,
        "average_fail_rate": average_fail_rate
    }

result = calculate_average_time_management(response['overall_time_management'])
print(f"Time Managment: {result}")

Time Managment: {'total_passes': 32, 'total_fails': 0, 'average_pass_rate': 100.0, 'average_fail_rate': 0.0}

In [ ]:
# print(confidence_overtime)  
            
        
        # result = extract_necessary_metrics(data)   
        # response = {
        #     "overall_confidence": confidence_overtime,
        #     "overall_clarity": clarity,
        #     "overall_engagement": engagement,
        #     "overall_time_management": result["overall_time_management"],
        #     "overall_competency": result["overall_competency"],
        #     "overall_performance": result["overall_performance"]
        # }
        # return response
        
# if isinstance(realtime, dict):
#         for communication in realtime.get("communication_skills", []):                            
#                 if isinstance(communication, dict):
#                 # Count overall clarity
#                 if communication.get('skill') == "clarity":  
#                         clarity_level = communication['level'].lower()  
#                         if clarity_level in clarity_count:
#                         clarity_count[clarity_level] += 1

#                 # Count overall engagement
#                 if communication.get('skill') == "engagement":  
#                         engagement_level = communication['level'].lower()  
#                         if engagement_level in engagement_count:
#                         engagement_count[engagement_level] += 1

In [7]:
# Sample data
data = [
 {
    "attributes": {
      "attributes": {
        "interview_evaluation": {
          "message": "Poor",
          "competency": [
            {
              "name": "Data Analysis",
              "sfia_level": "3"
            },
            {
              "name": "Machine Learning",
              "sfia_level": "3"
            },
            {
              "name": "NLP Techniques",
              "sfia_level": "3"
            }
          ],
          "evaluation": "Your performance in the interview demonstrates a solid understanding of machine learning and NLP concepts, particularly through your projects involving LLM fine-tuning and automated solutions. However, there are areas where you can enhance your skills, especially in data modeling and statistical analysis, which are crucial for the Data Scientist (NLP) role. Your enthusiasm for continuous improvement and innovation is commendable, but you should focus on articulating your experiences more clearly and aligning them with the specific requirements of the job description.",
          "recommendation": [
            {
              "link": "https://www.coursera.org/specializations/jhu-data-science",
              "type": "Online Course",
              "title": "Data Modeling and Statistical Analysis",
              "resource": "Data Science Specialization by Johns Hopkins University on Coursera, which covers data modeling and statistical analysis techniques."
            },
            {
              "link": "https://www.coursera.org/specializations/deep-learning",
              "type": "Online Course",
              "title": "Deep Learning Specialization",
              "resource": "Deep Learning Specialization by Andrew Ng on Coursera, focusing on deep learning architectures and their applications."
            },
            {
              "link": "http://www.nltk.org/book/",
              "type": "Book",
              "title": "NLP with Python",
              "resource": "Natural Language Processing with Python by Steven Bird, Ewan Klein, and Edward Loper, which provides practical insights into NLP techniques."
            }
          ],
          "overall_performance": 0
        },
        "interview_evaluation_metrics": {
          "rating": 1,
          "message": "Poor",
          "strength": [
            {
              "skill": "Problem-Solving",
              "description": "You demonstrated strong problem-solving skills, particularly when discussing your project on automated storyboard synthesis. You effectively explained how you utilized advanced deep learning frameworks to streamline the ad creation process, showcasing your ability to tackle complex challenges."
            }
          ],
          "relevancy": [],
          "performance": [
            {
              "name": "confidence_level",
              "level": "Good",
              "reason": "You showed a solid level of confidence during the interview, articulating your thoughts clearly. However, there were moments of hesitation when discussing specific technical skills, which slightly affected your overall assertiveness."
            }
          ],
          "time_management": {
            "fail": 0,
            "pass": 0
          },
          "areas_of_improvement": [
            {
              "skill": "Technical Skills",
              "description": "You need to enhance your understanding of complex data models and machine learning frameworks. During the interview, you struggled to explain your experience with NLP techniques and deep learning architectures, which are crucial for the Data Scientist (NLP) role. To improve, consider engaging in more hands-on projects or online courses that focus specifically on these areas."
            }
          ]
        }
      },
      "metadata": {
        "createdBy": "parrot"
      }
    }
  },
  {
    "attributes": {
      "attributes": {
        "interview_evaluation": {
          "message": "Poor",
          "competency": [
            {
              "name": "Data Analysis",
              "sfia_level": "3"
            },
            {
              "name": "Machine Learning",
              "sfia_level": "3"
            },
            {
              "name": "NLP Techniques",
              "sfia_level": "3"
            }
          ],
          "evaluation": "Your performance in the interview demonstrates a solid understanding of machine learning and NLP concepts, particularly through your projects involving LLM fine-tuning and automated solutions. However, there are areas where you can enhance your skills, especially in data modeling and statistical analysis, which are crucial for the Data Scientist (NLP) role. Your enthusiasm for continuous improvement and innovation is commendable, but you should focus on articulating your experiences more clearly and aligning them with the specific requirements of the job description.",
          "recommendation": [
            {
              "link": "https://www.coursera.org/specializations/jhu-data-science",
              "type": "Online Course",
              "title": "Data Modeling and Statistical Analysis",
              "resource": "Data Science Specialization by Johns Hopkins University on Coursera, which covers data modeling and statistical analysis techniques."
            },
            {
              "link": "https://www.coursera.org/specializations/deep-learning",
              "type": "Online Course",
              "title": "Deep Learning Specialization",
              "resource": "Deep Learning Specialization by Andrew Ng on Coursera, focusing on deep learning architectures and their applications."
            },
            {
              "link": "http://www.nltk.org/book/",
              "type": "Book",
              "title": "NLP with Python",
              "resource": "Natural Language Processing with Python by Steven Bird, Ewan Klein, and Edward Loper, which provides practical insights into NLP techniques."
            }
          ],
          "overall_performance": 0
        },
        "interview_evaluation_metrics": {
          "rating": 1,
          "message": "Poor",
          "strength": [
            {
              "skill": "Problem-Solving",
              "description": "You demonstrated strong problem-solving skills, particularly when discussing your project on automated storyboard synthesis. You effectively explained how you utilized advanced deep learning frameworks to streamline the ad creation process, showcasing your ability to tackle complex challenges."
            }
          ],
          "relevancy": [],
          "performance": [
            {
              "name": "confidence_level",
              "level": "Good",
              "reason": "You showed a solid level of confidence during the interview, articulating your thoughts clearly. However, there were moments of hesitation when discussing specific technical skills, which slightly affected your overall assertiveness."
            }
          ],
          "time_management": {
            "fail": 0,
            "pass": 0
          },
          "areas_of_improvement": [
            {
              "skill": "Technical Skills",
              "description": "You need to enhance your understanding of complex data models and machine learning frameworks. During the interview, you struggled to explain your experience with NLP techniques and deep learning architectures, which are crucial for the Data Scientist (NLP) role. To improve, consider engaging in more hands-on projects or online courses that focus specifically on these areas."
            }
          ]
        }
      },
      "metadata": {
        "createdBy": "parrot"
      }
    }
  }
]

whiteok = []
# Since data is a list, we need to access the first element (index 0)
for item in data:
    message_attributes = item['attributes']['attributes']['interview_evaluation']
    whiteok.append(message_attributes)
# Output the result
print(whiteok)  # This should print: {'name': 'hay'}

[{'message': 'Poor', 'competency': [{'name': 'Data Analysis', 'sfia_level': '3'}, {'name': 'Machine Learning', 'sfia_level': '3'}, {'name': 'NLP Techniques', 'sfia_level': '3'}], 'evaluation': 'Your performance in the interview demonstrates a solid understanding of machine learning and NLP concepts, particularly through your projects involving LLM fine-tuning and automated solutions. However, there are areas where you can enhance your skills, especially in data modeling and statistical analysis, which are crucial for the Data Scientist (NLP) role. Your enthusiasm for continuous improvement and innovation is commendable, but you should focus on articulating your experiences more clearly and aligning them with the specific requirements of the job description.', 'recommendation': [{'link': 'https://www.coursera.org/specializations/jhu-data-science', 'type': 'Online Course', 'title': 'Data Modeling and Statistical Analysis', 'resource': 'Data Science Specialization by Johns Hopkins University on Coursera, which covers data modeling and statistical analysis techniques.'}, {'link': 'https://www.coursera.org/specializations/deep-learning', 'type': 'Online Course', 'title': 'Deep Learning Specialization', 'resource': 'Deep Learning Specialization by Andrew Ng on Coursera, focusing on deep learning architectures and their applications.'}, {'link': 'http://www.nltk.org/book/', 'type': 'Book', 'title': 'NLP with Python', 'resource': 'Natural Language Processing with Python by Steven Bird, Ewan Klein, and Edward Loper, which provides practical insights into NLP techniques.'}], 'overall_performance': 0}, {'message': 'Poor', 'competency': [{'name': 'Data Analysis', 'sfia_level': '3'}, {'name': 'Machine Learning', 'sfia_level': '3'}, {'name': 'NLP Techniques', 'sfia_level': '3'}], 'evaluation': 'Your performance in the interview demonstrates a solid understanding of machine learning and NLP concepts, particularly through your projects involving LLM fine-tuning and automated solutions. However, there are areas where you can enhance your skills, especially in data modeling and statistical analysis, which are crucial for the Data Scientist (NLP) role. Your enthusiasm for continuous improvement and innovation is commendable, but you should focus on articulating your experiences more clearly and aligning them with the specific requirements of the job description.', 'recommendation': [{'link': 'https://www.coursera.org/specializations/jhu-data-science', 'type': 'Online Course', 'title': 'Data Modeling and Statistical Analysis', 'resource': 'Data Science Specialization by Johns Hopkins University on Coursera, which covers data modeling and statistical analysis techniques.'}, {'link': 'https://www.coursera.org/specializations/deep-learning', 'type': 'Online Course', 'title': 'Deep Learning Specialization', 'resource': 'Deep Learning Specialization by Andrew Ng on Coursera, focusing on deep learning architectures and their applications.'}, {'link': 'http://www.nltk.org/book/', 'type': 'Book', 'title': 'NLP with Python', 'resource': 'Natural Language Processing with Python by Steven Bird, Ewan Klein, and Edward Loper, which provides practical insights into NLP techniques.'}], 'overall_performance': 0}]

In [10]:
df = [
  {
    "id": "36",
    "attributes": {
      "slug": "b42f1c84-bc8f-4cab-92b9-afdcdab50415",
      "status": "Complete",
      "createdAt": "one", 
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Excellent",
                "competency": [
                  {
                    "name": "Data Analysis",
                    "sfia_level": "4"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "4"
                  },
                  {
                    "name": "Collaboration",
                    "sfia_level": "3"
                  }
                ],
                "evaluation": "Your performance throughout the interview demonstrates a solid foundation in data science and natural language processing (NLP). You effectively articulated your educational background and relevant projects, showcasing your technical skills and problem-solving abilities. Your responses were well-structured and relevant, particularly in discussing your experience with machine learning frameworks and handling imbalanced datasets. However, there is room for improvement in providing measurable outcomes from your projects and elaborating on your experience with both TensorFlow and PyTorch to present a more balanced skill set.",
                "recommendation": [
                  {
                    "link": "https://www.coursera.org/specializations/deep-learning",
                    "type": "Online Course",
                    "title": "Resources",
                    "resource": "Deep Learning Specialization by Andrew Ng on Coursera, which covers both TensorFlow and PyTorch applications in depth."
                  },
                  {
                    "link": "https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/",
                    "type": "Book",
                    "title": "Books",
                    "resource": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron, which provides practical insights into machine learning and deep learning."
                  },
                  {
                    "link": "https://www.kaggle.com/",
                    "type": "Community",
                    "title": "Community",
                    "resource": "Kaggle, a platform for data science competitions and projects where you can practice your skills and learn from others."
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 4,
                "message": "Excellent",
                "strength": [
                  {
                    "skill": "Problem-Solving",
                    "description": "You demonstrated strong problem-solving skills, particularly when discussing how you addressed class imbalance in your projects. Your use of techniques like SMOTE and data augmentation showed a solid understanding of practical solutions in machine learning."
                  }
                ],
                "relevancy": [
                  {
                    "level": "90",
                    "reason": "All responses were highly relevant to the questions asked, detailing both educational qualifications and specific experiences related to NLP.",
                    "question_no": 1
                  },
                  {
                    "level": "90",
                    "reason": "The response was highly relevant, addressing the project specifics, challenges, and solutions directly related to NLP.",
                    "question_no": 2
                  },
                  {
                    "level": "90",
                    "reason": "The response was highly relevant as it directly addressed the question about experience with machine learning frameworks, specifically TensorFlow, and included a concrete example of its application.",
                    "question_no": 3
                  },
                  {
                    "level": "90",
                    "reason": "The response was highly relevant as it directly addressed the specific challenge faced in the project and outlined the steps taken to resolve it.",
                    "question_no": 4
                  },
                  {
                    "level": "90",
                    "reason": "The response was highly relevant, detailing the collaborative effort, your specific role, and the challenges addressed, though it lacked the final results of the project.",
                    "question_no": 5
                  },
                  {
                    "level": "90",
                    "reason": "All responses were highly relevant to the questions asked, providing specific details about the algorithms and their evaluation.",
                    "question_no": 6
                  },
                  {
                    "level": "90",
                    "reason": "Your response was highly relevant as it directly addressed the question about problem-solving with imbalanced datasets and included a specific example from your experience.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Data Analysis",
                    "sfia_level": "4"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "4"
                  },
                  {
                    "name": "Collaboration",
                    "sfia_level": "3"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Good",
                    "reason": "You displayed a good level of confidence throughout the interview, articulating your experiences and knowledge clearly, though there were moments of hesitation when discussing specific technical details."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You should improve your ability to discuss specific technical frameworks and algorithms in more detail. For instance, while you mentioned using TensorFlow and PyTorch, elaborating on your experience with PyTorch would provide a more balanced view of your skills."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Good",
                    "skill": "clarity",
                    "reason": "Your responses were generally clear and coherent, though some technical explanations could have been more detailed for better understanding."
                  },
                  {
                    "level": "Good",
                    "skill": "engagement",
                    "reason": "You actively participated in the interview and showed enthusiasm for the topics discussed, contributing positively to the overall engagement."
                  }
                ],
                "overall_performance_score": 90
              }
            }
          }
        }
      }
    }
  },
  {
    "id": "35",
    "attributes": {
      "slug": "57c417a9-fb03-4d8b-8149-4e899a59f3fd",
      "status": "Complete",
      "createdAt": "two",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Data Analysis",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Collaboration",
                    "sfia_level": "1"
                  }
                ],
                "evaluation": "Your performance in the interview indicates a significant gap in the required skills and knowledge for the Data Scientist (NLP) role. Responses were often too brief and lacked the necessary detail to demonstrate your qualifications. It is crucial to elaborate on your educational background, relevant projects, and experiences that align with the job description. Additionally, familiarity with key machine learning frameworks and techniques is essential for this position.",
                "recommendation": [
                  {
                    "link": "https://www.coursera.org/learn/machine-learning",
                    "type": "Online Course",
                    "title": "Machine Learning Foundations",
                    "resource": "Coursera's 'Machine Learning' by Andrew Ng"
                  },
                  {
                    "link": "https://www.coursera.org/specializations/natural-language-processing",
                    "type": "Online Course",
                    "title": "Natural Language Processing Specialization",
                    "resource": "Coursera's 'Natural Language Processing' Specialization"
                  },
                  {
                    "link": "https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/",
                    "type": "Book",
                    "title": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
                    "resource": "Book by Aurélien Géron"
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Data Cleaning",
                    "description": "You mentioned data cleaning as part of your process, indicating some understanding of data preprocessing, which is a relevant skill for the role."
                  }
                ],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response only mentioned a computer science background without any details or connections to data science or NLP, making it largely irrelevant to the question.",
                    "question_no": 1
                  },
                  {
                    "level": "10",
                    "reason": "The response did not provide relevant information or context related to the question asked.",
                    "question_no": 2
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, indicating a significant gap in relevant experience.",
                    "question_no": 3
                  },
                  {
                    "level": "30",
                    "reason": "The response only mentioned one tool, which does not fully address the question about preferred tools or technologies for data analysis and modeling tasks.",
                    "question_no": 4
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, indicating no relevant experience or examples of collaboration.",
                    "question_no": 5
                  },
                  {
                    "level": "10",
                    "reason": "The response did not provide any relevant information or examples related to the skills mentioned in the job description.",
                    "question_no": 6
                  },
                  {
                    "level": "30",
                    "reason": "The response provided is only tangentially related to the question, as it does not explain how data cleaning relates to handling imbalanced datasets or what specific strategies were employed.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Data Analysis",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Collaboration",
                    "sfia_level": "1"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, often providing very brief and vague responses that did not adequately address the questions asked."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your familiarity with key machine learning frameworks such as TensorFlow and PyTorch, as well as your understanding of data modeling and NLP techniques. Your responses indicated a lack of experience with these tools, which are critical for the role."
                  },
                  {
                    "skill": "Collaboration",
                    "description": "You should work on providing examples of teamwork and collaboration in your projects. The lack of specific examples during the interview suggested limited experience in working with others on technical projects."
                  },
                  {
                    "skill": "Detail Orientation",
                    "description": "You need to elaborate more on your experiences and projects. Many of your responses were too brief and did not provide sufficient detail, which is essential for demonstrating your qualifications for the role."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many of your responses were difficult to follow and lacked coherence, making it challenging to understand your qualifications and experiences."
                  },
                  {
                    "level": "Poor",
                    "skill": "engagement",
                    "reason": "You did not show much interest or engagement during the interview, which affected the overall impression of your enthusiasm for the role."
                  }
                ],
                "overall_performance_score": 18.57
              }
            },
          }
        }
      }
    }
  }
]

extracted_observers = []
for message in df:
    # Access the 'data' which is a dictionary, not a list
    message_data = message['attributes']['i_persona_observer']['data']
    
    # Access the interview evaluation metrics
    message_attributes = message_data['attributes']['attributes']['interview_evaluation_metrics']
    
    # Get the createdBy metadata
    message_attributes['createdAt'] = message['attributes']['createdAt']
    
  
    # Append the new dictionary to the list
    extracted_observers.append(message_attributes)

# Now extracted_observers contains the interview evaluation metrics along with the createdBy information
extracted_observers

[{'rating': 4,
  'message': 'Excellent',
  'strength': [{'skill': 'Problem-Solving',
    'description': 'You demonstrated strong problem-solving skills, particularly when discussing how you addressed class imbalance in your projects. Your use of techniques like SMOTE and data augmentation showed a solid understanding of practical solutions in machine learning.'}],
  'relevancy': [{'level': '90',
    'reason': 'All responses were highly relevant to the questions asked, detailing both educational qualifications and specific experiences related to NLP.',
    'question_no': 1},
   {'level': '90',
    'reason': 'The response was highly relevant, addressing the project specifics, challenges, and solutions directly related to NLP.',
    'question_no': 2},
   {'level': '90',
    'reason': 'The response was highly relevant as it directly addressed the question about experience with machine learning frameworks, specifically TensorFlow, and included a concrete example of its application.',
    'question_no': 3},
   {'level': '90',
    'reason': 'The response was highly relevant as it directly addressed the specific challenge faced in the project and outlined the steps taken to resolve it.',
    'question_no': 4},
   {'level': '90',
    'reason': 'The response was highly relevant, detailing the collaborative effort, your specific role, and the challenges addressed, though it lacked the final results of the project.',
    'question_no': 5},
   {'level': '90',
    'reason': 'All responses were highly relevant to the questions asked, providing specific details about the algorithms and their evaluation.',
    'question_no': 6},
   {'level': '90',
    'reason': 'Your response was highly relevant as it directly addressed the question about problem-solving with imbalanced datasets and included a specific example from your experience.',
    'question_no': 7}],
  'competency': [{'name': 'Data Analysis', 'sfia_level': '4'},
   {'name': 'Machine Learning', 'sfia_level': '4'},
   {'name': 'Collaboration', 'sfia_level': '3'}],
  'performance': [{'name': 'confidence_level',
    'level': 'Good',
    'reason': 'You displayed a good level of confidence throughout the interview, articulating your experiences and knowledge clearly, though there were moments of hesitation when discussing specific technical details.'}],
  'time_management': {'fail': 0, 'pass': 8},
  'areas_of_improvement': [{'skill': 'Technical Skills',
    'description': 'You should improve your ability to discuss specific technical frameworks and algorithms in more detail. For instance, while you mentioned using TensorFlow and PyTorch, elaborating on your experience with PyTorch would provide a more balanced view of your skills.'}],
  'communication_skills': [{'level': 'Good',
    'skill': 'clarity',
    'reason': 'Your responses were generally clear and coherent, though some technical explanations could have been more detailed for better understanding.'},
   {'level': 'Good',
    'skill': 'engagement',
    'reason': 'You actively participated in the interview and showed enthusiasm for the topics discussed, contributing positively to the overall engagement.'}],
  'overall_performance_score': 90,
  'createdAt': 'one'},
 {'rating': 1,
  'message': 'Poor',
  'strength': [{'skill': 'Data Cleaning',
    'description': 'You mentioned data cleaning as part of your process, indicating some understanding of data preprocessing, which is a relevant skill for the role.'}],
  'relevancy': [{'level': '30',
    'reason': 'The response only mentioned a computer science background without any details or connections to data science or NLP, making it largely irrelevant to the question.',
    'question_no': 1},
   {'level': '10',
    'reason': 'The response did not provide relevant information or context related to the question asked.',
    'question_no': 2},
   {'level': '10',
    'reason': 'The response did not address the question at all, indicating a significant gap in relevant experience.',
    'question_no': 3},
   {'level': '30',
    'reason': 'The response only mentioned one tool, which does not fully address the question about preferred tools or technologies for data analysis and modeling tasks.',
    'question_no': 4},
   {'level': '10',
    'reason': 'The response did not address the question at all, indicating no relevant experience or examples of collaboration.',
    'question_no': 5},
   {'level': '10',
    'reason': 'The response did not provide any relevant information or examples related to the skills mentioned in the job description.',
    'question_no': 6},
   {'level': '30',
    'reason': 'The response provided is only tangentially related to the question, as it does not explain how data cleaning relates to handling imbalanced datasets or what specific strategies were employed.',
    'question_no': 7}],
  'competency': [{'name': 'Data Analysis', 'sfia_level': '1'},
   {'name': 'Machine Learning', 'sfia_level': '1'},
   {'name': 'Collaboration', 'sfia_level': '1'}],
  'performance': [{'name': 'confidence_level',
    'level': 'Poor',
    'reason': 'You appeared unsure and lacked confidence throughout the interview, often providing very brief and vague responses that did not adequately address the questions asked.'}],
  'time_management': {'fail': 0, 'pass': 8},
  'areas_of_improvement': [{'skill': 'Technical Skills',
    'description': 'You need to improve your familiarity with key machine learning frameworks such as TensorFlow and PyTorch, as well as your understanding of data modeling and NLP techniques. Your responses indicated a lack of experience with these tools, which are critical for the role.'},
   {'skill': 'Collaboration',
    'description': 'You should work on providing examples of teamwork and collaboration in your projects. The lack of specific examples during the interview suggested limited experience in working with others on technical projects.'},
   {'skill': 'Detail Orientation',
    'description': 'You need to elaborate more on your experiences and projects. Many of your responses were too brief and did not provide sufficient detail, which is essential for demonstrating your qualifications for the role.'}],
  'communication_skills': [{'level': 'Poor',
    'skill': 'clarity',
    'reason': 'Many of your responses were difficult to follow and lacked coherence, making it challenging to understand your qualifications and experiences.'},
   {'level': 'Poor',
    'skill': 'engagement',
    'reason': 'You did not show much interest or engagement during the interview, which affected the overall impression of your enthusiasm for the role.'}],
  'overall_performance_score': 18.57,
  'createdAt': 'two'}]

In [4]:
#! pip install pandas numpy

In [ ]:
import requests
import json

class StrapiGraphql():
    def __init__(self, **kwargs):          
        self.apiroot = f"http://localhost:1337/graphql" 
        print("Run stage api root ........", self.apiroot)

    def insert_table(self, query, variables):
        """Mutation query to insert data"""
        request = requests.post(self.apiroot, json={'query': query, 'variables': variables})
        if request.status_code == 200:
            r = request.json()
            print("Insert Response: ", r)  # Debugging output
            result_json = json.dumps(r, indent=2)
        else:
            raise Exception(f"Query failed with status code {request.status_code}. {query}")
        
        return result_json

    def select_from_table(self, query, variables=None):
        """Query to select data from the table"""
        if variables is None:
            request = requests.post(self.apiroot, json={'query': query})
        else:
            request = requests.post(self.apiroot, json={'query': query, 'variables': variables})

        if request.status_code == 200:
            r = request.json()
            print("Select Response: ", r)  # Debugging output
            if 'errors' in r:
                raise Exception(f"GraphQL error: {r['errors']}")
            return r['data']  # Return the data directly for easier use
        else:
            raise Exception(f"Query failed with status code {request.status_code}. {query}")

    def update_table(self, query, variables):
        """Mutation query to update data"""
        request = requests.post(self.apiroot, json={'query': query, 'variables': variables})
        if request.status_code == 200:
            r = request.json()
            print("Update Response: ", r)  # Debugging output
            result_json = json.dumps(r, indent=2)
        else:
            raise Exception(f"Query failed with status code {request.status_code}. {query}")
        
        return result_json

    def delete_from_table(self, query, variables):
        """Mutation query to delete data"""
        request = requests.post(self.apiroot, json={'query': query, 'variables': variables})
        if request.status_code == 200:
            r = request.json()
            print("Delete Response: ", r)  # Debugging output
            result_json = json.dumps(r, indent=2)
        else:
            raise Exception(f"Query failed with status code {request.status_code}. {query}")
        
        return result_json


if __name__ == "__main__":
    obj = StrapiGraphql()
    
    query = """
    query GetCategories {
        categories {
            name,
            documentId
        }
    }"""
    
    result = obj.select_from_table(query)
    print("Final Result: ", result)  # Debugging output

time-taken
00:21
time-taken
00:09
time-taken
00:07
final
{'fail': 0, 'pass': 3, 'total_time_taken_by_candidate': '00:00:37'}

{'fail': 0, 'pass': 3, 'total_time_taken_by_candidate': '00:00:37'}

In [19]:
# ! pip install --upgrade library
data = [
  {
    "id": "120",
    "attributes": {
      "status": "Complete",
      "createdAt": "2024-12-01T18:49:27.134Z",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "evaluation": "Your performance in the interview indicates a need for improvement in articulating your experiences and connecting them to the specific requirements of the AI/ML Engineer role in healthcare. While you have relevant skills and experiences, the responses lacked depth and specificity, making it challenging to assess your fit for the position. It is crucial to provide concrete examples that demonstrate your problem-solving abilities, technical expertise, and understanding of healthcare applications.",
                "recommendation": [
                  {
                    "link": "https://www.coursera.org/specializations/deep-learning",
                    "type": "Online Course",
                    "title": "Technical Skills Enhancement",
                    "resource": "Deep Learning Specialization by Andrew Ng on Coursera"
                  },
                  {
                    "link": "https://www.linkedin.com/learning/agile-project-management",
                    "type": "Online Course",
                    "title": "Agile Methodology Training",
                    "resource": "Agile Project Management on LinkedIn Learning"
                  },
                  {
                    "link": "https://www.udemy.com/course/data-science-and-machine-learning-bootcamp-with-r/",
                    "type": "Online Course",
                    "title": "Data Handling and Security",
                    "resource": "Data Science and Machine Learning Bootcamp with R on Udemy"
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Problem-Solving",
                    "description": "You demonstrated a problem-solving mindset in your personal statement, indicating a willingness to tackle complex challenges, although this was not fully reflected in your interview responses."
                  }
                ],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked specific references to educational experiences, coursework, or projects that relate to AI/ML in healthcare, making it difficult to assess its relevance.",
                    "question_no": 1
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked a specific project example and did not adequately address the question about challenges faced and how they were overcome.",
                    "question_no": 2
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked relevant content and did not address the question regarding specific experiences with Python in AI/ML development.",
                    "question_no": 3
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked relevant content and did not address the question about handling large-scale data or ensuring security and scalability.",
                    "question_no": 4
                  },
                  {
                    "level": "10",
                    "reason": "The response lacked any relevant content or details related to the question about working in an Agile team.",
                    "question_no": 5
                  },
                  {
                    "level": "20",
                    "reason": "The response did not address the question at all, lacking any relevant information about experiences or skills related to the AI/ML Engineer role.",
                    "question_no": 6
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant content or context related to the question asked, making it difficult to assess your decision-making abilities.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by your brief and vague responses."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8,
                  "total_time_taken_by_candidate": "00:00:58"
                },
                "areas_of_improvement": [
                  {
                    "skill": "Project Detailing",
                    "description": "You need to improve on providing specific examples and details about your projects, particularly how you faced challenges and the outcomes. This will help demonstrate your problem-solving skills and technical expertise more effectively."
                  },
                  {
                    "skill": "Technical Skills",
                    "description": "You should enhance your ability to articulate your experience with relevant technologies, such as Python and data handling. Providing concrete examples of how you've applied these skills in past projects is crucial."
                  },
                  {
                    "skill": "Agile Methodology",
                    "description": "You need to elaborate on your experiences working within Agile teams. Sharing specific instances of your role and contributions will help illustrate your understanding and effectiveness in such environments."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many of your responses were difficult to follow and lacked coherence, making it challenging to understand your experiences and qualifications."
                  },
                  {
                    "level": "Poor",
                    "skill": "engagement",
                    "reason": "You did not show much interest or enthusiasm during the interview, which affected the overall engagement level."
                  }
                ],
                "overall_performance_score": 24.29
              }
            },
            "metadata": {
              "createdBy": "parrot"
            }
          }
        }
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "121",
    "attributes": {
      "status": "Complete",
      "createdAt": "2024-12-01T20:02:09.723Z",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "3"
                  }
                ],
                "evaluation": "Your performance in the interview indicates a lack of specific examples and details that are crucial for the AI/ML Engineer role, particularly in the healthcare context. While you have a diverse background in software engineering and leadership, the responses provided did not effectively connect your experiences to the competencies required for this position. It is essential to articulate your educational background, relevant projects, and specific skills in a way that demonstrates your fit for the role.",
                "recommendation": [
                  {
                    "link": "www.coursera.org/learn/ai-for-healthcare",
                    "type": "Online Course",
                    "title": "Courses on AI/ML in Healthcare",
                    "resource": "AI for Healthcare: An Introduction to Machine Learning in Healthcare"
                  },
                  {
                    "link": "www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
                    "type": "Online Course",
                    "title": "Python for Data Science and Machine Learning Bootcamp",
                    "resource": "Python for Data Science and Machine Learning Bootcamp"
                  },
                  {
                    "link": "www.udemy.com/course/agile-fundamentals/",
                    "type": "Online Course",
                    "title": "Agile Methodology Training",
                    "resource": "Agile Fundamentals: Including the Scrum Framework"
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Problem-Solving",
                    "description": "You demonstrated a problem-solving mindset by mentioning your experience with developing advanced NLP systems, although specific examples were lacking."
                  }
                ],
                "relevancy": [
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information about educational background or its connection to the role.",
                    "question_no": 1
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked specific examples and details related to handling large-scale data, which is crucial for addressing the question.",
                    "question_no": 2
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information about Python experience or its application in AI/ML.",
                    "question_no": 3
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked relevant content and did not address the question about handling large-scale data or ensuring security and scalability.",
                    "question_no": 4
                  },
                  {
                    "level": "10",
                    "reason": "The response lacked any relevant content or details related to the question asked.",
                    "question_no": 5
                  },
                  {
                    "level": "20",
                    "reason": "The response did not address the question at all, lacking any relevant information about experiences or skills related to the role.",
                    "question_no": 6
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, lacking any relevant content or context.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "3"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by your inability to provide specific examples or details in response to the questions."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8,
                  "total_time_taken_by_candidate": "00:01:57"
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your ability to articulate your technical skills, particularly in Python and AI/ML applications. Focus on providing specific examples of projects where you utilized these skills, including challenges faced and how you overcame them."
                  },
                  {
                    "skill": "Project Experience",
                    "description": "You should enhance your ability to discuss your project experiences in detail. For instance, when asked about handling large-scale data, you did not provide relevant examples or context, which is crucial for demonstrating your expertise."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many of your responses were difficult to follow, lacking coherence and specific details that would help convey your points effectively."
                  },
                  {
                    "level": "Poor",
                    "skill": "engagement",
                    "reason": "You did not show much interest or engagement during the interview, as your responses were often brief and lacked enthusiasm."
                  }
                ],
                "overall_performance_score": 14.29
              }
            },
            "metadata": {
              "createdBy": "parrot"
            }
          }
        }
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "122",
    "attributes": {
      "status": "Complete",
      "createdAt": "2024-12-01T20:07:53.855Z",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Industrialization Algorithms",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Data Processing",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "evaluation": "Your performance in the interview indicates a need for improvement in articulating your experiences and skills relevant to the AI/ML Engineer role in healthcare. While you have a solid background in software engineering and leadership, the responses lacked specific examples and clarity, making it difficult to assess your fit for the position. It is crucial to connect your academic and professional experiences directly to the competencies required for this role, particularly in industrializing algorithms and handling large datasets in healthcare applications.",
                "recommendation": [
                  {
                    "link": "https://www.coursera.org/learn/ai-for-healthcare",
                    "type": "Online Course",
                    "title": "Resources",
                    "resource": "AI for Healthcare: Introduction to Machine Learning in Healthcare"
                  },
                  {
                    "link": "https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/",
                    "type": "Book",
                    "title": "Resources",
                    "resource": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow"
                  },
                  {
                    "link": "https://www.udemy.com/course/data-science-and-machine-learning-bootcamp-with-r/",
                    "type": "Online Course",
                    "title": "Resources",
                    "resource": "Data Science and Machine Learning Bootcamp with R"
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Communication Skill",
                    "description": "You demonstrated a willingness to engage in the conversation, but the lack of detail in your responses hindered the effectiveness of your communication."
                  }
                ],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked specific information about educational experiences and their relevance to the role, making it difficult to assess preparedness for the position.",
                    "question_no": 1
                  },
                  {
                    "level": "30",
                    "reason": "The response did not adequately address the question about a specific project and the challenges faced, leading to a low relevance score.",
                    "question_no": 2
                  },
                  {
                    "level": "30",
                    "reason": "The response did not adequately address the question about experience with industrializing algorithms, lacking specific examples or context.",
                    "question_no": 3
                  },
                  {
                    "level": "40",
                    "reason": "The response lacked specific details about experiences or skills relevant to the AI/ML Engineer role, particularly in healthcare applications.",
                    "question_no": 4
                  },
                  {
                    "level": "5",
                    "reason": "The response did not address the question at all, lacking any relevant information or context.",
                    "question_no": 5
                  },
                  {
                    "level": "20",
                    "reason": "The response did not address the question at all, lacking any relevant information about experiences or skills related to the role.",
                    "question_no": 6
                  },
                  {
                    "level": "0",
                    "reason": "The response provided does not contain any relevant information or context related to the question asked.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Industrialization Algorithms",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Machine Learning",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Data Processing",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by your brief and vague responses."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8,
                  "total_time_taken_by_candidate": "00:01:23"
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your ability to articulate specific technical experiences, particularly in industrializing algorithms and handling large datasets. Providing concrete examples from your past projects would strengthen your responses."
                  },
                  {
                    "skill": "Problem-Solving",
                    "description": "You should work on detailing your problem-solving process when faced with challenges in projects. Sharing specific instances of obstacles and how you overcame them would demonstrate your capability in this area."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many of your responses were difficult to follow due to a lack of specific details and examples."
                  },
                  {
                    "level": "Good",
                    "skill": "engagement",
                    "reason": "You participated in the interview and showed some interest, but your responses lacked enthusiasm and depth."
                  }
                ],
                "overall_performance_score": 22.14
              }
            },
            "metadata": {
              "createdBy": "parrot"
            }
          }
        }
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "123",
    "attributes": {
      "status": "Complete",
      "createdAt": "2024-12-01T20:14:16.917Z",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Healthcare Product/Application Development",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Data Handling and Security",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "evaluation": "Your performance in the interview indicates a significant gap in the required experience for the AI/ML Engineer role, particularly in healthcare product/application development and handling large-scale data. While you possess some relevant skills, the lack of specific examples and detailed responses to the questions posed suggests that you may need to further develop your expertise in these areas to be a strong candidate for this position.",
                "recommendation": [
                  {
                    "link": "www.udemy.com/course/healthcare-software-development",
                    "type": "Online Course",
                    "title": "Healthcare Product Development",
                    "resource": "Consider taking a course on healthcare application development to gain insights into industry-specific requirements and best practices."
                  },
                  {
                    "link": "www.coursera.org/learn/data-security",
                    "type": "Online Course",
                    "title": "Data Handling and Security",
                    "resource": "Look into resources that focus on data security and scalability, especially in the context of AI/ML applications."
                  },
                  {
                    "link": "www.scrum.org",
                    "type": "Workshop",
                    "title": "Agile Methodologies",
                    "resource": "Participate in workshops or training sessions on Agile methodologies to enhance your collaboration and communication skills within self-organizing teams."
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Problem-Solving",
                    "description": "The candidate demonstrated a problem-solving mindset, as indicated by their ability to discuss their approach to developing innovative solutions in their projects."
                  }
                ],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response did not adequately address the question regarding specific experiences in healthcare product/application development, leading to a low relevance score.",
                    "question_no": 1
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked specific examples and details related to handling large-scale data, which is crucial for addressing the question.",
                    "question_no": 2
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, lacking any relevant details or context.",
                    "question_no": 3
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant information or context regarding large-scale data handling, making it difficult to assess your experience in this critical area.",
                    "question_no": 4
                  },
                  {
                    "level": "5",
                    "reason": "The response did not address the question at all, indicating a lack of relevant content.",
                    "question_no": 5
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, providing no relevant information or context.",
                    "question_no": 6
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, providing no relevant information or context.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Healthcare Product/Application Development",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Data Handling and Security",
                    "sfia_level": "1"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "The candidate appeared unsure and lacked confidence, as evidenced by their inability to provide relevant examples and details in response to the questions asked."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8,
                  "total_time_taken_by_candidate": "00:02:44"
                },
                "areas_of_improvement": [
                  {
                    "skill": "Healthcare Product/Application Development",
                    "description": "The candidate should improve their ability to articulate specific experiences in healthcare product/application development. They need to provide concrete examples of projects they have worked on in this area, demonstrating their understanding of healthcare regulations and technologies used."
                  },
                  {
                    "skill": "Handling Large-Scale Data",
                    "description": "The candidate needs to enhance their ability to discuss experiences related to handling large-scale data. They should focus on providing specific examples of projects where they managed large datasets, including the methods used to ensure security and scalability."
                  },
                  {
                    "skill": "Python Proficiency",
                    "description": "The candidate should work on clearly explaining their experience with Python, particularly in the context of developing AI/ML features. They need to provide specific instances where they utilized Python effectively in their projects."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many responses were difficult to follow, lacking coherence and specific details that would help convey their experiences effectively."
                  },
                  {
                    "level": "Poor",
                    "skill": "engagement",
                    "reason": "The candidate did not show interest or engagement during the interview, as evidenced by their brief and unelaborated responses."
                  }
                ],
                "overall_performance_score": 12.14
              }
            },
            "metadata": {
              "createdBy": "parrot"
            }
          }
        }
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "124",
    "attributes": {
      "status": "Complete",
      "createdAt": "2024-12-01T20:21:50.798Z",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Python",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Data Processing",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "evaluation": "The interview performance indicates a lack of specific examples and details that are crucial for demonstrating the required competencies for the AI/ML Engineer role in healthcare. Your responses were often vague and did not adequately connect your experiences to the job requirements, particularly in areas such as handling large-scale data, Python application, and Agile teamwork. This suggests a need for more preparation in articulating your relevant experiences and how they align with the job description.",
                "recommendation": [
                  {
                    "link": "www.udemy.com",
                    "type": "Online Course",
                    "title": "Resources",
                    "resource": "Data Science and Machine Learning Bootcamp with R"
                  },
                  {
                    "link": "www.udemy.com",
                    "type": "Online Course",
                    "title": "Resources",
                    "resource": "Python for Data Science and Machine Learning Bootcamp"
                  },
                  {
                    "link": "www.coursera.org",
                    "type": "Online Course",
                    "title": "Resources",
                    "resource": "Agile Project Management"
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Problem-Solving",
                    "description": "You demonstrated a problem-solving mindset by mentioning your experience with developing innovative solutions, such as the RAG system for legal documents."
                  }
                ],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked specific information about educational experiences and their relevance to the AI/ML role in healthcare.",
                    "question_no": 1
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked specific examples or relevant details related to handling large-scale data, security measures, and scalability strategies.",
                    "question_no": 2
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information about Python experience or its application in AI/ML.",
                    "question_no": 3
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant information or context regarding the handling of large-scale data, making it difficult to assess your experience in this critical area.",
                    "question_no": 4
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant content or context related to the question about working in an Agile team.",
                    "question_no": 5
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, providing no relevant information or context.",
                    "question_no": 6
                  },
                  {
                    "level": "10",
                    "reason": "The response was a single number without any explanation or context, making it largely irrelevant to the question asked.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Python",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Data Processing",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by your inability to provide detailed responses to questions."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8,
                  "total_time_taken_by_candidate": "00:00:24"
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your ability to articulate specific technical experiences, particularly in handling large-scale data and using Python for AI/ML algorithms. Focus on providing concrete examples from your past projects that demonstrate your expertise in these areas."
                  },
                  {
                    "skill": "Communication Skills",
                    "description": "You should work on structuring your responses more clearly and providing relevant details. Many of your answers lacked context and specificity, which made it difficult to assess your qualifications."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many of your responses were difficult to follow and lacked coherence, making it challenging to understand your experiences and qualifications."
                  },
                  {
                    "level": "Poor",
                    "skill": "engagement",
                    "reason": "You did not show much enthusiasm or responsiveness during the interview, which affected the overall engagement level."
                  }
                ],
                "overall_performance_score": 17.14
              }
            },
            "metadata": {
              "createdBy": "parrot"
            }
          }
        }
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "125",
    "attributes": {
      "status": "Complete",
      "createdAt": "2024-12-01T20:36:51.006Z",
      "i_persona_observer": {
        "data": {
          "attributes": {
            "attributes": {
              "interview_evaluation": {
                "message": "Poor",
                "competency": [
                  {
                    "name": "Industrialization Algorithms",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "evaluation": "Your performance in the interview indicates a need for improvement in articulating your experiences and connecting them to the specific requirements of the AI/ML Engineer role in healthcare. While you have relevant experience, the responses lacked detail and clarity, particularly in areas such as handling large-scale data, developing algorithms, and working within Agile teams. It is crucial to provide concrete examples that demonstrate your skills and knowledge in these areas.",
                "recommendation": [
                  {
                    "link": "https://www.coursera.org/specializations/jhu-data-science",
                    "type": "Online Course",
                    "title": "Data Handling and Security",
                    "resource": "Coursera's 'Data Science Specialization' by Johns Hopkins University, which covers data handling, security, and analysis."
                  },
                  {
                    "link": "https://www.udemy.com/course/scrum-master-certification/",
                    "type": "Online Course",
                    "title": "Agile Methodologies",
                    "resource": "Scrum Master Certification Course on Udemy to enhance your understanding of Agile practices."
                  },
                  {
                    "link": "https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844",
                    "type": "Book",
                    "title": "Algorithm Development",
                    "resource": "The book 'Introduction to Algorithms' by Thomas H. Cormen, which provides a comprehensive overview of algorithm design and analysis."
                  }
                ]
              },
              "interview_evaluation_metrics": {
                "rating": 1,
                "message": "Poor",
                "strength": [
                  {
                    "skill": "Problem-Solving",
                    "description": "You demonstrated a problem-solving mindset by mentioning your experience with developing innovative solutions, although specific examples were lacking."
                  }
                ],
                "relevancy": [
                  {
                    "level": "30",
                    "reason": "The response lacked any relevant information regarding educational background or its application to the AI/ML Engineer role in healthcare.",
                    "question_no": 1
                  },
                  {
                    "level": "30",
                    "reason": "The response lacked specific examples and did not directly address the question about handling large-scale data, security measures, or scalability strategies.",
                    "question_no": 2
                  },
                  {
                    "level": "30",
                    "reason": "The response did not provide sufficient information or examples related to the use of Python in AI/ML development, making it largely irrelevant to the question.",
                    "question_no": 3
                  },
                  {
                    "level": "20",
                    "reason": "The response lacked any relevant information or context regarding large-scale data handling, making it difficult to assess your experience in this critical area.",
                    "question_no": 4
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, lacking any relevant information or context.",
                    "question_no": 5
                  },
                  {
                    "level": "10",
                    "reason": "The response did not address the question at all, providing no relevant information or context.",
                    "question_no": 6
                  },
                  {
                    "level": "0",
                    "reason": "The response did not address the question at all, lacking any relevant information or context.",
                    "question_no": 7
                  }
                ],
                "competency": [
                  {
                    "name": "Industrialization Algorithms",
                    "sfia_level": "2"
                  },
                  {
                    "name": "Python",
                    "sfia_level": "3"
                  },
                  {
                    "name": "Agile Methodology",
                    "sfia_level": "2"
                  }
                ],
                "performance": [
                  {
                    "name": "confidence_level",
                    "level": "Poor",
                    "reason": "You appeared unsure and lacked confidence throughout the interview, as evidenced by your vague responses and inability to provide specific examples."
                  }
                ],
                "time_management": {
                  "fail": 0,
                  "pass": 8,
                  "total_time_taken_by_candidate": "00:00:21"
                },
                "areas_of_improvement": [
                  {
                    "skill": "Technical Skills",
                    "description": "You need to improve your ability to articulate your technical skills, particularly in Python and handling large-scale data. Providing concrete examples of projects where you applied these skills would enhance your credibility."
                  },
                  {
                    "skill": "Project Experience",
                    "description": "You should focus on detailing your project experiences more thoroughly. For instance, when discussing your work with large-scale data, include specific challenges faced and how you addressed them."
                  }
                ],
                "communication_skills": [
                  {
                    "level": "Poor",
                    "skill": "clarity",
                    "reason": "Many of your responses were difficult to follow, lacking coherence and specific details that would help convey your points effectively."
                  },
                  {
                    "level": "Poor",
                    "skill": "engagement",
                    "reason": "You did not show much interest or engagement during the interview, which affected the overall interaction and your ability to connect with the questions asked."
                  }
                ],
                "overall_performance_score": 18.57
              }
            },
            "metadata": {
              "createdBy": "parrot"
            }
          }
        }
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "126",
    "attributes": {
      "status": "Incomplete",
      "createdAt": "2024-12-01T21:34:15.502Z",
      "i_persona_observer": {
        "data": "null"
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "127",
    "attributes": {
      "status": "Incomplete",
      "createdAt": "2024-12-02T08:07:27.992Z",
      "i_persona_observer": {
        "data": "null"
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  },
  {
    "id": "128",
    "attributes": {
      "status": "Incomplete",
      "createdAt": "2024-12-02T08:08:09.568Z",
      "i_persona_observer": {
        "data": "null"
      },
      "tinder_user_profile": {
        "data": {
          "id": "167"
        }
      },
      "tinder_job_profile": {
        "data": {
          "id": "46"
        }
      }
    }
  }
]

In [ ]:
len(data)

In [20]:
from collections import defaultdict

def calculate_session_metrics(sessions):
    session_count = 0
    job_profile_count = 0
    user_profile_count = 0
    complete_sessions = 0
    incomplete_sessions = 0
    job_profile_frequency = defaultdict(int)
    user_profile_frequency = defaultdict(int)

    unique_job_profiles = set()
    unique_user_profiles = set()

    # Iterate over each session
    for idx, session in enumerate(sessions):
        session_count += 1

        # Ensure 'attributes' exist and is a dictionary
        attributes = session.get('attributes', {})
        if not isinstance(attributes, dict):
            print(f"Skipping session {idx} due to missing or invalid 'attributes'")
            continue

        # Extract job and user profiles safely
        job_profile = attributes.get('tinder_job_profile', {}).get('data', {})
        user_profile = attributes.get('tinder_user_profile', {}).get('data', {})

        # Ensure job_profile and user_profile are dictionaries, not strings
        if not isinstance(job_profile, dict):
            print(f"Skipping session {idx} due to invalid 'tinder_job_profile'")
            continue

        if not isinstance(user_profile, dict):
            print(f"Skipping session {idx} due to invalid 'tinder_user_profile'")
            continue

        job_profile_id = job_profile.get('id')
        user_profile_id = user_profile.get('id')

        # Check if job_profile_id and user_profile_id are valid
        if not job_profile_id or not user_profile_id:
            print(f"Skipping session {idx} due to missing job/user profile ID")
            continue

        # Count unique job profiles
        if job_profile_id not in unique_job_profiles:
            unique_job_profiles.add(job_profile_id)
            job_profile_count += 1

        # Count unique user profiles
        if user_profile_id not in unique_user_profiles:
            unique_user_profiles.add(user_profile_id)
            user_profile_count += 1

        # Track the frequency of job profiles and user profiles
        job_profile_frequency[job_profile_id] += 1
        user_profile_frequency[user_profile_id] += 1

        # Check if the session is complete or incomplete
        i_persona_observer = attributes.get('status')

        # Log the status and ensure all sessions are being processed
        print(f"Session {idx}: Status = {i_persona_observer}")

        if i_persona_observer == 'Incomplete':
            incomplete_sessions += 1
        else:
            complete_sessions += 1

    # Create the resulting JSON with calculated metrics
    result = {
        'session_count': session_count,
        'job_profile_count': job_profile_count,
        'user_profile_count': user_profile_count,
        'complete_sessions': complete_sessions,
        'incomplete_sessions': incomplete_sessions
    }

    return result


calculate_session_metrics(data)

Session 0: Status = Complete
Session 1: Status = Complete
Session 2: Status = Complete
Session 3: Status = Complete
Session 4: Status = Complete
Session 5: Status = Complete
Session 6: Status = Incomplete
Session 7: Status = Incomplete
Session 8: Status = Incomplete

{'session_count': 9,
 'job_profile_count': 1,
 'user_profile_count': 1,
 'complete_sessions': 6,
 'incomplete_sessions': 3}

In [1]:
def all_session_jobs_average_metrics(data):
    try:
        avg_confidence = calculate_average(data['overall_confidence'])
        avg_clarity = calculate_average(data['overall_clarity'])
        avg_engagment = calculate_average(data['overall_engagement'])
        avg_time_management = calculate_average_time_management(data['overall_time_management'])
 
        
        overall_data = {
                            "avg_confidence": avg_confidence,
                            "avg_clarity": avg_clarity,
                            "avg_engagment": avg_engagment,
                            "avg_time_management": avg_time_management
                        }
        
        return overall_data
        
    except Exception as e:
        print(f"process failed: ${str(e)}")
    
    
def calculate_average(data):
    try:
        total_score = 0
        count = 0
        
        for entry in data:
            value = entry.get("value", 0)          
            total_score += value 
            count += 1 
        
        average_confidence = total_score / count if count > 0 else 0
        return round(average_confidence, 2)

    except Exception as e:
        print(f"Error processing files: {e}")
        return {'error': str(e)}


def calculate_average_time_management(data):
    try:
        total_passes = 0
        total_fails = 0
        
        for entry in data:
            time_management = entry.get("time_management", {})
            passes = time_management.get("pass", 0)  
            fails = time_management.get("fail", 0)    
            
            total_passes += passes  
            total_fails += fails     
        
        total_questions = total_passes + total_fails
        
        average_pass_rate = round((total_passes / total_questions) * 100, 2) if total_questions > 0 else 0
        average_fail_rate = round((total_fails / total_questions) * 100, 2) if total_questions > 0 else 0

        return {
            "total_passes": total_passes,
            "total_fails": total_fails,
            "average_pass_rate": average_pass_rate,
            "average_fail_rate": average_fail_rate
        }
    except Exception as e:
        print(f"Error processing files: {e}")
        return {'error': str(e)}

In [3]:
data = [
  {
    "overall_clarity": [
      {
        "time": "08 Dec 2024 07:02 AM",
        "level": "poor",
        "value": 1
      }
    ],
    "overall_competency": [
      {
        "time": "08 Dec 2024 07:02 AM",
        "competency": [
          {
            "name": "Data Engineering",
            "sfia_level": "1"
          },
          {
            "name": "Machine Learning",
            "sfia_level": "1"
          },
          {
            "name": "Professional Communication",
            "sfia_level": "1"
          }
        ]
      }
    ],
    "overall_confidence": [
      {
        "time": "08 Dec 2024 07:02 AM",
        "level": "poor",
        "value": 1
      }
    ],
    "overall_engagement": [
      {
        "time": "08 Dec 2024 07:02 AM",
        "level": "poor",
        "value": 1
      }
    ],
    "overall_performance": [
      {
        "time": "08 Dec 2024 07:02 AM",
        "score": 17.14
      }
    ],
    "overall_time_management": [
      {
        "time": "08 Dec 2024 07:02 AM",
        "time_management": {
          "fail": 0,
          "pass": 8,
          "total_time_taken_by_candidate": "00:02:34"
        }
      }
    ]
  }
]
all_session_jobs_average_metrics(data)

process failed: $list indices must be integers or slices, not str