In [9]:
# -*- coding: utf-8 -*-
%load_ext autoreload
%autoreload 2

In [10]:
! pip install json-repair

Requirement already satisfied: json-repair in /home/ek/Documents/10Xtutor/SIFA/tenx_ipersona/env/lib/python3.10/site-packages (0.27.2)

In [11]:
import json, json_repair
def extract_jsons(response, quite=False):    
    if isinstance(response, (dict, list)):
        # return as it is 
        # if not quite: print("extract_json", "response is already in json format")
        return response       
    elif isinstance(response, str):
        # Method 1
        try:
            # try simple to load it as json
            res = json.loads(response)
            # if not quite: print("extract_json", "response is already in jsons format")
            return res
        except:
            pass
            # if not quite: print("extract_json: simple json load failed. Trying to fix json string ...")
           
        # Method 2 
        try:
            # if not quite: print("extract_json", "response is not in json format. Trying to extract json from response")
            if '```json' in text:                
                out = text.split('```json')[1].split('```')[0].replace('\n','')
            elif '```' in text:
                out = text.split('```')[1].split('```')[0].replace('\n','')
            else:
                out = text

            res = json.loads(out)
            return res        
        except Exception as e:
            # if not quite: print(f"extract_json: unable to fix json string. Trying with json_repair ...")
            pass         
            # it is not in json string format
            
            # Method 3
            text = response
            try:                
                res = json_repair.loads(text)
                if isinstance(res, (dict, list)):
                    # if not quite: print("extract_json: result obtained using repair json")
                    return res
            except:
                if not quite: print("extract_json: unable to repair json string using json_repair. Raise exception")
                raise
    else:
        # if not quite: print("extract_json", "response is not a string or a dictionary")
        return {}

:

In [12]:
response = """
    Overall, you have demonstrated qualities that align with the role's requirements outlined in the job description. Your performance was Good.

    { "evaluation": { "percentage": "80%", "message": "Good" } }

    I would like to offer you the opportunity for a follow-up interview. If you agree, we can conduct a new round of fresh, diverse questions, including more technical questions related to the specific position you are applying for. Would you like to proceed?
"""
val = extract_json(response)

NameError: name 'extract_json' is not defined

In [14]:
import json
import json_repair

def extract_json(response, quite=False):    
    if isinstance(response, (dict, list)):
        return response, ""  # Return as it is       
    elif isinstance(response, str):
        # Initialize variables
        json_part = None
        
        # Method 1: Try simple JSON load
        try:
            json_part = json.loads(response)
            return json_part, ""  # Return if already valid JSON with empty text
        except:
            pass
        
        # Method 2: Attempt to extract JSON from response
        try:
            # Find the first occurrence of '{' and the last occurrence of '}'
            start_index = response.index('{')
            end_index = response.rindex('}') + 1
            json_str = response[start_index:end_index]
            json_part = json.loads(json_str)
            # Remove the JSON part from the original response
            non_json_part = response.replace(json_str, '').strip()
            return json_part, non_json_part        
        except Exception:
            pass
            
        # Method 3: Try using json_repair
        try:                
            repaired_json = json_repair.loads(response)
            if isinstance(repaired_json, (dict, list)):
                repaired_json_str = json.dumps(repaired_json)  # Convert to string
                non_json_part = response.replace(repaired_json_str, '').strip()  # Remove JSON part from original response
                return repaired_json, non_json_part
        except:
            if not quite:
                print("extract_json: unable to repair json string using json_repair. Raise exception")
            raise

    # If no valid JSON was found, return None for both
    return None, None

# Example usage
response = """
    Overall, you have demonstrated qualities that align with the role's requirements outlined in the job description. Your performance was Good.

    

    I would like to offer you the opportunity for a follow-up interview. If you agree, we can conduct a new round of fresh, diverse questions, including more technical questions related to the specific position you are applying for. Would you like to proceed?
"""

json_output, other_text = extract_json(response)
print("JSON Output:", json_output)
print("Other Text:", other_text)

JSON Output: None
Other Text: None

In [15]:
# import pandas as pd

# df = pd.read_csv('./dataset/job_match.csv', index_col=0)

# json_data = df.to_json(orient='records', lines=True)

# with open('./dataset/job_match.json', 'w') as json_file:
#     json_file.write(json_data)

# print(json_data)

In [19]:
import pandas as pd
import pprint as pp
# df = pd.read_csv('./dataset/extracted/job_match.csv', index_col=0)
# len(df)
# df.head()

In [17]:
filtered_df = df[df['match_attributes_overall_match_degree'].isin(['very high'])]
# Assign to result_df
result_df = filtered_df

NameError: name 'df' is not defined

In [18]:
# Get unique user_profile_ids
unique_user_ids = result_df['user_profile_id'].unique()

# Create a dictionary to store results
user_data = {}

# Fetch 3 rows for each unique user_profile_id
for user_id in unique_user_ids:
    user_data[user_id] = result_df[result_df['user_profile_id'] == user_id].head(3)

# Optionally, convert the dictionary to a DataFrame for better display
final_result_df = pd.concat(user_data.values())

len(final_result_df)

# final_result_df

NameError: name 'result_df' is not defined

In [19]:
df['match_attributes_overall_match_degree'].unique()

NameError: name 'df' is not defined

In [20]:
result_df['user_profile_id'].unique()

NameError: name 'result_df' is not defined

In [ ]:
result_df['job_profile_id'].unique()

In [ ]:
df2 = pd.read_csv('./dataset/extracted/job_profile.csv', index_col=0)
len(df2)
# df2.head()

In [13]:
job_profile_ids = [1035, 1041, 1086, 808, 929, 616, 190, 191, 49, 197, 618, 621, 52]

filtered_job_profiles = df2[df2['job_profile_id'].isin(job_profile_ids)]

len(filtered_job_profiles)

#filtered_job_profiles['job_profile_id'].unique()

11

In [14]:
df3 = pd.read_csv('./dataset/extracted/user_profile.csv', index_col=0)
len(df3)

30

In [ ]:
# Define the user_profile_ids to fetch
user_profile_ids = [197, 167, 176, 183, 189, 180]

filtered_user_profiles = df3[df3['user_profile_id'].isin(user_profile_ids)]

# Display the filtered job profiles
len(filtered_user_profiles)
json_data = filtered_user_profiles.to_json(orient='records', lines=True)

with open('./dataset/final/user_profiles.json', 'w') as json_file:
    json_file.write(json_data)

In [ ]:
pp.pprint(len(df))
df.columns.tolist()
'user_job_match_id',
'job_profile_id',
'user_profile_id',
'match_attributes_overall_match_score',
'match_attributes_overall_match_degree',

In [ ]:
df = pd.read_csv('./dataset/job_match.csv')

# List of columns to keep
columns_to_keep_job_match = [
    'user_job_match_id',
    'job_profile_id',
    'user_profile_id',
    'match_attributes_overall_match_score',
    'match_attributes_overall_match_degree'
]

# Create a new DataFrame with only the specified columns
new_job_match_df = df[columns_to_keep_job_match]
new_job_match_df.to_csv('./dataset/extracted/extracted_job_match.csv')
# Display the new DataFrame
print(new_job_match_df)

In [23]:
df2 = pd.read_csv('./dataset/job_profile.csv')
print(len(df2))
df2.columns.to_list()

1000

['job_profile_id',
 'job_id',
 'title',
 'category',
 'level',
 'label',
 'location',
 'summary',
 'tags',
 'applyLink',
 'job_id.1',
 'role',
 'purpose',
 'apply_link',
 'posted_date',
 'company_info_name',
 'company_info_size',
 'company_info_summary',
 'company_name',
 'competencies_name',
 'competencies_summary',
 'competencies_relevance',
 'competencies_sfia_level',
 'competencies_rationale_name',
 'job_is_a_fit',
 'salary_range',
 'application_url',
 'employment_type',
 'rationale_is_a_fit',
 'job_is_fully_remote',
 'input_is_job_description',
 'job_posted_at_datetime_utc',
 'job_offer_expiration_datetime_utc',
 'createdAt',
 'duties_responsibilities',
 'required_qualifications',
 'preferred_qualifications',
 'url',
 'company_info_location',
 'company_info_mission',
 'company_info_values',
 'company_info_overview',
 'required_qualifications_Education',
 'competencies_rationale_sfia_level',
 'company_info_annual_revenue',
 'competencies_other_attributes',
 'company_info_website',
 'company_info_instagram',
 'company_info_example_school',
 'company_info_revenue',
 'company_info_headquarters',
 'company_info_central_office',
 'company_info_funding',
 'company_info_additional_info',
 'company_info_diversity_inclusion',
 'company_info_founded',
 'company_info_industry',
 'required_competencies_name',
 'required_competencies_summary',
 'required_competencies_relevance',
 'required_competencies_sfia_level',
 'required_competencies_rationale_name',
 'weaviate_uuid',
 'company_info_status',
 'company_info_country',
 'company_info_year_founded',
 'company_info_locations',
 'company_info_global_offices',
 'company_info_other_info_website',
 'company_info_other_info_equal_opportunity_statement',
 'company_info_stage',
 'source_{k}',
 'company_info_culture',
 'company_info_links_Twitter',
 'company_info_links_LinkedIn',
 'company_info_name:']

In [23]:
df2 = pd.read_csv('./dataset/combined_job_data.csv')
df2.columns

Index(['job_profile_id', 'required_qualifications', 'duties_responsibilities',
       'purpose', 'role', 'competencies'],
      dtype='object')

In [ ]:
# Read the CSV file into a DataFrame
df2 = pd.read_csv('./dataset/combined_job_data.csv')

# List of columns to keep
columns_to_keep_job_profile = [
    "title",
    "category",
    "location",
    "summary",
    "job_profile_id",
    "attributes.role",
    "attributes.level",
    "attributes.title",
    "attributes.purpose",
    "attributes.location",
    "attributes.apply_link",
    "attributes.posted_date",
    "attributes.company_info.name",
    "attributes.company_info.summary",
    "attributes.company_name",
    "attributes.competencies",
    "attributes.job_is_a_fit",
    "attributes.salary_range",
    "attributes.application_url",
    "attributes.employment_type",
    "attributes.rationale_is_a_fit",
    "attributes.job_is_fully_remote",
    "attributes.duties_responsibilities",
    "attributes.required_qualifications",
    "attributes.preferred_qualifications",
    "attributes.company_info.size",
    "attributes.company_info.founded",
    "attributes.company_info.website",
    "attributes.company_info.industry",
    "attributes.company_info.mission"
]

# Create a new DataFrame with only the specified columns
new_job_df = df2[columns_to_keep_job_profile]
new_job_df.to_csv('./dataset/extracted_job_profile.csv')
# Display the new DataFrame
print(new_job_df)

In [25]:
df3 = pd.read_csv('./dataset/user_profile_data.csv')
print(len(df3))
df3.head()

29

,name,display,description,profile_type,user_profile_id,awards.code,awards.name,awards.display,awards.template,awards.attributes,...,work_experience.attributes,work_experience.description,work_experience.profile_type,programing_languages.code,programing_languages.name,programing_languages.display,programing_languages.template,programing_languages.attributes,programing_languages.description,programing_languages.profile_type
0,user_profile,User Profile,User profile information,user_profile,11,awards,awards,Awards,form,"[{'date': '2023-06-30', 'uuid': 'c53f0125-6dc5...",...,"[{'role': 'Software Engineering Fellowship', '...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
1,user_profile,User Profile,User profile information,user_profile,16,awards,awards,Awards,form,[],...,"[{'role': 'Full-stack Developer', 'uuid': '323...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
2,user_profile,User Profile,User profile information,user_profile,8,awards,awards,Awards,form,[],...,[],Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
3,user_profile,User Profile,User profile information,user_profile,21,awards,awards,Awards,form,"[{'date': '', 'uuid': 'e69f2a9d-3b30-45de-ab02...",...,"[{'role': 'Data engineering, Machine learning ...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages
4,user_profile,User Profile,User profile information,user_profile,4,awards,awards,Awards,form,[],...,"[{'role': 'Software Engineer', 'uuid': '04d46b...",Work experiences of the user,work_experience,programing_languages,programing_languages,Programming Languages,form,[],Programming languages the user is familiar with,programing_languages

In [26]:
df3.columns.to_list()

['user_profile_id',
 'all_user_id',
 'name',
 'email',
 'batch',
 'trainee_id',
 'category',
 'slug',
 'name.1',
 'awards_code',
 'awards_name',
 'awards_display',
 'awards_template',
 'awards_date',
 'awards_uuid',
 'awards_title',
 'awards_status',
 'awards_awarder',
 'awards_history_blob',
 'awards_history_user',
 'awards_history_status',
 'awards_history_timestamp',
 'awards_summary',
 'awards_verified_by',
 'awards_requested_by',
 'awards_description',
 'awards_profile_type',
 'basics_code',
 'basics_name',
 'basics_display',
 'basics_template',
 'basics_role',
 'basics_uuid',
 'basics_email',
 'basics_image',
 'basics_status',
 'basics_history_blob',
 'basics_history_user',
 'basics_history_status',
 'basics_history_timestamp',
 'basics_location_city',
 'basics_location_icon',
 'basics_location_region',
 'basics_location_address',
 'basics_location_country',
 'basics_location_postal_code',
 'basics_full_name',
 'basics_name_title',
 'basics_verified_by',
 'basics_requested_by',
 'basics_personal_statement',
 'basics_description',
 'basics_profile_type',
 'display',
 'projects_code',
 'projects_name',
 'projects_display',
 'projects_template',
 'projects_url',
 'projects_uuid',
 'projects_title',
 'projects_status',
 'projects_history_blob',
 'projects_history_user',
 'projects_history_status',
 'projects_history_timestamp',
 'projects_summary',
 'projects_end_date',
 'projects_focus_area',
 'projects_start_date',
 'projects_verified_by',
 'projects_requested_by',
 'projects_description',
 'projects_profile_type',
 'education_code',
 'education_name',
 'education_display',
 'education_template',
 'education_uuid',
 'education_score',
 'education_remark',
 'education_status',
 'education_country',
 'education_history_blob',
 'education_history_user',
 'education_history_status',
 'education_history_timestamp',
 'education_end_date',
 'education_start_date',
 'education_study_area',
 'education_study_type',
 'education_verified_by',
 'education_requested_by',
 'education_institution_url',
 'education_institution_name',
 'education_description',
 'education_profile_type',
 'interests_code',
 'interests_name',
 'interests_display',
 'interests_template',
 'interests_uuid',
 'interests_status',
 'interests_history_blob',
 'interests_history_user',
 'interests_history_status',
 'interests_history_timestamp',
 'interests_verified_by',
 'interests_requested_by',
 'interests_description',
 'interests_profile_type',
 'languages_code',
 'languages_name',
 'languages_display',
 'languages_template',
 'languages_uuid',
 'languages_status',
 'languages_fluency',
 'languages_history_blob',
 'languages_history_user',
 'languages_history_status',
 'languages_history_timestamp',
 'languages_language',
 'languages_verified_by',
 'languages_requested_by',
 'languages_description',
 'languages_profile_type',
 'volunteer_code',
 'volunteer_name',
 'volunteer_display',
 'volunteer_template',
 'volunteer_url',
 'volunteer_uuid',
 'volunteer_status',
 'volunteer_history_blob',
 'volunteer_history_user',
 'volunteer_history_status',
 'volunteer_history_timestamp',
 'volunteer_summary',
 'volunteer_end_date',
 'volunteer_position',
 'volunteer_start_date',
 'volunteer_verified_by',
 'volunteer_organization',
 'volunteer_requested_by',
 'volunteer_description',
 'volunteer_profile_type',
 'references_code',
 'references_name',
 'references_display',
 'references_template',
 'references_uuid',
 'references_status',
 'references_history_blob',
 'references_history_user',
 'references_history_status',
 'references_history_timestamp',
 'references_priority',
 'references_verified_by',
 'references_requested_by',
 'references_reference_text',
 'references_description',
 'references_profile_type',
 'description',
 'achievements_code',
 'achievements_name',
 'achievements_display',
 'achievements_template',
 'achievements_date',
 'achievements_uuid',
 'achievements_title',
 'achievements_status',
 'achievements_history_blob',
 'achievements_history_user',
 'achievements_history_status',
 'achievements_history_timestamp',
 'achievements_summary',
 'achievements_verified_by',
 'achievements_requested_by',
 'achievements_description',
 'achievements_profile_type',
 'certificates_code',
 'certificates_name',
 'certificates_display',
 'certificates_template',
 'certificates_url',
 'certificates_date',
 'certificates_uuid',
 'certificates_issuer',
 'certificates_status',
 'certificates_history_blob',
 'certificates_history_user',
 'certificates_history_status',
 'certificates_history_timestamp',
 'certificates_verified_by',
 'certificates_requested_by',
 'certificates_description',
 'certificates_profile_type',
 'competencies_code',
 'competencies_name',
 'competencies_display',
 'competencies_template',
 'competencies_uuid',
 'competencies_status',
 'competencies_history_blob',
 'competencies_history_user',
 'competencies_history_status',
 'competencies_history_timestamp',
 'competencies_evidence_source_link',
 'competencies_evidence_source_name',
 'competencies_evidence_status',
 'competencies_evidence_sentiment',
 'competencies_evidence_verified_by',
 'competencies_evidence_requested_by',
 'competencies_evidence_confidence_degree',
 'competencies_evidence_sfia_level_approved',
 'competencies_evidence_sfia_level_requested',
 'competencies_rationale',
 'competencies_sfia_level',
 'competencies_description',
 'competencies_verified_by',
 'competencies_requested_by',
 'competencies_experience_level',
 'competencies_sfia_estimation_method',
 'competencies_profile_type',
 'profile_type',
 'publications_code',
 'publications_name',
 'publications_display',
 'publications_template',
 'publications_url',
 'publications_uuid',
 'publications_status',
 'publications_history_blob',
 'publications_history_user',
 'publications_history_status',
 'publications_history_timestamp',
 'publications_summary',
 'publications_publisher',
 'publications_verified_by',
 'publications_release_date',
 'publications_requested_by',
 'publications_description',
 'publications_profile_type',
 'work_experience_code',
 'work_experience_name',
 'work_experience_display',
 'work_experience_template',
 'work_experience_role',
 'work_experience_uuid',
 'work_experience_status',
 'work_experience_company',
 'work_experience_history_blob',
 'work_experience_history_user',
 'work_experience_history_status',
 'work_experience_history_timestamp',
 'work_experience_summary',
 'work_experience_end_date',
 'work_experience_location',
 'work_experience_start_date',
 'work_experience_company_url',
 'work_experience_verified_by',
 'work_experience_requested_by',
 'work_experience_description',
 'work_experience_profile_type',
 'programing_languages_code',
 'programing_languages_name',
 'programing_languages_display',
 'programing_languages_template',
 'programing_languages_description',
 'programing_languages_profile_type',
 'tags',
 'title',
 'credibility',
 'summary',
 'created_at',
 'basics_media_icon',
 'basics_media_link',
 'basics_media_name',
 'basics_phone_icon',
 'basics_phone_name',
 'basics_phone_value',
 'references_contact_email',
 'references_contact_phone',
 'references_contact_remark',
 'references_contact_full_name',
 'references_contact_relationship',
 'competencies_evidence_remark',
 'competencies_evidence_message_role',
 'competencies_evidence_message_content',
 'competencies_evidence_message_timestamp',
 'competencies_evidence_sfia_dimensions_requested_name',
 'competencies_evidence_sfia_dimensions_requested_level',
 'competencies_evidence_sfia_dimensions_approved_name',
 'competencies_evidence_sfia_dimensions_approved_level']

In [27]:
df3.columns.tolist()
"user_profile_id"
"name"
"email"
"basics_location_address"
"basics_personal_statement"
"projects_code"
"projects_name"
"projects_display"
"projects_url"
"projects_history_timestamp"
"projects_summary"
"projects_end_date"
"education_code" 
"education_name"
"education_display"
"education_end_date"
"education_start_date"
"education_study_area"
"education_study_type"
"education_institution_name"
"languages_code"
"languages_display"
"languages_language"
"languages_fluency"
"achievements_code"
"achievements_display"
"certificates_code"
"certificates_name"
"certificates_display"
"certificates_url"
"certificates_issuer"
"work_experience_code"
"work_experience_display"
"work_experience_role"
"work_experience_company"
"work_experience_history_timestamp"
"work_experience_summary"
"work_experience_location"
"work_experience_start_date"
"work_experience_company_url"

'work_experience_company_url'

In [37]:

import pandas as pd

# Read the CSV file into a DataFrame
df3 = pd.read_csv('./dataset/user_profile_data.csv')

# List of columns to keep
columns_to_keep = [
"name",
"description",
"user_profile_id",
"basics.attributes",
"basics.description",
"projects.display",
"projects.attributes",
"projects.description",
"projects.profile_type",
"education.display",
"education.attributes",
"education.description",
"interests.display",
"interests.description",
"languages.display",
"languages.attributes",
"languages.description",
"volunteer.display",
"volunteer.description",
"references.display",
"references.description",
"achievements.display",
"achievements.description",
"certificates.display",
"certificates.attributes",
"certificates.description",
"competencies.display",
"competencies.attributes",
"publications.display",
"publications.description",
"publications.profile_type",
"work_experience.display",
"programing_languages.description",
"programing_languages.display",
"work_experience.attributes"
]

# Create a new DataFrame with only the specified columns
new_df = df3[columns_to_keep]
new_df.to_csv('./dataset/extract_user_profile_with_comptency.csv')
# Display the new DataFrame
print(new_df)

            name               description  user_profile_id  \
0   user_profile  User profile information               11
1   user_profile  User profile information               16
2   user_profile  User profile information                8
3   user_profile  User profile information               21
4   user_profile  User profile information                4
5   user_profile  User profile information               31
6   user_profile  User profile information               30
7   user_profile  User profile information                5
8   user_profile  User profile information               24
9   user_profile  User profile information               12
10  user_profile  User profile information                3
11  user_profile  User profile information                7
12  user_profile  User profile information               26
13  user_profile  User profile information               20
14  user_profile  User profile information               23
15  user_profile  User profile information               17
16  user_profile  User profile information               28
17  user_profile  User profile information                1
18  user_profile  User profile information                6
19  user_profile  User profile information               15
20  user_profile  User profile information                2
21  user_profile  User profile information               29
22  user_profile  User profile information               13
23  user_profile  User profile information               25
24  user_profile  User profile information               27
25  user_profile  User profile information               18
26  user_profile  User profile information               14
27  user_profile  User profile information               22
28  user_profile  User profile information               19

                                    basics.attributes  \
0   [{'role': 'Machine Learning Engineer|AI Engine...
1   [{'role': 'Generative AI Engineer | Software E...
2   [{'role': '', 'uuid': '90a30031-fa4d-4de1-a0ae...
3   [{'role': 'AI Engineer | Software Engineer | M...
4   [{'role': 'Generative AI | Software Engineerin...
5   [{'role': '10 Academy ', 'uuid': '9c7bcd69-f5c...
6   [{'role': '--Data Scientist||Data Engineering|...
7   [{'role': 'Generative AI Engineer | ML Enthusi...
8   [{'role': 'Generative AI Engineer | Machine Le...
9   [{'role': 'Generative AI Engineer | Machine Le...
10  [{'role': 'Data Engineer | Machine Learning | ...
11  [{'role': 'Data Engineer | Gen AI Engineer | U...
12  [{'role': 'Machine Learning Engineer|| Radio p...
13  [{'role': 'AI/ ML Engineer | Software Engineer...
14  [{'role': 'Generative AI & ML Engineer | CTO |...
15  [{'role': 'Data Engineer| ML Engineer', 'uuid'...
16  [{'role': 'Tensorflow Certified Developer | Ma...
17  [{'role': '', 'uuid': 'ef5db2a6-8114-440c-9052...
18  [{'role': 'Machine Learning Engineer | Generat...
19  [{'role': 'Geomatic Engineer | GIS Data Analys...
20  [{'role': 'Generative AI Engineer', 'uuid': '5...
21  [{'role': 'Generative AI Engineer | Machine le...
22  [{'role': 'Generative AI Engineer | Machine Le...
23  [{'role': 'Generative AI Engineer | Machine Le...
24  [{'role': 'Generative AI Engineer | Machine Le...
25  [{'role': 'Generative AI Engineer | Machine Le...
26  [{'role': 'Generative AI | ML Engineer', 'uuid...
27  [{'role': 'Generative Artificial Intelligence ...
28  [{'role': 'Generative AI | Data | Software Eng...

                  basics.description projects.display  \
0   Basic information about the user         Projects
1   Basic information about the user         Projects
2   Basic information about the user         Projects
3   Basic information about the user         Projects
4   Basic information about the user         Projects
5   Basic information about the user         Projects
6   Basic information about the user         Projects
7   Basic information about the user         Projects
8   Basic information about the user         Projects
9   Basic information about the user         Projects
10  Basic information about the user         Projects
11  Basic information about the user         Projects
12  Basic information about the user         Projects
13  Basic information about the user         Projects
14  Basic information about the user         Projects
15  Basic information about the user         Projects
16  Basic information about the user         Projects
17  Basic information about the user         Projects
18  Basic information about the user         Projects
19  Basic information about the user         Projects
20  Basic information about the user         Projects
21  Basic information about the user         Projects
22  Basic information about the user         Projects
23  Basic information about the user         Projects
24  Basic information about the user         Projects
25  Basic information about the user         Projects
26  Basic information about the user         Projects
27  Basic information about the user         Projects
28  Basic information about the user         Projects

                                  projects.attributes  \
0   [{'url': 'None', 'uuid': 'f0e10a16-f947-46a1-9...
1   [{'url': 'None', 'uuid': 'c4adfcce-acac-486b-b...
2                                                  []
3   [{'url': 'https://github.com/jadmassu/chatbot_...
4   [{'url': 'None', 'uuid': 'ed27398d-a1ee-46bd-b...
5   [{'url': 'http://cosmos.esa.int/web/planck', '...
6   [{'url': 'None', 'uuid': '52f6aeeb-d412-4369-a...
7   [{'url': 'None', 'uuid': 'e5687ca8-4f7f-44b5-8...
8   [{'url': 'None', 'uuid': '98f386be-9a22-4384-8...
9   [{'url': 'None', 'uuid': '8c85aeb6-f764-4a56-a...
10                                                 []
11  [{'url': 'None', 'uuid': '24ba7520-7213-46de-8...
12  [{'url': 'None', 'uuid': '02d2af9d-56af-4d21-b...
13  [{'url': 'None', 'uuid': 'cc444703-88c5-4c64-b...
14  [{'url': 'None', 'uuid': '112426f3-a383-41e4-9...
15                                                 []
16  [{'url': 'None', 'uuid': 'c402bf64-c8dc-4a94-9...
17                                                 []
18                                                 []
19  [{'url': 'None', 'uuid': '694fef5c-3276-4190-a...
20  [{'url': 'None', 'uuid': '5b961a4e-7f1e-4d13-9...
21  [{'url': 'None', 'uuid': 'f46879c8-53db-4ec8-a...
22  [{'url': 'None', 'uuid': 'cd2ff12a-89e5-4cf1-a...
23  [{'url': 'None', 'uuid': '33aca2d2-8b9d-48aa-8...
24  [{'url': 'None', 'uuid': 'bd7278a7-db94-4ab1-a...
25  [{'url': 'None', 'uuid': '713cc6c1-45de-4463-b...
26  [{'url': 'None', 'uuid': 'f1093510-bf23-42d8-a...
27  [{'url': 'None', 'uuid': '39c7c1ae-ee87-45ce-b...
28  [{'url': 'None', 'uuid': '7f97e410-60d9-4839-a...

               projects.description projects.profile_type education.display  \
0   Projects the user has worked on              projects         Education
1   Projects the user has worked on              projects         Education
2   Projects the user has worked on              projects         Education
3   Projects the user has worked on              projects         Education
4   Projects the user has worked on              projects         Education
5   Projects the user has worked on              projects         Education
6   Projects the user has worked on              projects         Education
7   Projects the user has worked on              projects         Education
8   Projects the user has worked on              projects         Education
9   Projects the user has worked on              projects         Education
10  Projects the user has worked on              projects         Education
11  Projects the user has worked on              projects         Education
12  Projects the user has worked on              projects         Education
13  Projects the user has worked on              projects         Education
14  Projects the user has worked on              projects         Education
15  Projects the user has worked on              projects         Education
16  Projects the user has worked on              projects         Education
17  Projects the user has worked on              projects         Education
18  Projects the user has worked on              projects         Education
19  Projects the user has worked on              projects         Education
20  Projects the user has worked on              projects         Education
21  Projects the user has worked on              projects         Education
22  Projects the user has worked on              projects         Education
23  Projects the user has worked on              projects         Education
24  Projects the user has worked on              projects         Education
25  Projects the user has worked on              projects         Education
26  Projects the user has worked on              projects         Education
27  Projects the user has worked on              projects         Education
28  Projects the user has worked on              projects         Education

    ...             certificates.description competencies.display  \
0   ...  Certificates and awards of the user         Competencies
1   ...  Certificates and awards of the user         Competencies
2   ...  Certificates and awards of the user         Competencies
3   ...  Certificates and awards of the user         Competencies
4   ...  Certificates and awards of the user         Competencies
5   ...  Certificates and awards of the user         Competencies
6   ...  Certificates and awards of the user         Competencies
7   ...  Certificates and awards of the user         Competencies
8   ...  Certificates and awards of the user         Competencies
9   ...  Certificates and awards of the user         Competencies
10  ...  Certificates and awards of the user         Competencies
11  ...  Certificates and awards of the user         Competencies
12  ...  Certificates and awards of the user         Competencies
13  ...  Certificates and awards of the user         Competencies
14  ...  Certificates and awards of the user         Competencies
15  ...  Certificates and awards of the user         Competencies
16  ...  Certificates and awards of the user         Competencies
17  ...  Certificates and awards of the user         Competencies
18  ...  Certificates and awards of the user         Competencies
19  ...  Certificates and awards of the user         Competencies
20  ...  Certificates and awards of the user         Competencies
21  ...  Certificates and awards of the user         Competencies
22  ...  Certificates and awards of the user         Competencies
23  ...  Certificates and awards of the user         Competencies
24  ...  Certificates and awards of the user         Competencies
25  ...  Certificates and awards of the user         Competencies
26  ...  Certificates and awards of the user         Competencies
27  ...  Certificates and awards of the user         Competencies
28  ...  Certificates and awards of the user         Competencies

                              competencies.attributes publications.display  \
0   [{'name': 'programming language', 'uuid': '4d6...         Publications
1   [{'name': 'programming language', 'uuid': '476...         Publications
2   [{'name': 'programming language', 'uuid': '475...         Publications
3   [{'name': 'programming language', 'uuid': 'dc7...         Publications
4   [{'name': 'programming language', 'uuid': 'bca...         Publications
5   [{'name': 'programming language', 'uuid': '78d...         Publications
6   [{'name': 'programming language', 'uuid': '54a...         Publications
7   [{'name': 'programming language', 'uuid': '3e8...         Publications
8   [{'name': 'programming language', 'uuid': 'c1d...         Publications
9   [{'name': 'programming language', 'uuid': '65a...         Publications
10  [{'name': 'programming language', 'uuid': '318...         Publications
11  [{'name': 'programming language', 'uuid': '314...         Publications
12  [{'name': 'programming language', 'uuid': '7a3...         Publications
13  [{'name': 'programming language', 'uuid': 'a67...         Publications
14  [{'name': 'programming language', 'uuid': 'c40...         Publications
15  [{'name': 'programming language', 'uuid': '5bc...         Publications
16  [{'name': 'programming language', 'uuid': 'e21...         Publications
17  [{'name': 'programming language', 'uuid': 'cdf...         Publications
18  [{'name': 'programming language', 'uuid': '90d...         Publications
19  [{'name': 'programming language', 'uuid': 'eb8...         Publications
20  [{'name': 'programming language', 'uuid': 'b8b...         Publications
21  [{'name': 'programming language', 'uuid': 'a97...         Publications
22  [{'name': 'programming language', 'uuid': '61c...         Publications
23  [{'name': 'programming language', 'uuid': '2a8...         Publications
24  [{'name': 'programming language', 'uuid': 'b12...         Publications
25  [{'name': 'programming language', 'uuid': '5f0...         Publications
26  [{'name': 'programming language', 'uuid': '209...         Publications
27  [{'name': 'programming language', 'uuid': '108...         Publications
28  [{'name': 'programming language', 'uuid': 'cd7...         Publications

    publications.description publications.profile_type  \
0   Publications of the user              publications
1   Publications of the user              publications
2   Publications of the user              publications
3   Publications of the user              publications
4   Publications of the user              publications
5   Publications of the user              publications
6   Publications of the user              publications
7   Publications of the user              publications
8   Publications of the user              publications
9   Publications of the user              publications
10  Publications of the user              publications
11  Publications of the user              publications
12  Publications of the user              publications
13  Publications of the user              publications
14  Publications of the user              publications
15  Publications of the user              publications
16  Publications of the user              publications
17  Publications of the user              publications
18  Publications of the user              publications
19  Publications of the user              publications
20  Publications of the user              publications
21  Publications of the user              publications
22  Publications of the user              publications
23  Publications of the user              publications
24  Publications of the user              publications
25  Publications of the user              publications
26  Publications of the user              publications
27  Publications of the user              publications
28  Publications of the user              publications

   work_experience.display                 programing_languages.description  \
0         Work Experiences  Programming languages the user is familiar with
1         Work Experiences  Programming languages the user is familiar with
2         Work Experiences  Programming languages the user is familiar with
3         Work Experiences  Programming languages the user is familiar with
4         Work Experiences  Programming languages the user is familiar with
5         Work Experiences  Programming languages the user is familiar with
6         Work Experiences  Programming languages the user is familiar with
7         Work Experiences  Programming languages the user is familiar with
8         Work Experiences  Programming languages the user is familiar with
9         Work Experiences  Programming languages the user is familiar with
10        Work Experiences  Programming languages the user is familiar with
11        Work Experiences  Programming languages the user is familiar with
12        Work Experiences  Programming languages the user is familiar with
13        Work Experiences  Programming languages the user is familiar with
14        Work Experiences  Programming languages the user is familiar with
15        Work Experiences  Programming languages the user is familiar with
16        Work Experiences  Programming languages the user is familiar with
17        Work Experiences  Programming languages the user is familiar with
18        Work Experiences  Programming languages the user is familiar with
19        Work Experiences  Programming languages the user is familiar with
20        Work Experiences  Programming languages the user is familiar with
21        Work Experiences  Programming languages the user is familiar with
22        Work Experiences  Programming languages the user is familiar with
23        Work Experiences  Programming languages the user is familiar with
24        Work Experiences  Programming languages the user is familiar with
25        Work Experiences  Programming languages the user is familiar with
26        Work Experiences  Programming languages the user is familiar with
27        Work Experiences  Programming languages the user is familiar with
28        Work Experiences  Programming languages the user is familiar with

   programing_languages.display  \
0         Programming Languages
1         Programming Languages
2         Programming Languages
3         Programming Languages
4         Programming Languages
5         Programming Languages
6         Programming Languages
7         Programming Languages
8         Programming Languages
9         Programming Languages
10        Programming Languages
11        Programming Languages
12        Programming Languages
13        Programming Languages
14        Programming Languages
15        Programming Languages
16        Programming Languages
17        Programming Languages
18        Programming Languages
19        Programming Languages
20        Programming Languages
21        Programming Languages
22        Programming Languages
23        Programming Languages
24        Programming Languages
25        Programming Languages
26        Programming Languages
27        Programming Languages
28        Programming Languages

                           work_experience.attributes
0   [{'role': 'Software Engineering Fellowship', '...
1   [{'role': 'Full-stack Developer', 'uuid': '323...
2                                                  []
3   [{'role': 'Data engineering, Machine learning ...
4   [{'role': 'Software Engineer', 'uuid': '04d46b...
5   [{'role': 'Scientific Director 2', 'uuid': '96...
6   [{'role': 'Data Engineering, Machine Learning ...
7   [{'role': 'Trainee', 'uuid': 'a6b84dd1-82ee-41...
8   [{'role': 'Trainee', 'uuid': 'a0a12547-8951-49...
9   [{'role': 'Data Engineering, Machine Learning ...
10  [{'role': 'Outreachy Intern', 'uuid': 'd1fc73f...
11  [{'role': ' Data Engineer, Generative AI, Mach...
12  [{'role': 'Machine Learning Engineering Traine...
13  [{'role': 'LLM Engineer(Contributor)', 'uuid':...
14  [{'role': 'DevOps Engineer', 'uuid': 'e2c7bb25...
15  [{'role': 'Assistant Researcher', 'uuid': '968...
16  [{'role': 'Machine Learning Engineer', 'uuid':...
17                                                 []
18  [{'role': 'Project Officer', 'uuid': '8e9fc101...
19  [{'role': 'Data Engineering, Machine Learning ...
20  [{'role': 'Web Developer', 'uuid': 'd5e2ccfa-d...
21  [{'role': 'Generative AI,ML and Data Engineer ...
22  [{'role': 'Generative AI, Machine Learning, Da...
23  [{'role': 'Trainee Generative AI Engineer | Ma...
24  [{'role': 'Machine Learning Engineer', 'uuid':...
25  [{'role': 'Data Engineering, Machine Learning ...
26  [{'role': 'Intelligent Systems Researcher', 'u...
27  [{'role': 'Data Engineering, Machine Learning ...
28  [{'role': 'Data Engineering, Machine Learning ...

[29 rows x 35 columns]

In [29]:
def dict_to_dataframe(data_dict):
    # Extract relevant fields
    job_profile_id = data_dict.get('job_profile_id', None)
    required_qualifications = data_dict.get('attributes', {}).get('required_qualifications', [])
    duties_responsibilities = data_dict.get('attributes', {}).get('duties_responsibilities', [])
    purpose = data_dict.get('attributes', {}).get('purpose', '')
    role = data_dict.get('attributes', {}).get('role', '')

    # Extract competencies
    competencies_list = []
    competencies = data_dict.get('attributes', {}).get('competencies', [])
    for competency in competencies:
        competencies_list.append({
            'name': competency.get('name', ''),
            'skills': competency.get('skills', []),
            'sfia_level': competency.get('sfia_level', ''),
            'summary': competency.get('summary', '')
        })

    # Create DataFrame with extracted fields
    df = pd.DataFrame([{
        'job_profile_id': job_profile_id,
        'required_qualifications': required_qualifications,
        'duties_responsibilities': duties_responsibilities,
        'purpose': purpose,
        'role': role,
        'competencies': competencies_list
    }])
    
    return df

In [30]:
import os
def process_json_files_in_folder(folder_path):
    all_dfs = []  # To store DataFrames from all JSON files

    # Iterate through each file in the folder
    for filename in os.listdir(folder_path):
        if filename.endswith('.json'):  # Only process JSON files
            file_path = os.path.join(folder_path, filename)

            # Read the JSON file
            with open(file_path, 'r') as file:
                data_dict = json.load(file)
            
            # Convert JSON to DataFrame and append to the list
            df = dict_to_dataframe(data_dict)
            all_dfs.append(df)

    # Combine all DataFrames into one
    final_df = pd.concat(all_dfs, ignore_index=True)
    
    return final_df

In [57]:
folder_path = './dataset/job_data'
final_df = process_json_files_in_folder(folder_path)

# Save the combined DataFrame to a CSV or display
final_df.to_csv('./dataset/combined_job_data.csv', index=False)

In [58]:
df = pd.read_csv("./dataset/combined_job_data.csv")
df.head()

,job_profile_id,required_qualifications,duties_responsibilities,purpose,role,competencies
0,1113,['Strong proficiency in Python and its data sc...,"['Collect, clean, and preprocess data from var...",To extract insights and knowledge from large a...,"Data Scientist (Python, Machine Learning)","[{'name': 'Programming Languages', 'skills': [..."
1,1087,"['Some software engineering experience.', 'Deg...",['Contribute to the AI Automation Platform for...,The role aims to develop and maintain scalable...,"(Senior) Backend Developer (Python, ML, Cloud)...","[{'name': 'Programming Languages', 'skills': [..."
2,1050,Advanced generative AI proficiency with the us...,Create and improve autonomous support platform...,Harness the power of GenAI to redefine busines...,"Machine Learning Engineer, IgniteTech (Remote)...","[{'name': 'Generative AI', 'skills': ['Advance..."
3,1030,['Experience with Python for prototyping algor...,['Consulting with R&D team to determine and re...,To design and optimize state-of-the-art comput...,Computer Vision Engineer,"[{'name': 'Programming Languages', 'skills': [..."
4,1032,['Fluency in English with the ability to artic...,['Assess the quality of AI-generated code and ...,Shape the future of AI by leveraging subject-m...,"Software Engineer - AI Training (Freelance, Re...","[{'name': 'Programming Languages', 'skills': [..."

In [65]:
df_match = pd.read_csv("./dataset/job_match.csv")
df_match.head()

,Unnamed: 0,user_job_match_id,job_profile_id,user_profile_id,category,slug,tags,match_score,match_level,match_summary,...,match_attributes_match_detail_ujc_similarity_score,match_attributes_match_detail_best_matched_user_competency,match_attributes_match_algorithm,match_attributes_overall_match_score,match_attributes_overall_match_degree,createdAt,match_attributes_applyLink,feedback_attributes_reaction_attributes_comment,feedback_attributes_reaction_attributes_section,feedback_attributes_reaction_attributes_user_reaction
0,0,1558,1035,197,openai_chatgpt_match,"job_profile_id:1035, user_profile_id:197, vers...",NaN,95.0,very_high,Overall match score is the average of all matc...,...,0.90,communication,vector_matching,95,very high,2024-09-19T11:30:30.003Z,NaN,NaN,NaN,NaN
1,1,1557,1041,197,openai_chatgpt_match,"job_profile_id:1041, user_profile_id:197, vers...",NaN,94.0,very_high,Overall match score is the average of all matc...,...,0.91,bi analytics,vector_matching,94,very high,2024-09-19T11:30:27.012Z,NaN,NaN,NaN,NaN
2,2,1556,1082,197,openai_chatgpt_match,"job_profile_id:1082, user_profile_id:197, vers...",NaN,86.0,high,Overall match score is the average of all matc...,...,0.74,data engineering,vector_matching,86,high,2024-09-19T11:30:23.764Z,NaN,NaN,NaN,NaN
3,3,1555,1086,197,openai_chatgpt_match,"job_profile_id:1086, user_profile_id:197, vers...",NaN,96.0,very_high,Overall match score is the average of all matc...,...,0.85,backend development,vector_matching,96,very high,2024-09-19T11:30:21.097Z,NaN,NaN,NaN,NaN
4,4,1554,1003,197,openai_chatgpt_match,"job_profile_id:1003, user_profile_id:197, vers...",NaN,97.0,very_high,Overall match score is the average of all matc...,...,0.95,collaboration,vector_matching,97,very high,2024-09-19T11:30:18.135Z,NaN,NaN,NaN,NaN

In [66]:
df_merge = df.merge(df_match, how="inner", on="job_profile_id")

In [67]:
df_merge.head()

,job_profile_id,required_qualifications,duties_responsibilities,purpose,role,competencies,Unnamed: 0,user_job_match_id,user_profile_id,category,...,match_attributes_match_detail_ujc_similarity_score,match_attributes_match_detail_best_matched_user_competency,match_attributes_match_algorithm,match_attributes_overall_match_score,match_attributes_overall_match_degree,createdAt,match_attributes_applyLink,feedback_attributes_reaction_attributes_comment,feedback_attributes_reaction_attributes_section,feedback_attributes_reaction_attributes_user_reaction
0,1040,"Proficient in designing, developing, and evalu...","Utilize NLP techniques to preprocess, analyze,...",To provide early career talent with an immersi...,Data Scientist (NLP),"[{'name': 'Data Analysis', 'skills': ['data mo...",29,1529,197,openai_chatgpt_match,...,0.98,programming language,vector_matching,99,very high,2024-09-18T06:19:55.634Z,NaN,NaN,NaN,NaN
1,1086,['Enrollment in 3rd or 4th year of a Software ...,['Writing production code and deploying new fe...,Offer an engaging and practical co-op experien...,Software Developer Co-op,"[{'name': 'Programming Languages', 'skills': [...",3,1555,197,openai_chatgpt_match,...,0.85,backend development,vector_matching,96,very high,2024-09-19T11:30:21.097Z,NaN,NaN,NaN,NaN
2,1041,"['BSc degree in Computer Science, Mathematics,...","['Lead technical projects, allocate effort, pl...","Lead technical projects, define technical spec...",R&amp;D - AI Engineer (Mid) / Horizon Project ...,"[{'name': 'Technical Project Management', 'ski...",1,1557,197,openai_chatgpt_match,...,0.91,bi analytics,vector_matching,94,very high,2024-09-19T11:30:27.012Z,NaN,NaN,NaN,NaN
3,1045,"Bachelor's degree in STEM (Computer Science, M...","Conduct R&D in computer vision, image processi...","To conduct R&D in computer vision, image proce...",Ml research engineer (remote),"[{'name': 'Machine Learning', 'skills': ['deep...",6,1552,197,openai_chatgpt_match,...,0.90,communication,vector_matching,92,very high,2024-09-19T11:30:15.088Z,NaN,NaN,NaN,NaN
4,1058,"[""Bachelor's or equivalent in Computer Science...","['Build robust, scalable, leading-edge contain...",To develop tools and technology for building a...,Software Engineer - Python - Container Images,"[{'name': 'Container Management', 'skills': ['...",14,1544,197,openai_chatgpt_match,...,0.90,communication,vector_matching,83,high,2024-09-19T11:30:01.631Z,NaN,NaN,NaN,NaN

In [68]:
df_merge['user_profile_id'].unique()

array([197])

In [51]:
matched = df_merge[["job_profile_id", "user_profile_id", "match_attributes_overall_match_score", "match_attributes_overall_match_degree"]]

In [53]:
matched.head()

,job_profile_id,user_profile_id,match_attributes_overall_match_score,match_attributes_overall_match_degree
0,1040,197,99,very high
1,1086,197,96,very high
2,1041,197,94,very high
3,1045,197,92,very high
4,1058,197,83,high
5,1068,197,93,very high
6,1060,197,94,very high
7,1028,197,93,very high
8,1082,197,86,high
9,1035,197,95,very high
10,1062,197,86,high
11,1080,197,91,very high

In [50]:
filtered_df = matched[matched['match_attributes_overall_match_degree'].isin(["very high", "high"])]
filtered_df

,job_profile_id,user_profile_id,match_attributes_overall_match_score,match_attributes_overall_match_degree
0,1040,197,99,very high
1,1086,197,96,very high
2,1041,197,94,very high
3,1045,197,92,very high
4,1058,197,83,high
5,1068,197,93,very high
6,1060,197,94,very high
7,1028,197,93,very high
8,1082,197,86,high
9,1035,197,95,very high
10,1062,197,86,high
11,1080,197,91,very high

In [79]:
# filtered_df.to_csv("./dataset/final/job_match.csv")
job_match = pd.read_csv("./dataset/final/job_match.csv")
job_match['user_profile_id'].unique()

array([23, 16, 13, 29, 25])

In [69]:
import pandas as pd
import os
import json

# Specify the folder containing JSON files
folder_path = './dataset/job_data/'

# Create an empty list to hold DataFrames
dataframes = []

# Loop through all files in the directory
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        
        # Read the JSON file
        with open(file_path, 'r') as file:
            data = json.load(file)
            df = pd.json_normalize(data)  # Converts JSON to DataFrame
            dataframes.append(df)

# Concatenate all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a CSV file
combined_df.to_csv('./dataset/job_json_combine_data.csv', index=False)

print("CSV file has been created successfully!")

CSV file has been created successfully!

In [31]:
dff = pd.read_csv('./dataset/combined_job_data.csv')
dff

,job_profile_id,required_qualifications,duties_responsibilities,purpose,role,competencies
0,1113,['Strong proficiency in Python and its data sc...,"['Collect, clean, and preprocess data from var...",To extract insights and knowledge from large a...,"Data Scientist (Python, Machine Learning)","[{'name': 'Programming Languages', 'skills': [..."
1,1087,"['Some software engineering experience.', 'Deg...",['Contribute to the AI Automation Platform for...,The role aims to develop and maintain scalable...,"(Senior) Backend Developer (Python, ML, Cloud)...","[{'name': 'Programming Languages', 'skills': [..."
2,1050,Advanced generative AI proficiency with the us...,Create and improve autonomous support platform...,Harness the power of GenAI to redefine busines...,"Machine Learning Engineer, IgniteTech (Remote)...","[{'name': 'Generative AI', 'skills': ['Advance..."
3,1030,['Experience with Python for prototyping algor...,['Consulting with R&D team to determine and re...,To design and optimize state-of-the-art comput...,Computer Vision Engineer,"[{'name': 'Programming Languages', 'skills': [..."
4,1032,['Fluency in English with the ability to artic...,['Assess the quality of AI-generated code and ...,Shape the future of AI by leveraging subject-m...,"Software Engineer - AI Training (Freelance, Re...","[{'name': 'Programming Languages', 'skills': [..."
...,...,...,...,...,...,...
95,1049,"['Advanced generative AI proficiency (i.e., us...",['Designing and building high-quality AI autom...,To design and build high-quality AI automation...,"Machine Learning Engineer, Trilogy (Remote) - ...","[{'name': 'Generative AI', 'skills': ['AI tool..."
96,1034,"['A degree in Computer Science, Machine Learni...",['Collaborate with cross-functional teams to d...,To develop and deploy Conversational AI applic...,Machine Learning Engineer - Conversational AI ...,"[{'name': 'Machine Learning', 'skills': ['Deve..."
97,1033,"['2+ years of professional experience in AI, D...",['Deliver comprehensive training programs cove...,"To deliver engaging, practical, and cutting-ed...",Artificial Intelligence (AI) Trainer,"[{'name': 'Data Science', 'skills': ['data_ana..."
98,1064,"['knowledge of Python and JavaScript', 'experi...",Maintenance and further development of the com...,To maintain and further develop the company’s ...,Python fullstack developer,"[{'name': 'Programming Languages', 'skills': [..."
99,1112,"• Bachelor's degree in Computer Science, Infor...",• Work with the IT Data Engineering Team and a...,To support the IT organization's data strategy...,IT Data Engineer,"[{'name': 'Data Engineering', 'skills': ['data..."

In [81]:
filter_job_match = pd.read_csv('./dataset/final/job_match.csv')
json_data = filter_job_match.to_json(orient='records', lines=True)

with open('./dataset/final/job_match.json', 'w') as json_file:
    json_file.write(json_data)

In [32]:
job_profile_ids = [1040, 1086, 1041, 1045, 1058, 1068, 1060, 1028, 1082, 1035, 1062,1080]

filtered_job_profiles = dff[dff['job_profile_id'].isin(job_profile_ids)]

len(filtered_job_profiles)

json_data = filtered_job_profiles.to_json(orient='records', lines=True)

with open('./dataset/final/job_profiles.json', 'w') as json_file:
    json_file.write(json_data)

In [74]:
folder_path = './dataset/trainees_profile_latest/'

# Create an empty list to hold DataFrames
dataframes = []

# Loop through all files in the directory
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        
        # Read the JSON file
        with open(file_path, 'r') as file:
            data = json.load(file)
            df = pd.json_normalize(data)  # Converts JSON to DataFrame
            dataframes.append(df)

# Concatenate all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a CSV file
combined_df.to_csv('./dataset/user_profile_data.csv', index=False)

print("CSV file has been created successfully!")

CSV file has been created successfully!

In [38]:
dff_user = pd.read_csv('./dataset/extract_user_profile_with_comptency.csv', index_col=0)
dff_user.columns

Index(['name', 'description', 'user_profile_id', 'basics.attributes',
       'basics.description', 'projects.display', 'projects.attributes',
       'projects.description', 'projects.profile_type', 'education.display',
       'education.attributes', 'education.description', 'interests.display',
       'interests.description', 'languages.display', 'languages.attributes',
       'languages.description', 'volunteer.display', 'volunteer.description',
       'references.display', 'references.description', 'achievements.display',
       'achievements.description', 'certificates.display',
       'certificates.attributes', 'certificates.description',
       'competencies.display', 'competencies.attributes',
       'publications.display', 'publications.description',
       'publications.profile_type', 'work_experience.display',
       'programing_languages.description', 'programing_languages.display',
       'work_experience.attributes'],
      dtype='object')

In [39]:
user_profile_ids = [23, 16, 13, 29, 25]

filtered_user_profiles = dff_user[dff_user['user_profile_id'].isin(user_profile_ids)]

len(filtered_user_profiles)
json_data = filtered_user_profiles.to_json(orient='records', lines=True)

with open('./dataset/final/user_profiles_with_comptency.json', 'w') as json_file:
    json_file.write(json_data)

In [87]:
import ast, json
projects =  "[{'url': 'None', 'uuid': 'c4adfcce-acac-486b-b4d4-07955fb16e0f', 'title': 'Automated Storyboard Synthesis for Digital Advertising', 'tools': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-05T02:25:36.083421'}], 'summary': 'Developed a machine learning solution to automate the conversion of textual advertisement concepts into detailed visual storyboards. Utilized advanced deep learning frameworks, image segmentation, and LLM-based agents for asset analysis, generation, and composition, streamlining the ad creation process for digital advertising campaigns.', 'end_date': '', 'focus_area': '', 'highlights': [], 'start_date': '', 'verified_by': '', 'requested_by': ''}, {'url': 'None', 'uuid': 'd80ab376-13a6-47b2-bebf-7cb6e031e3e2', 'title': 'LLM Finetuning: Enabling Quality Embedding and Text Generation for Amharic Language', 'tools': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-05T02:25:36.083479'}], 'summary': 'Enhanced NLP for Amharic by fine-tuning LLaMA-2. Key steps included implementing model quantization, preprocessing data and finetuning the model. Initial results showed promise in text generation and question answering. Future improvements will focus on  enhancing the fine-tuning process for better performance.', 'end_date': '', 'focus_area': '', 'highlights': [], 'start_date': '', 'verified_by': '', 'requested_by': ''}, {'url': 'None', 'uuid': 'e8033426-399d-4a61-84d8-20c2074cc1dd', 'title': 'Precision RAG: Prompt Tuning For Building Enterprise Grade RAG Systems', 'tools': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-05T02:25:36.083529'}], 'summary': \"The Prompt Generation System is an automated tool designed to assist users in generating multiple prompt options based on their input descriptions of tasks, objectives, and scenarios. The system employs sophisticated algorithms and evaluation metrics to ensure that the generated prompts align with the user's requirements.\", 'end_date': '', 'focus_area': '', 'highlights': [], 'start_date': '', 'verified_by': '', 'requested_by': ''}]"

In [85]:
new = ast.literal_eval(projects)
type(new)

list

In [91]:
# Convert the list to JSON
json_output = json.dumps(new, indent=4)

# Print the JSON output
print(json_output)

# Optionally, save to a JSON file
with open('output.json', 'w') as json_file:
    json_file.write(json_output)

[
    {
        "url": "None",
        "uuid": "c4adfcce-acac-486b-b4d4-07955fb16e0f",
        "title": "Automated Storyboard Synthesis for Digital Advertising",
        "tools": [],
        "status": "approved",
        "history": [
            {
                "blob": "",
                "user": "2151",
                "status": "approved",
                "timestamp": "2024-08-05T02:25:36.083421"
            }
        ],
        "summary": "Developed a machine learning solution to automate the conversion of textual advertisement concepts into detailed visual storyboards. Utilized advanced deep learning frameworks, image segmentation, and LLM-based agents for asset analysis, generation, and composition, streamlining the ad creation process for digital advertising campaigns.",
        "end_date": "",
        "focus_area": "",
        "highlights": [],
        "start_date": "",
        "verified_by": "",
        "requested_by": ""
    },
    {
        "url": "None",
        "uuid": "d80ab376-13a6-47b2-bebf-7cb6e031e3e2",
        "title": "LLM Finetuning: Enabling Quality Embedding and Text Generation for Amharic Language",
        "tools": [],
        "status": "approved",
        "history": [
            {
                "blob": "",
                "user": "2151",
                "status": "approved",
                "timestamp": "2024-08-05T02:25:36.083479"
            }
        ],
        "summary": "Enhanced NLP for Amharic by fine-tuning LLaMA-2. Key steps included implementing model quantization, preprocessing data and finetuning the model. Initial results showed promise in text generation and question answering. Future improvements will focus on  enhancing the fine-tuning process for better performance.",
        "end_date": "",
        "focus_area": "",
        "highlights": [],
        "start_date": "",
        "verified_by": "",
        "requested_by": ""
    },
    {
        "url": "None",
        "uuid": "e8033426-399d-4a61-84d8-20c2074cc1dd",
        "title": "Precision RAG: Prompt Tuning For Building Enterprise Grade RAG Systems",
        "tools": [],
        "status": "approved",
        "history": [
            {
                "blob": "",
                "user": "2151",
                "status": "approved",
                "timestamp": "2024-08-05T02:25:36.083529"
            }
        ],
        "summary": "The Prompt Generation System is an automated tool designed to assist users in generating multiple prompt options based on their input descriptions of tasks, objectives, and scenarios. The system employs sophisticated algorithms and evaluation metrics to ensure that the generated prompts align with the user's requirements.",
        "end_date": "",
        "focus_area": "",
        "highlights": [],
        "start_date": "",
        "verified_by": "",
        "requested_by": ""
    }
]

In [ ]:
# Loop through each item in the data list
for item in data:
    for key in item:
        # Convert the string representation of the list of dictionaries to actual list
        try:
            attributes_list = ast.literal_eval(item[key])
            # Convert the list of dictionaries to JSON
            attributes_json = json.dumps(attributes_list)
            item[key] = attributes_json  # Update the item with JSON representation
        except Exception as e:
            print(f"Error processing {key}: {e}")

# Print the updated data
print(json.dumps(data, indent=2))

In [6]:
import os
def file_reader(path: str) -> str:
    try:
       
        fname = os.path.join(path)
        with open(fname, 'r') as f:
            system_message = f.read()
        return system_message
    
    except Exception as e:
        return f'Error: {str(e)}'
    
# jbPath = '\n'.join(str(item) for item in data['user']['jbPath'])
# cvPath = '\n'.join(str(item) for item in profile)
# cvPath

In [6]:
profile_txt = """
    You are an experienced HR analyst, here is the documents you need to do the analysis
    - The JD(job description) in JSON format: {jd} 
    - The CV(curriculum vitae) in JSON format: {cv}

You job is to analyse the CV and the JD, and provide your analysis. 
"""

In [15]:
import json
jbPath=str(profile)
cvPath="json.loads(recieved.cvPath)"

context = str(profile_txt)
msg = context\
        .replace("{jd}", jbPath)\
        .replace("{cv}", cvPath)

In [16]:
print("#######jbPath#######")
msg

#######jbPath#######

'\n    You are an experienced HR analyst, here is the documents you need to do the analysis\n    - The JD(job description) in JSON format: {\'name\': \'Abraham Teka\', \'display\': \'User Profile\', \'description\': \'User profile information\', \'profile_type\': \'user_profile\', \'user_profile_id\': 16, \'awards.code\': \'awards\', \'awards.name\': \'awards\', \'awards.display\': \'Awards\', \'awards.template\': \'form\', \'awards.attributes\': [], \'awards.description\': \'Awards received by the user\', \'awards.profile_type\': \'awards\', \'basics.code\': \'basics\', \'basics.name\': \'basics\', \'basics.display\': \'Basics\', \'basics.template\': \'form\', \'basics.attributes\': \'[{\\\'role\\\': \\\'Generative AI Engineer | Software Engineer | Machine Learning | Cloud Solutions (Azure, AWS) | Advocate for Continuous Improvement\\\', \\\'uuid\\\': \\\'e0eab10e-67ca-47c1-b89d-cd38f78037bc\\\', \\\'email\\\': \\\'aberhamyirsaw@gmail.com\\\', \\\'image\\\': \\\'\\\', \\\'media\\\': [], \\\'phone\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-15T05:55:43.666429\\\'}], \\\'location\\\': {\\\'city\\\': \\\'\\\', \\\'icon\\\': \\\'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain\\\', \\\'region\\\': \\\'\\\', \\\'address\\\': \\\'Ethiopia\\\', \\\'country\\\': \\\'US\\\', \\\'postal_code\\\': \\\'\\\'}, \\\'full_name\\\': \\\'Abraham Teka\\\', \\\'name_title\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\', \\\'personal_statement\\\': "Abraham Teka here, ambitious about advancing software solutions through Generative AI and cloud computing. With certifications in Azure and AWS, I specialize in RAG systems, prompt engineering, and LLM fine-tuning. I aim to innovate and drive technological advancements in AI and software engineering. Let\\\'s connect and build intelligent solutions that make technology beneficial to everyone!"}]\', \'basics.description\': \'Basic information about the user\', \'basics.profile_type\': \'basics\', \'projects.code\': \'projects\', \'projects.name\': \'projects\', \'projects.display\': \'Projects\', \'projects.template\': \'form\', \'projects.attributes\': \'[{\\\'url\\\': \\\'None\\\', \\\'uuid\\\': \\\'c4adfcce-acac-486b-b4d4-07955fb16e0f\\\', \\\'title\\\': \\\'Automated Storyboard Synthesis for Digital Advertising\\\', \\\'tools\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083421\\\'}], \\\'summary\\\': \\\'Developed a machine learning solution to automate the conversion of textual advertisement concepts into detailed visual storyboards. Utilized advanced deep learning frameworks, image segmentation, and LLM-based agents for asset analysis, generation, and composition, streamlining the ad creation process for digital advertising campaigns.\\\', \\\'end_date\\\': \\\'\\\', \\\'focus_area\\\': \\\'\\\', \\\'highlights\\\': [], \\\'start_date\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\'}, {\\\'url\\\': \\\'None\\\', \\\'uuid\\\': \\\'d80ab376-13a6-47b2-bebf-7cb6e031e3e2\\\', \\\'title\\\': \\\'LLM Finetuning: Enabling Quality Embedding and Text Generation for Amharic Language\\\', \\\'tools\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083479\\\'}], \\\'summary\\\': \\\'Enhanced NLP for Amharic by fine-tuning LLaMA-2. Key steps included implementing model quantization, preprocessing data and finetuning the model. Initial results showed promise in text generation and question answering. Future improvements will focus on  enhancing the fine-tuning process for better performance.\\\', \\\'end_date\\\': \\\'\\\', \\\'focus_area\\\': \\\'\\\', \\\'highlights\\\': [], \\\'start_date\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\'}, {\\\'url\\\': \\\'None\\\', \\\'uuid\\\': \\\'e8033426-399d-4a61-84d8-20c2074cc1dd\\\', \\\'title\\\': \\\'Precision RAG: Prompt Tuning For Building Enterprise Grade RAG Systems\\\', \\\'tools\\\': [], \\\'status\\\': \\\'approved\\\', \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083529\\\'}], \\\'summary\\\': "The Prompt Generation System is an automated tool designed to assist users in generating multiple prompt options based on their input descriptions of tasks, objectives, and scenarios. The system employs sophisticated algorithms and evaluation metrics to ensure that the generated prompts align with the user\\\'s requirements.", \\\'end_date\\\': \\\'\\\', \\\'focus_area\\\': \\\'\\\', \\\'highlights\\\': [], \\\'start_date\\\': \\\'\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\'}]\', \'projects.description\': \'Projects the user has worked on\', \'projects.profile_type\': \'projects\', \'education.code\': \'education\', \'education.name\': \'education\', \'education.display\': \'Education\', \'education.template\': \'form\', \'education.attributes\': \'[{\\\'uuid\\\': \\\'a7537ae7-18ae-4fd4-b253-0204a681e437\\\', \\\'score\\\': \\\'\\\', \\\'remark\\\': \\\'\\\', \\\'status\\\': \\\'approved\\\', \\\'country\\\': \\\'\\\', \\\'courses\\\': [], \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083597\\\'}], \\\'end_date\\\': \\\'2024-07-31\\\', \\\'start_date\\\': \\\'2024-04-30\\\', \\\'study_area\\\': \\\'\\\', \\\'study_type\\\': \\\'Generative AI, Data Engineering & Machine Learning\\\', \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\', \\\'institution_url\\\': \\\'\\\', \\\'institution_name\\\': \\\'10 Academy\\\'}, {\\\'uuid\\\': \\\'f58152c2-32a3-40f4-bd15-038a65cf0931\\\', \\\'score\\\': \\\'3.4\\\', \\\'remark\\\': \\\'\\\', \\\'status\\\': \\\'approved\\\', \\\'country\\\': \\\'\\\', \\\'courses\\\': [], \\\'history\\\': [{\\\'blob\\\': \\\'\\\', \\\'user\\\': \\\'2151\\\', \\\'status\\\': \\\'approved\\\', \\\'timestamp\\\': \\\'2024-08-05T02:25:36.083649\\\'}], \\\'end_date\\\': \\\'2022-06-30\\\', \\\'start_date\\\': \\\'2017-09-30\\\', \\\'study_area\\\': \\\'Software Engineering\\\', \\\'study_type\\\': "Bachelor\\\'s degree", \\\'verified_by\\\': \\\'\\\', \\\'requested_by\\\': \\\'\\\', \\\'institution_url\\\': \\\'\\\', \\\'institution_name\\\': \\\'Bahir Dar University\\\'}]\', \'education.description\': \'Educational background of the user\', \'education.profile_type\': \'education\', \'interests.code\': \'interests\', \'interests.name\': \'interests\', \'interests.display\': \'Interests\', \'interests.template\': \'form\', \'interests.attributes\': [], \'interests.description\': \'Interests of the user\', \'interests.profile_type\': \'interests\', \'languages.code\': \'languages\', \'languages.name\': \'languages\', \'languages.display\': \'Languages\', \'languages.template\': \'form\', \'languages.attributes\': "[{\'uuid\': \'7a659bec-40a5-483c-8d93-ae75561bfc7a\', \'status\': \'approved\', \'fluency\': \'Native Speaker\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083689\'}], \'language\': \'English\', \'verified_by\': \'\', \'requested_by\': \'\'}]", \'languages.description\': \'Languages spoken by the user\', \'languages.profile_type\': \'languages\', \'volunteer.code\': \'volunteer\', \'volunteer.name\': \'volunteer\', \'volunteer.display\': \'Volunteer Work\', \'volunteer.template\': \'form\', \'volunteer.attributes\': [], \'volunteer.description\': \'Volunteer work of the user\', \'volunteer.profile_type\': \'volunteer\', \'references.code\': \'references\', \'references.name\': \'references\', \'references.display\': \'References\', \'references.template\': \'form\', \'references.attributes\': [], \'references.description\': \'References of the user\', \'references.profile_type\': \'references\', \'achievements.code\': \'achievements\', \'achievements.name\': \'achievements\', \'achievements.display\': \'Achievements\', \'achievements.template\': \'form\', \'achievements.attributes\': [], \'achievements.description\': \'Achievements of the user\', \'achievements.profile_type\': \'achievements\', \'certificates.code\': \'certificates\', \'certificates.name\': \'certificates\', \'certificates.display\': \'Certificates\', \'certificates.template\': \'form\', \'certificates.attributes\': "[{\'url\': \'https://learn.microsoft.com/api/credentials/share/en-us/AbrahamYT-4943/E0A02D871CD533ED?sharingId=7A7DE93C2D817883\', \'date\': \'\', \'name\': \'Microsoft Certified: Azure Fundamentals\', \'uuid\': \'3961d92e-bfaa-425b-9d75-5bae2da0296b\', \'issuer\': \'Microsoft\', \'status\': \'approved\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083735\'}], \'verified_by\': \'\', \'requested_by\': \'\'}, {\'url\': \'https://www.credly.com/badges/2e03cc29-77eb-4537-9938-e41abd474da5/public_url\', \'date\': \'\', \'name\': \'Amazon Web Services Cloud Practitioner\', \'uuid\': \'428a1f5b-8c3c-443d-b4bf-fb8aab8f81d7\', \'issuer\': \'Amazon Web Services (AWS)\', \'status\': \'approved\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083770\'}], \'verified_by\': \'\', \'requested_by\': \'\'}]", \'certificates.description\': \'Certificates and awards of the user\', \'certificates.profile_type\': \'certificates\', \'competencies.code\': \'competencies\', \'competencies.name\': \'competencies\', \'competencies.display\': \'Competencies\', \'competencies.template\': \'form\', \'competencies.attributes\': "[{\'name\': \'programming language\', \'uuid\': \'4760cbf8-1cb4-4164-ab94-6e2ecc7ef74e\', \'others\': [], \'skills\': [\'python\', \'javaScript\', \'django\'], \'status\': \'approved\', \'display\': \'Programming Language\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.083990\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \'positive\', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \'high\', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has sound generic, domain, and specialist knowledge necessary for effective performance, typically gained from recognized bodies of knowledge and organizational information. Understands and effectively applies appropriate methods, tools, applications, and processes. Demonstrates judgment and a systematic approach to work, applies a methodical approach to routine and moderately complex issue definition and resolution, may oversee others or make decisions impacting routine work assigned to individuals or project stages, and works under general direction with specific guidance and milestone reviews.\', \'sfia_level\': \'3\', \'description\': \'A programming language is a way for programmers (developers) to communicate with computers. Programming languages consist of a set of rules that allows string values to be converted into various ways of generating machine code, or, in the case of visual programming languages, graphical elements.\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'data engineering\', \'uuid\': \'b1e2cf8f-5d7a-4b9e-ac18-60ecf6e484fe\', \'others\': [], \'skills\': [\'airflow\', \'aws\', \'big data\', \'dbt\', \'kafka\', \'mysql\', \'postgres\', \'sql\'], \'status\': \'approved\', \'display\': \'Data Engineering\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084207\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \'positive\', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \'high\', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \'positive\', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \'high\', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has gained basic domain knowledge and demonstrates application of essential generic knowledge typically found in industry bodies of knowledge. Absorbs new information when presented systematically and applies it effectively. Understands and uses appropriate methods, tools, applications, and processes. Shows a rational and organized approach to work, performs a range of activities in varied environments, interacts with and may influence immediate colleagues, and uses limited discretion in resolving issues or inquiries.\', \'sfia_level\': \'2\', \'description\': \'Data engineering is the process of designing and building systems that let people collect and analyze raw data from multiple sources and formats.\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'analytics engineering\', \'uuid\': \'bcff8234-3954-41db-88e7-34fe5bb0b11e\', \'others\': [], \'skills\': [\'airflow\', \'aws\', \'dbt\', \'kafka\', \'postgres\', \'sql\'], \'status\': \'approved\', \'display\': \'Analytics Engineering\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084414\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has gained basic domain knowledge and demonstrates application of essential generic knowledge typically found in industry bodies of knowledge. Absorbs new information when presented systematically and applies it effectively. Understands and uses appropriate methods, tools, applications, and processes. Shows a rational and organized approach to work, performs a range of activities in varied environments, interacts with and may influence immediate colleagues, and uses limited discretion in resolving issues or inquiries.\', \'sfia_level\': \'2\', \'description\': \'Analytics engineering is a discipline that focuses on designing, constructing, and maintaining data infrastructure and data pipelines. Analytics engineers bridge the gap between data science and data engineering by transforming raw data into clean, reliable datasets that can be easily analyzed by data analysts and data scientists\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'automation \', \'uuid\': \'6782c8eb-3d02-43f3-9d67-5c63c22c10a7\', \'others\': [], \'skills\': [\'airflow\', \'aws\', \'cicd\', \'cml\', \'dbt\', \'docker\', \'git\', \'hyper parameter tuning\', \'linux\', \'ml pipeline\', \'mlflow\', \'unit testng\'], \'status\': \'approved\', \'display\': \'Automation \', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084619\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has sound generic, domain, and specialist knowledge necessary for effective performance, typically gained from recognized bodies of knowledge and organizational information. Understands and effectively applies appropriate methods, tools, applications, and processes. Demonstrates judgment and a systematic approach to work, applies a methodical approach to routine and moderately complex issue definition and resolution, may oversee others or make decisions impacting routine work assigned to individuals or project stages, and works under general direction with specific guidance and milestone reviews.\', \'sfia_level\': \'3\', \'description\': \' Automation in machine learning (ML) and data engineering involves using tools and processes to streamline, simplify and enhance the development, deployment, and maintenance of ML models and data pipelines. This automation aims to improve efficiency, reduce errors, and enable scalability\', \'verified_by\': \'\', \'requested_by\': \'\', \'experience_level\': \'\', \'sfia_estimation_method\': \'observed\'}, {\'name\': \'mathematics\', \'uuid\': \'77348cb1-6083-4dc6-b5fc-d61eb237869b\', \'others\': [], \'skills\': [\'algorithm\', \'deep learning\', \'machine learning\', \'mathematics\'], \'status\': \'approved\', \'display\': \'Mathematics\', \'history\': [{\'blob\': \'\', \'user\': \'2151\', \'status\': \'approved\', \'timestamp\': \'2024-08-05T02:25:36.084820\'}], \'attitude\': [], \'evidence\': [{\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'github\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}, {\'remark\': \'\', \'source\': {\'link\': \'\', \'name\': \'grade\'}, \'status\': \'verified\', \'sentiment\': \' \', \'verified_by\': \'staff\', \'requested_by\': \'\', \'confidence_degree\': \' \', \'sfia_level_approved\': \'\', \'sfia_level_requested\': \'\', \'sfia_dimensions_approved\': [], \'sfia_dimensions_requested\': []}], \'abilities\': [], \'knowledge\': [], \'rationale\': \'Has gained basic domain knowledge and demonstrates application of essential generic knowledge typically found in industry bodies of knowledge. Absorbs new information when presented systematically and applies it effectively. Understands and uses appropriate methods, tools, applications, and processes. Shows a rational and organized approach to work, performs a range of activities in varied environments, interacts with and may influence immediate colleagues, and uses limited discretion in resolving issues or inquiries.\', \'sfia_level\': \'2\', \'description\': \'Mathema

In [5]:
import json, os, ast
import pandas as pd

In [76]:
with open("/home/rehmet/dev/tenx_ipersona/frontend/src/assets/mock-data/user_profiles.json", "r") as file:
    data = json.load(file)
# data

In [77]:
for item in data:
    if 'basics.attributes' in item:
        basic_attributes = []
        basic = ast.literal_eval(item['basics.attributes'])
        json.dumps(basic)
        print("got")
        print(basic)
        for x in basic:
            role = x.get('role')
            personal_statement = x.get('personal_statement')  
            if role and personal_statement: 
                basic_attributes.append({
                    'role': role,
                    'personal_statement': personal_statement
                })
        item['basics.attributes'] = basic_attributes       
        
    if 'projects.attributes' in item:
        project_attributes = []
        project = ast.literal_eval(item['projects.attributes'])
        json.dumps(project)
        for x in project:
            title = x.get('title')
            summary = x.get('summary')  
            if title and summary: 
                project_attributes.append({
                    'title': title,
                    'summary': summary
                })
        item['projects.attributes'] = project_attributes   
        
    if 'education.attributes' in item:
        education_attributes = []
        education = ast.literal_eval(item['education.attributes'])
        json.dumps(education)
        for x in education:
            study_area = x.get('study_area')
            study_type = x.get('study_type')
            institution_name = x.get('institution_name')  
            start_date = x.get('start_date')
            end_date = x.get('end_date')

            if study_area and study_type and institution_name and start_date and end_date: 
                education_attributes.append({
                    'study_area': study_area,
                    'study_type': study_type,
                    'institution_name': institution_name,
                    'start_date': start_date,
                    'end_date': end_date
                })
 
        item['education.attributes'] = education_attributes
        
    if 'work_experience.attributes' in item:
        work_attributes = []
        work = ast.literal_eval(item['work_experience.attributes'])
        json.dumps(work)
        for x in work:
            role = x.get('role')
            company = x.get('company')
            summary = x.get('summary')  
            start_date = x.get('start_date')
            end_date = x.get('end_date')

            if role and company and summary and start_date and end_date: 
                work_attributes.append({
                    'role': role,
                    'company': company,
                    'summary': summary,
                    'start_date': start_date,
                    'end_date': end_date
                })
                
        item['work_experience.attributes'] = work_attributes
        
# json.dumps(data)

got
[{'role': 'Generative AI Engineer | Software Engineer | Machine Learning | Cloud Solutions (Azure, AWS) | Advocate for Continuous Improvement', 'uuid': 'e0eab10e-67ca-47c1-b89d-cd38f78037bc', 'email': 'aberhamyirsaw@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2151', 'status': 'approved', 'timestamp': '2024-08-15T05:55:43.666429'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Ethiopia', 'country': 'US', 'postal_code': ''}, 'full_name': 'Abraham Teka', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': "Abraham Teka here, ambitious about advancing software solutions through Generative AI and cloud computing. With certifications in Azure and AWS, I specialize in RAG systems, prompt engineering, and LLM fine-tuning. I aim to innovate and drive technological advancements in AI and software engineering. Let's connect and build intelligent solutions that make technology beneficial to everyone!"}]
got
[{'role': 'Generative AI & ML Engineer | CTO | Computer & Software Engineer | Entrepreneur | RAG Systems | Data Warehouse Professional', 'uuid': '48df28a6-5d04-4a78-9d39-fb304ade1cf9', 'email': 'abubekershamil123@gmail.com', 'image': '', 'media': [{'icon': '', 'link': 'https://www.linkedin.com/in/abubeker-shamil/', 'name': 'LinkedIn'}, {'icon': '', 'link': 'https://github.com/dev-abuke', 'name': 'GitHub'}, {'icon': '', 'link': 'https://medium.com/@abubekershamil', 'name': 'Medium'}, {'icon': '', 'link': 'https://abubekershamil.com', 'name': 'Website'}], 'phone': [{'icon': 'https://pngimg.com/uploads/phone/phone_PNG48988.png', 'name': 'Main', 'value': '+251912121388'}], 'status': 'approved', 'history': [{'blob': '', 'user': '1974', 'status': 'approved', 'timestamp': '2024-08-17T08:55:50.435440'}], 'location': {'city': 'Addis Ababa', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Addis Ababa', 'country': 'Ethiopia', 'postal_code': ''}, 'full_name': 'Abubeker Shamil', 'name_title': 'Mr', 'verified_by': '', 'requested_by': '', 'personal_statement': 'Abubeker Shamil is a dedicated Software Engineer with proven leadership skills. Proficient in Python, JavaScript, fine-tuning LLMs, RAG systems, prompt engineering, Langchain, and various frameworks. Known for a problem-solving mindset, effective communication skills, and a collaborative attitude. Passionate about Generative AI and Technology, with experience in developing advanced NLP systems and optimizing data workflows.'}]
got
[{'role': 'Generative AI Engineer | Machine learning| Data engineering |Electrical engineer | Electrical lighting designer', 'uuid': 'a6c41abe-bf4b-4d20-ae7c-c9db8c7afcd6', 'email': 'bethelhem.mebratu.123@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2098', 'status': 'approved', 'timestamp': '2024-08-16T08:26:29.277183'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Ethiopia', 'country': 'US', 'postal_code': ''}, 'full_name': 'Bethelhem Mebratu', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': 'I am a junior Generative AI Engineer with a programming foundation and committed to advancing my skills in AI and technology . My expertise lies in Python, SQL and vector databases. I have hands on experience in building and fine-tuning Generative AI models,LLMs implementing RAG systems, and developing chatbots. Additionally, I am skilled in various data-related tasks such as analysis, processing, visualization, and building data warehouses.'}]
got
[{'role': 'Generative AI Engineer | Machine Learning | Software Engineer | Data Engineering', 'uuid': '69a9a5f2-fd0f-4355-8a3a-b09191913e5e', 'email': 'hillary6k@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2187', 'status': 'approved', 'timestamp': '2024-08-05T02:25:24.391717'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Kenya', 'country': 'US', 'postal_code': ''}, 'full_name': 'Hillary Kipkemoi', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': "I am Generative AI Engineer with solid foundation in mathematics and full-stack development. I'm skilled in building RAG systems, fine-tuning LLMs, prompt engineering, and building chatbot applications. I'm also proficient in Python, React, and MLOps tools & practices such as Kafka, Airflow and Github Actions.\n\nI am committed to continuous learning and research in the field of Artificial intelligence and actively exploring the latest advancements in NLP, generative AI to create impactful solutions."}]
got
[{'role': 'Generative AI Engineer | Machine Learning | Data Engineering | Application Support Engineer at ZamZam Bank', 'uuid': '573d1e46-b7c7-4c77-8aa9-b44f838bf535', 'email': 'mahbubah.abdulhakim12@gmail.com', 'image': '', 'media': [], 'phone': [], 'status': 'approved', 'history': [{'blob': '', 'user': '2116', 'status': 'approved', 'timestamp': '2024-08-05T02:25:39.965493'}], 'location': {'city': '', 'icon': 'https://th.bing.com/th/id/OIP.Vr0IsnNZaY3cxmBtOtSqqAHaNN?w=2555&h=4557&rs=1&pid=ImgDetMain', 'region': '', 'address': 'Ethiopia', 'country': 'US', 'postal_code': ''}, 'full_name': 'Mahbubah Abdulhakim', 'name_title': '', 'verified_by': '', 'requested_by': '', 'personal_statement': 'A junior generative AI Engineer with 3+ year experience in IT Industry, committed to advancing my skills in AI and technology. Proficient in Python, SQL, and vector databases. Specialized in fine-tuning LLMs, building RAG systems, prompt engineering and AI Chatbot development, with a strong foundation in neural networks and natural language processing (NLP). Demonstrated expertise through hands-on project work in these areas.'}]

In [78]:
json.loads(data)

TypeError: the JSON object must be str, bytes or bytearray, not list

In [67]:
# dat = ast.literal_eval(data)
type(data)
json.loads(str(data))

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

In [24]:
new_attributes = []
for item in data:
    if 'basics.attributes' in item:
        for x in item['basics.attributes']:
            role = x.get('role')
            personal_statement = x.get('personal_statement')  
            if role and personal_statement: 
                new_attributes.append({
                    'role': role,
                    'personal_statement': personal_statement
                })
                
new_attributes

[{'role': 'Generative AI Engineer | Software Engineer | Machine Learning | Cloud Solutions (Azure, AWS) | Advocate for Continuous Improvement',
  'personal_statement': "Abraham Teka here, ambitious about advancing software solutions through Generative AI and cloud computing. With certifications in Azure and AWS, I specialize in RAG systems, prompt engineering, and LLM fine-tuning. I aim to innovate and drive technological advancements in AI and software engineering. Let's connect and build intelligent solutions that make technology beneficial to everyone!"},
 {'role': 'Generative AI & ML Engineer | CTO | Computer & Software Engineer | Entrepreneur | RAG Systems | Data Warehouse Professional',
  'personal_statement': 'Abubeker Shamil is a dedicated Software Engineer with proven leadership skills. Proficient in Python, JavaScript, fine-tuning LLMs, RAG systems, prompt engineering, Langchain, and various frameworks. Known for a problem-solving mindset, effective communication skills, and a collaborative attitude. Passionate about Generative AI and Technology, with experience in developing advanced NLP systems and optimizing data workflows.'},
 {'role': 'Generative AI Engineer | Machine learning| Data engineering |Electrical engineer | Electrical lighting designer',
  'personal_statement': 'I am a junior Generative AI Engineer with a programming foundation and committed to advancing my skills in AI and technology . My expertise lies in Python, SQL and vector databases. I have hands on experience in building and fine-tuning Generative AI models,LLMs implementing RAG systems, and developing chatbots. Additionally, I am skilled in various data-related tasks such as analysis, processing, visualization, and building data warehouses.'},
 {'role': 'Generative AI Engineer | Machine Learning | Software Engineer | Data Engineering',
  'personal_statement': "I am Generative AI Engineer with solid foundation in mathematics and full-stack development. I'm skilled in building RAG systems, fine-tuning LLMs, prompt engineering, and building chatbot applications. I'm also proficient in Python, React, and MLOps tools & practices such as Kafka, Airflow and Github Actions.\n\nI am committed to continuous learning and research in the field of Artificial intelligence and actively exploring the latest advancements in NLP, generative AI to create impactful solutions."},
 {'role': 'Generative AI Engineer | Machine Learning | Data Engineering | Application Support Engineer at ZamZam Bank',
  'personal_statement': 'A junior generative AI Engineer with 3+ year experience in IT Industry, committed to advancing my skills in AI and technology. Proficient in Python, SQL, and vector databases. Specialized in fine-tuning LLMs, building RAG systems, prompt engineering and AI Chatbot development, with a strong foundation in neural networks and natural language processing (NLP). Demonstrated expertise through hands-on project work in these areas.'}]

In [ ]:
import pandas

:

In [4]:
chat = [{'user_type': 'candidate', 'content_type': 'answer', 'complete': False, 'content': {'response': '1', 'time_taken': '00:34', 'realtime_evaluation': 'null'}}, {'user_type': 'assistant', 'content_type': 'overall_feedback', 'complete': True, 'content': {'time_taken': 'null', 'response': {'question_number': '2', 'question': 'What relevant work experiences do you have that align with the responsibilities of a Machine Learning Research Engineer?', 'question_type': 'Background', 'time_limit': '02:00', 'end_message': 'Please take your time to provide a detailed response'}, 'realtime_evaluation': None}}, {'user_type': 'candidate', 'content_type': 'answer', 'complete': False, 'content': {'response': '2', 'time_taken': '03:05', 'realtime_evaluation': 'null'}}, {'user_type': 'assistant', 'content_type': 'question_feedback', 'complete': False, 'content': {'time_taken': 'null', 'response': {'question': 'Can you provide specific examples of projects or experiences that demonstrate your skills in machine learning or computer vision?', 'question_type': 'follow-up', 'time_limit': '02:00', 'end_message': 'Please take your time to provide a detailed response'}, 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response did not provide any relevant work experiences that align with the responsibilities of a Machine Learning Research Engineer. It is important to highlight specific projects or roles that demonstrate your skills and experience in machine learning, computer vision, or related areas.'}, 'answer_relevancy': [{'level': '20', 'reason': 'The response did not address the question at all, lacking any relevant details or examples.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'The response was unclear and did not convey any meaningful information.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was no engagement or enthusiasm in the response, making it difficult to assess your interest in the role.'}]}}}, {'user_type': 'candidate', 'content_type': 'answer', 'complete': False, 'content': {'response': '4', 'time_taken': '07:50', 'realtime_evaluation': 'null'}}, {'user_type': 'assistant', 'content_type': 'question_feedback', 'complete': False, 'content': {'time_taken': 'null', 'response': {'question_number': '4', 'question': 'What are some common machine learning and computer vision concepts you have worked with, and how do you stay updated with advancements in these fields?', 'question_type': 'Technical', 'time_limit': '02:30', 'end_message': 'Please take your time to provide a detailed response'}, 'realtime_evaluation': {'overall': {'relevance': 'weak', 'feedback': 'Your response suggested a lack of specific examples related to machine learning or computer vision projects. Providing concrete details about your experiences would strengthen your answer and demonstrate your skills more effectively.'}, 'answer_relevancy': [{'level': '40', 'reason': 'The response did not provide any specific examples or details, making it difficult to assess the relevance to the question.'}], 'communication_skills': [{'skill': 'clarity', 'level': 'Poor', 'reason': 'The response was vague and did not clearly convey any relevant information.'}, {'skill': 'engagement', 'level': 'Poor', 'reason': 'There was a lack of enthusiasm or detail in the response, which may indicate disinterest or uncertainty.'}]}}}]
global chat_count
chat_count = 1
assistant_count = sum(1 for entry in chat if entry["user_type"] == "assistant")
chat_count += assistant_count 
print(chat_count)
len(chat)

4

6

# openai

In [2]:
from openai import OpenAI

OPENAI_API_KEY = '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'

client = OpenAI(api_key=OPENAI_API_KEY)

In [5]:
# client = OpenAI()

audio_file= open("/home/ek/Documents/10Xtutor/SIFA/tenx_ipersona/notebooks/output.mp3", "rb")
transcription = client.audio.transcriptions.create(
  model="whisper-1", 
  file=audio_file,
)
transcription.text

'Hello, world. This is a streaming test.'

In [9]:
# from openai import OpenAI
# OPENAI_API_KEY = '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'

# client = OpenAI(api_key=OPENAI_API_KEY)

with client.audio.speech.with_streaming_response.create(
    model="tts-1",
    voice="alloy",
    input="""I see skies of blue and clouds of white
             The bright blessed days, the dark sacred nights
             And I think to myself
             What a wonderful world""",
) as response:
    print(response)
    # response.stream_to_file("speech.mp3")

<StreamedBinaryAPIResponse [200 OK] type=<class 'bytes'>>

In [12]:
response = client.audio.speech.create(
    model="tts-1",
    voice="alloy",
    input="Hello world! This is a streaming test.",
)

#response.stream_to_file("output.mp3")

In [15]:
response

In [3]:
! apt install python3-pyaudio

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

In [1]:
import os
import requests
from time import time
import pyaudio

url = "https://api.openai.com/v1/audio/speech"
headers = {
    "Authorization": f'Bearer {os.getenv("OPENAI_API_KEY")}',
}

data = {
    "model": "tts-1",
    "input": "This is a test",
    "voice": "shimmer",
    "response_format": "wav",
}

start_time = time()
response = requests.post(url, headers=headers, json=data, stream=True)
if response.status_code == 200:
    print(f"Time to first byte: {int((time() - start_time) * 1000)} ms")
    p = pyaudio.PyAudio()
    stream = p.open(format=8, channels=1, rate=24000, output=True)
    for chunk in response.iter_content(chunk_size=1024):
        stream.write(chunk)
    print(f"Time to complete: {int((time() - start_time) * 1000)} ms")

ModuleNotFoundError: No module named 'pyaudio'